import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ShellComponent } from '../shared/shell.component';
import { TemplateBankService } from '../core/template-bank.service';

@Component({
 selector:'sn-template-bank', standalone:true,
 imports:[CommonModule,FormsModule,ShellComponent],
 template:`
 <sn-shell title="Template Bank"><main class="page">
  <section class="hero panel"><div><small>PLATFORM MEDIA</small><h2>Template Bank</h2><p>Global poster templates for Voting and Ranks.</p></div><button class="primary" (click)="open()">＋ Upload template</button></section>
  @if(error()){<div class="notice error">{{error()}}</div>} @if(success()){<div class="notice success">{{success()}}</div>}
  <section class="settings panel"><div><small>GLOBAL QR SETTINGS</small><h3>Default QR destination</h3><p>Super administrator can change this URL at any time.</p></div><div class="settings-grid">
   <label>Default QR URL<input [(ngModel)]="settings.default_qr_url"></label><label>QR caption<input [(ngModel)]="settings.default_qr_caption"></label>
   <label class="check"><input type="checkbox" [(ngModel)]="settings.allow_guild_qr_override"> Allow guild override</label><button class="primary" (click)="saveSettings()">Save settings</button>
  </div></section>
  <nav class="tabs panel"><button [class.active]="category==='all'" (click)="category='all'">All</button><button [class.active]="category==='voting'" (click)="category='voting'">Voting</button><button [class.active]="category==='ranks'" (click)="category='ranks'">Ranks</button></nav>
  <section class="gallery">
   @for(t of filtered();track t.id){<article class="card panel"><div class="preview"><img [src]="t.preview_url+'?v='+t.version"><b>{{t.category}}</b></div><div class="body"><div class="title"><div><h3>{{t.name}}</h3><small>{{t.key}} · v{{t.version}}</small></div><span [class.on]="t.is_active">{{t.is_active?'ACTIVE':'OFF'}}</span></div><p>{{t.description||'No description'}}</p><div class="meta"><i>{{t.canvas_width}}×{{t.canvas_height}}</i><i>{{t.subcategory||'General'}}</i><i *ngIf="t.is_default">DEFAULT</i></div><footer><button (click)="toggle(t)">{{t.is_active?'Disable':'Enable'}}</button><button (click)="makeDefault(t)">Set default</button><button (click)="manifest(t)">Manifest</button><button class="danger" (click)="remove(t)">Delete</button></footer></div></article>}
   @if(!filtered().length){<article class="empty panel"><h3>No templates</h3><p>Upload the first template.</p></article>}
  </section>
  @if(dialog()){<div class="modal"><form class="dialog panel" (ngSubmit)="create()"><header><div><small>NEW TEMPLATE</small><h2>Upload template</h2></div><button type="button" (click)="dialog.set(false)">×</button></header><div class="grid">
   <label>Name<input required [(ngModel)]="form.name" name="name"></label><label>Key<input required [(ngModel)]="form.key" name="key"></label>
   <label>Category<select [(ngModel)]="form.category" name="category"><option value="voting">Voting</option><option value="ranks">Ranks</option></select></label><label>Subcategory<input [(ngModel)]="form.subcategory" name="subcategory"></label>
   <label>Width<input type="number" [(ngModel)]="form.canvas_width" name="width"></label><label>Height<input type="number" [(ngModel)]="form.canvas_height" name="height"></label>
   <label class="full">Description<textarea [(ngModel)]="form.description" name="description"></textarea></label><label>Background<input required type="file" accept=".png,.jpg,.jpeg,.webp" (change)="pick($event,'background')"></label><label>Preview<input type="file" accept=".png,.jpg,.jpeg,.webp" (change)="pick($event,'preview')"></label>
   <label class="full">Manifest JSON<textarea rows="9" [(ngModel)]="form.manifest_json" name="manifest"></textarea></label></div><footer><button type="button" (click)="dialog.set(false)">Cancel</button><button class="primary" type="submit">Upload</button></footer></form></div>}
 </main></sn-shell>`,
 styles:[`.page{display:grid;gap:1rem}.panel{background:var(--surface-1);border:1px solid var(--line);border-radius:16px}.hero,.settings{padding:1rem;display:flex;justify-content:space-between;gap:1rem;align-items:center}h2,h3,p{margin:0}small{color:var(--primary);letter-spacing:.13em}.hero p,.settings p,.body p,.empty p{color:var(--muted);margin-top:.35rem}button,input,textarea,select{font:inherit;border:1px solid var(--line);border-radius:9px;background:var(--surface-2);color:var(--text);padding:.7rem}button{cursor:pointer}.primary{background:var(--primary);color:#03130e;font-weight:850}.danger{color:#ff9aa8}.settings-grid{display:grid;grid-template-columns:1.4fr 1fr;gap:.6rem;min-width:min(650px,60vw)}label{display:grid;gap:.3rem;color:var(--muted);font-size:.65rem}.check{display:flex;gap:.5rem;align-items:center}.check input{width:auto}.tabs{display:flex;gap:.4rem;padding:.45rem}.tabs .active{background:var(--primary-soft);color:var(--primary)}.gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:.9rem}.card{overflow:hidden}.preview{height:220px;position:relative;background:#050b11}.preview img{width:100%;height:100%;object-fit:cover}.preview b{position:absolute;left:.7rem;top:.7rem;padding:.3rem .5rem;border-radius:99px;background:#071019dd;color:var(--primary)}.body{padding:1rem;display:grid;gap:.75rem}.title{display:flex;justify-content:space-between}.title span{color:#ff9aa8}.title span.on{color:var(--success)}.meta,footer{display:flex;gap:.4rem;flex-wrap:wrap}.meta i{font-style:normal;background:var(--surface-2);padding:.3rem .45rem;border-radius:7px;color:var(--muted)}.empty{grid-column:1/-1;padding:3rem;text-align:center}.notice{padding:.75rem 1rem}.error{color:#ff9aa8}.success{color:var(--success)}.modal{position:fixed;inset:0;z-index:1000;background:#000b;display:grid;place-items:center;padding:1rem}.dialog{width:min(760px,96vw);padding:1rem;max-height:92vh;overflow:auto}.dialog header,.dialog footer{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:.65rem;margin:1rem 0}.full{grid-column:1/-1}@media(max-width:800px){.hero,.settings{align-items:flex-start;flex-direction:column}.settings-grid,.grid{grid-template-columns:1fr;min-width:0;width:100%}.full{grid-column:auto}}`]
})
export class TemplateBankComponent implements OnInit{
 private api=inject(TemplateBankService);templates=signal<any[]>([]);dialog=signal(false);error=signal('');success=signal('');category='all';files:any={};form:any={};settings:any={default_qr_url:'https://discord.lrm-it.com',default_qr_caption:'Visit our website',allow_guild_qr_override:false};
 ngOnInit(){this.reload();this.api.settings().subscribe({next:x=>this.settings=x,error:e=>this.fail(e)})} filtered(){return this.category==='all'?this.templates():this.templates().filter(x=>x.category===this.category)} reload(){this.api.list().subscribe({next:x=>this.templates.set(x.items||[]),error:e=>this.fail(e)})} fail(e:any){this.error.set(e?.error?.detail||e?.message||'Request failed')}
 saveSettings(){this.api.saveSettings(this.settings).subscribe({next:x=>{this.settings=x;this.success.set('Settings saved.')},error:e=>this.fail(e)})} open(){this.form={name:'',key:'',category:'voting',subcategory:'general',description:'',canvas_width:1536,canvas_height:2048,manifest_json:JSON.stringify({schema_version:1,fields:{}},null,2)};this.files={};this.dialog.set(true)} pick(e:any,k:string){this.files[k]=e.target.files?.[0]}
 create(){if(!this.files.background){this.error.set('Background is required.');return}const d=new FormData();for(const k of ['name','key','category','subcategory','description','canvas_width','canvas_height','manifest_json'])d.append(k,String(this.form[k]??''));d.append('background',this.files.background);if(this.files.preview)d.append('preview',this.files.preview);this.api.create(d).subscribe({next:()=>{this.dialog.set(false);this.success.set('Template uploaded.');this.reload()},error:e=>this.fail(e)})}
 toggle(t:any){this.api.update(t.id,{is_active:!t.is_active}).subscribe({next:()=>this.reload(),error:e=>this.fail(e)})} makeDefault(t:any){this.api.update(t.id,{is_default:true}).subscribe({next:()=>this.reload(),error:e=>this.fail(e)})} manifest(t:any){const raw=prompt('Manifest JSON',JSON.stringify(t.manifest||{},null,2));if(raw===null)return;try{this.api.update(t.id,{manifest:JSON.parse(raw)}).subscribe({next:()=>this.reload(),error:e=>this.fail(e)})}catch{this.error.set('Invalid JSON.')}} remove(t:any){if(confirm(`Delete ${t.name}?`))this.api.remove(t.id).subscribe({next:()=>this.reload(),error:e=>this.fail(e)})}
}
