from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies.platform_access import require_superadmin
from app.db.session import get_db_session
from app.models.core import User
from app.services.settings import SettingsService

router=APIRouter(tags=["Public merchant information"])
MODULE="merchant_public_page"
DEFAULTS={
 "business_name":"LRM-IT / GuildConsole","tax_id":"","legal_address":"","actual_address":"","phone":"","email":"",
 "service_description":"GuildConsole надає цифрові послуги з онлайн-доступу до розробленого програмного забезпечення для адміністрування Discord-серверів, автоматизації, безпеки та підключення програмних модулів.",
 "service_terms":"Доступ активується в електронній формі для обраного Discord-сервера після успішної оплати. Фізична доставка не здійснюється. Період активації зазначається до підтвердження платежу.",
 "payment_methods":"Онлайн-оплата цифрових послуг платіжними картками Visa та Mastercard через захищений платіжний шлюз. Валюта списання, опис програмної послуги та остаточна сума відображаються до підтвердження платежу.",
 "service_area":"Цифрові послуги надаються онлайн. Доступність може залежати від обмежень Discord та сторонніх сервісів у країні клієнта.",
 "refund_policy":"Для повернення коштів зверніться до продавця за контактами на цій сторінці, вкажіть номер платежу та причину звернення. Заявка розглядається протягом 7 робочих днів. Кошти повертаються на початковий спосіб оплати у випадках, передбачених законом, або якщо оплачена послуга не була надана.",
 "cancellation_policy":"Скасування можна запросити до активації послуги. Після активації можливість скасування та повернення залежить від невикористаного періоду, причини звернення та вимог чинного законодавства.",
 "public_offer":"Оплата підтверджує, що клієнт ознайомився з описом послуги, ціною, строком активації, правилами повернення та цими умовами й приймає публічну пропозицію щодо надання обраної цифрової послуги.",
 "privacy_policy":"Персональні та пов’язані з оплатою дані обробляються лише для автентифікації клієнта, надання послуги, проведення платежу, запобігання шахрайству та обробки звернень. Дані платіжної картки обробляє платіжний провайдер; GuildConsole їх не зберігає.",
 "updated_label":""
}
SUPPORTED_LOCALES={"en","uk","ru","de","ar","fr","it","pl"}
LOCALIZED_DEFAULTS={
 "en":{"service_description":"GuildConsole provides digital online access to developed software for Discord server administration, automation, security and software modules.","service_terms":"Access is activated electronically for the selected Discord server after successful payment. No physical delivery is provided. The activation period is displayed before payment confirmation.","payment_methods":"Digital services can be paid online by Visa or Mastercard through a secure payment gateway. The charge currency, software service description and final amount are displayed before confirmation.","service_area":"Digital services are provided online. Availability may depend on Discord and third-party service restrictions in the customer's country.","refund_policy":"To request a refund, contact the seller using the details on this page and provide the payment number and reason. Requests are reviewed within 7 business days. Funds are returned to the original payment method where required by law or when the paid service was not provided.","cancellation_policy":"Cancellation may be requested before service activation. After activation, eligibility depends on the unused period, the reason for the request and applicable law.","public_offer":"Payment confirms that the customer has reviewed the service description, price, activation period, refund rules and these terms, and accepts the public offer for the selected digital service.","privacy_policy":"We process personal data only for authentication, service delivery, payments, fraud prevention, support and legal obligations. Payment card data is handled by the payment provider and is not stored by GuildConsole. Necessary cookies and browser storage are used for sessions, security, language and interface preferences. Analytics starts only after consent. You may request access, correction or deletion using the contacts on this page."},
 "ru":{"service_description":"GuildConsole предоставляет цифровой доступ к инструментам администрирования Discord-серверов, автоматизации, безопасности и плагинам.","service_terms":"Доступ активируется в электронной форме для выбранного Discord-сервера после успешной оплаты. Физическая доставка не осуществляется. Период активации указывается до подтверждения платежа.","payment_methods":"Онлайн-оплата картами Visa и Mastercard через подключённого платёжного провайдера. Валюта списания и итоговая сумма отображаются до подтверждения.","service_area":"Цифровые услуги предоставляются онлайн. Доступность может зависеть от ограничений Discord и сторонних сервисов в стране клиента.","refund_policy":"Для возврата средств свяжитесь с продавцом по контактам на этой странице, укажите номер платежа и причину обращения. Заявка рассматривается в течение 7 рабочих дней. Средства возвращаются исходным способом оплаты в предусмотренных законом случаях или если оплаченная услуга не была предоставлена.","cancellation_policy":"Отмену можно запросить до активации услуги. После активации возможность отмены и возврата зависит от неиспользованного периода, причины обращения и требований законодательства.","public_offer":"Оплата подтверждает, что клиент ознакомился с описанием услуги, ценой, сроком активации, правилами возврата и настоящими условиями и принимает публичную оферту на выбранную цифровую услугу.","privacy_policy":"Мы обрабатываем персональные данные только для авторизации, предоставления услуг, проведения платежей, предотвращения мошенничества, поддержки и выполнения требований закона. Данные банковских карт обрабатывает платёжный провайдер; GuildConsole их не хранит. Необходимые cookie и хранилище браузера используются для сессии, безопасности, языка и настроек интерфейса. Аналитика запускается только после согласия. Запросить доступ, исправление или удаление данных можно по контактам на этой странице."},
 "uk":{},
 "de":{"service_description":"GuildConsole bietet digitale Werkzeuge zur Verwaltung, Automatisierung und Absicherung von Discord-Servern.","service_terms":"Der Zugang wird nach erfolgreicher Zahlung elektronisch für den gewählten Server aktiviert. Es erfolgt keine physische Lieferung.","payment_methods":"Online-Zahlung mit Visa oder Mastercard über den angebundenen Zahlungsanbieter. Währung und Endbetrag werden vor der Bestätigung angezeigt.","service_area":"Die digitalen Dienste werden online bereitgestellt. Die Verfügbarkeit kann von Discord und Drittanbietern abhängen.","refund_policy":"Für eine Erstattung kontaktieren Sie den Verkäufer mit Zahlungsnummer und Begründung. Anträge werden innerhalb von 7 Werktagen geprüft.","cancellation_policy":"Eine Stornierung kann vor der Aktivierung beantragt werden. Danach gelten Nutzungszeitraum und anwendbares Recht.","public_offer":"Mit der Zahlung akzeptiert der Kunde Leistungsbeschreibung, Preis, Aktivierungszeitraum, Erstattungsregeln und diese Bedingungen.","privacy_policy":"Personenbezogene Daten werden nur für Anmeldung, Leistungserbringung, Zahlung, Betrugsprävention, Support und gesetzliche Pflichten verarbeitet. Kartendaten speichert GuildConsole nicht. Analysen starten erst nach Einwilligung."},
 "fr":{"service_description":"GuildConsole fournit des outils numériques de gestion, d’automatisation et de sécurité des serveurs Discord.","service_terms":"L’accès est activé électroniquement pour le serveur choisi après paiement. Aucune livraison physique n’est effectuée.","payment_methods":"Paiement en ligne par Visa ou Mastercard via le prestataire connecté. La devise et le montant final sont affichés avant confirmation.","service_area":"Les services numériques sont fournis en ligne et peuvent dépendre des restrictions de Discord et de services tiers.","refund_policy":"Pour demander un remboursement, contactez le vendeur avec le numéro du paiement et le motif. La demande est examinée sous 7 jours ouvrés.","cancellation_policy":"L’annulation peut être demandée avant l’activation. Après activation, elle dépend de la période inutilisée et de la loi applicable.","public_offer":"Le paiement confirme l’acceptation de la description du service, du prix, du délai d’activation, des règles de remboursement et des présentes conditions.","privacy_policy":"Les données personnelles sont traitées uniquement pour l’authentification, le service, les paiements, la prévention de la fraude, l’assistance et les obligations légales. GuildConsole ne stocke pas les données de carte. Les analyses ne démarrent qu’après consentement."},
 "it":{"service_description":"GuildConsole fornisce strumenti digitali per gestione, automazione e sicurezza dei server Discord.","service_terms":"L’accesso viene attivato elettronicamente per il server scelto dopo il pagamento. Non è prevista consegna fisica.","payment_methods":"Pagamento online con Visa o Mastercard tramite il fornitore collegato. Valuta e importo finale sono mostrati prima della conferma.","service_area":"I servizi digitali sono forniti online e possono dipendere dalle restrizioni di Discord e di servizi terzi.","refund_policy":"Per un rimborso contatta il venditore indicando numero del pagamento e motivo. La richiesta viene esaminata entro 7 giorni lavorativi.","cancellation_policy":"La cancellazione può essere richiesta prima dell’attivazione. Dopo dipende dal periodo non utilizzato e dalla legge applicabile.","public_offer":"Il pagamento conferma l’accettazione di descrizione, prezzo, periodo di attivazione, regole di rimborso e presenti condizioni.","privacy_policy":"I dati personali sono trattati solo per autenticazione, servizio, pagamenti, prevenzione frodi, assistenza e obblighi legali. GuildConsole non conserva i dati delle carte. Le analisi iniziano solo dopo il consenso."},
 "pl":{"service_description":"GuildConsole zapewnia cyfrowe narzędzia do zarządzania, automatyzacji i zabezpieczania serwerów Discord.","service_terms":"Dostęp jest aktywowany elektronicznie dla wybranego serwera po płatności. Dostawa fizyczna nie występuje.","payment_methods":"Płatność online kartą Visa lub Mastercard przez podłączonego operatora. Waluta i końcowa kwota są widoczne przed potwierdzeniem.","service_area":"Usługi cyfrowe są świadczone online, a dostępność może zależeć od Discorda i usług zewnętrznych.","refund_policy":"Aby uzyskać zwrot, skontaktuj się ze sprzedawcą, podając numer płatności i powód. Wniosek jest rozpatrywany w ciągu 7 dni roboczych.","cancellation_policy":"Rezygnację można zgłosić przed aktywacją. Później zależy ona od niewykorzystanego okresu i obowiązującego prawa.","public_offer":"Płatność potwierdza akceptację opisu usługi, ceny, okresu aktywacji, zasad zwrotu i niniejszych warunków.","privacy_policy":"Dane osobowe przetwarzamy wyłącznie do logowania, świadczenia usługi, płatności, zapobiegania oszustwom, wsparcia i obowiązków prawnych. GuildConsole nie przechowuje danych kart. Analityka uruchamia się dopiero po zgodzie."},
 "ar":{"service_description":"توفر GuildConsole أدوات رقمية لإدارة خوادم Discord وأتمتتها وحمايتها.","service_terms":"يتم تفعيل الوصول إلكترونياً للخادم المحدد بعد نجاح الدفع، ولا يوجد تسليم مادي.","payment_methods":"الدفع عبر الإنترنت ببطاقات Visa أو Mastercard من خلال مزود الدفع المتصل، وتظهر العملة والمبلغ النهائي قبل التأكيد.","service_area":"تُقدم الخدمات الرقمية عبر الإنترنت وقد يعتمد توفرها على قيود Discord والخدمات الخارجية.","refund_policy":"لطلب استرداد، تواصل مع البائع واذكر رقم الدفع والسبب. تتم مراجعة الطلب خلال 7 أيام عمل.","cancellation_policy":"يمكن طلب الإلغاء قبل التفعيل. بعد التفعيل يعتمد ذلك على الفترة غير المستخدمة والقانون المعمول به.","public_offer":"يؤكد الدفع قبول العميل لوصف الخدمة والسعر وفترة التفعيل وقواعد الاسترداد وهذه الشروط.","privacy_policy":"تُعالج البيانات الشخصية فقط للمصادقة وتقديم الخدمة والدفع ومنع الاحتيال والدعم والالتزامات القانونية. لا تخزن GuildConsole بيانات البطاقة. تبدأ التحليلات بعد الموافقة فقط."}
}

class MerchantPageUpdate(BaseModel):
    business_name:str=Field(max_length=300);tax_id:str=Field(max_length=100);legal_address:str=Field(max_length=500);actual_address:str=Field(max_length=500);phone:str=Field(max_length=100);email:str=Field(max_length=320)
    service_description:str=Field(max_length=10000);service_terms:str=Field(max_length=10000);payment_methods:str=Field(max_length=5000);service_area:str=Field(max_length=5000);refund_policy:str=Field(max_length=10000);cancellation_policy:str=Field(max_length=10000);public_offer:str=Field(max_length=20000);privacy_policy:str=Field(max_length=20000)

async def content(session:AsyncSession,locale:str):
    locale=locale if locale in SUPPORTED_LOCALES else "en"
    service=SettingsService(session)
    legacy=await service.get(0,MODULE,"content",{})
    saved=await service.get(0,MODULE,f"content.{locale}",{})
    localized=LOCALIZED_DEFAULTS.get(locale,LOCALIZED_DEFAULTS["en"])
    legacy_values=legacy if isinstance(legacy,dict) and locale=="uk" else {}
    return {**DEFAULTS,**localized,**legacy_values,**(saved if isinstance(saved,dict) else {}),"locale":locale}

@router.get("/public/privacy-policy")
@router.get("/public/merchant-information",deprecated=True)
async def public_merchant_information(locale:str=Query("en"),session:AsyncSession=Depends(get_db_session)):
    return await content(session,locale)

@router.put("/platform/privacy-policy")
@router.put("/platform/merchant-information",deprecated=True)
async def update_merchant_information(payload:MerchantPageUpdate,locale:str=Query("en"),user:User=Depends(require_superadmin),session:AsyncSession=Depends(get_db_session)):
    locale=locale if locale in SUPPORTED_LOCALES else "en"
    await SettingsService(session).set(guild_id=0,module=MODULE,key=f"content.{locale}",value=payload.model_dump(),updated_by=user.id)
    return await content(session,locale)
