import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { AutomationAction, AutomationCondition, AutomationRule, AutomationService } from '../core/automation.service';
import { ShellComponent } from '../shared/shell.component';
import { TranslatePipe } from '../core/translate.pipe';
import { TranslationService } from '../core/translation.service';
import { ModalService } from '../core/modal.service';
import { ToastService } from '../core/toast.service';

@Component({
 selector:'sn-automations', standalone:true, imports:[CommonModule,FormsModule,ShellComponent,TranslatePipe],
 template:`<sn-shell [title]="'automations.title' | snT:'Automation Designer'">
 <section class="hero"><div><div class="eyebrow">{{ "automations.eyebrow" | snT:"No-code Discord workflows" }}</div><h2>{{ "automations.heading" | snT:"WHEN → IF → THEN" }}</h2><p>{{ "automations.description" | snT:"Create safe automation rules, validate them and test the execution plan before enabling." }}</p></div><button (click)="newRule()">{{ "automations.new" | snT:"New automation" }}</button></section>
 <div class="notice err" *ngIf="error">{{error}}</div>
 <div class="layout">
  <aside class="rules"><div class="rule" *ngFor="let item of items" [class.selected]="selected?.id===item.id" (click)="select(item)"><div><b>{{item.name}}</b><span>{{labelTrigger(item.trigger_type)}}</span></div><em [class.enabled]="item.status==='enabled'">{{item.status}}</em><small>{{item.conditions.length}} {{ "automations.conditions" | snT:"conditions" }} · {{item.actions.length}} {{ "automations.actions" | snT:"actions" }}</small></div><div class="empty" *ngIf="!items.length">{{ "automations.empty" | snT:"No automation rules yet." }}</div></aside>
  <main class="designer" *ngIf="editing">
   <div class="section"><h3>{{ "automations.rule" | snT:"Rule" }}</h3><div class="two"><label>{{ "automations.name" | snT:"Name" }}<input [(ngModel)]="editing.name"></label><label>{{ "automations.trigger" | snT:"Trigger" }}<select [(ngModel)]="editing.trigger_type"><option *ngFor="let t of catalog?.triggers" [value]="t.key">{{t.label}}</option></select></label></div><label>{{ "automations.description_label" | snT:"Description" }}<textarea [(ngModel)]="editing.description" rows="2"></textarea></label></div>
   <div class="flow"><section><div class="step when">{{ "automations.when" | snT:"WHEN" }}</div><b>{{labelTrigger(editing.trigger_type)||('automations.choose_trigger' | snT:'Choose trigger')}}</b></section><section><div class="step if">{{ "automations.if" | snT:"IF" }}</div><b>{{editing.conditions.length}} {{ "automations.condition_singular" | snT:"condition(s)" }}</b></section><section><div class="step then">{{ "automations.then" | snT:"THEN" }}</div><b>{{editing.actions.length}} {{ "automations.action_singular" | snT:"action(s)" }}</b></section></div>
   <div class="section"><div class="head"><h3>{{ "automations.conditions" | snT:"Conditions" }}</h3><button (click)="addCondition()">{{ "automations.add_condition" | snT:"Add condition" }}</button></div><div class="row" *ngFor="let c of editing.conditions;let i=index"><input [(ngModel)]="c.field" placeholder="member.account_age_days"><select [(ngModel)]="c.operator"><option *ngFor="let op of catalog?.operators" [value]="op">{{op}}</option></select><input [(ngModel)]="c.value" placeholder="value"><button class="danger" (click)="editing.conditions.splice(i,1)">×</button></div><p class="muted" *ngIf="!editing.conditions.length">{{ "automations.no_conditions" | snT:"No conditions: every matching trigger passes." }}</p></div>
   <div class="section"><div class="head"><h3>{{ "automations.actions" | snT:"Actions" }}</h3><button (click)="addAction()">{{ "automations.add_action" | snT:"Add action" }}</button></div><div class="action" *ngFor="let a of editing.actions;let i=index"><select [(ngModel)]="a.type"><option *ngFor="let x of catalog?.actions" [value]="x.key">{{x.label}}</option></select><textarea [(ngModel)]="actionJson[i]" (blur)="parseAction(i)" rows="2" placeholder='{"role_id":"123"}'></textarea><button class="danger" (click)="removeAction(i)">{{ "automations.remove" | snT:"Remove" }}</button></div></div>
   <div class="section"><label class="check"><input type="checkbox" [(ngModel)]="editing.stop_on_error"> {{ "automations.stop_on_error" | snT:"Stop workflow after the first failed action" }}</label><label>{{ "automations.auto_disable" | snT:"Auto-disable after failed runs" }}<input type="number" min="1" max="100" [(ngModel)]="editing.max_failures"></label><p class="muted" *ngIf="editing.disabled_reason">{{editing.disabled_reason}}</p></div>
   <div class="toolbar"><button (click)="save()" [disabled]="saving">{{ saving ? ('automations.saving' | snT:'Saving…') : ('automations.save' | snT:'Save draft') }}</button><button *ngIf="selected" (click)="changeStatus(selected.status==='enabled'?'disabled':'enabled')">{{ selected.status==='enabled' ? ('automations.disable' | snT:'Disable') : ('automations.enable' | snT:'Enable') }}</button><button *ngIf="selected" (click)="openDryRun()">{{ "automations.dry_run" | snT:"Dry-run" }}</button><button *ngIf="selected" class="danger" (click)="remove()">{{ "automations.delete" | snT:"Delete" }}</button></div>
  </main>
 </div>
 <section class="modal" *ngIf="showDry"><div class="dialog"><div class="head"><h3>{{ "automations.dry_context" | snT:"Dry-run context" }}</h3><button (click)="showDry=false">{{ "automations.close" | snT:"Close" }}</button></div><p>{{ "automations.dry_help" | snT:"Provide a JSON event payload. No Discord action will be executed." }}</p><textarea [(ngModel)]="contextJson" rows="10"></textarea><button (click)="runDry()">{{ "automations.evaluate" | snT:"Evaluate rule" }}</button><pre *ngIf="dryResult">{{dryResult|json}}</pre></div></section>
 </sn-shell>`,
 styles:[`.hero,.rules,.designer,.section,.dialog{border:1px solid var(--line);background:rgba(16,22,38,.72);border-radius:18px}.hero{padding:1.3rem;display:flex;justify-content:space-between;gap:1rem;align-items:center}.eyebrow{color:var(--primary);text-transform:uppercase;letter-spacing:.12em;font-size:.72rem}.hero h2{margin:.2rem 0}.hero p,.muted,.rule span,.rule small{color:var(--muted)}button{padding:.65rem .9rem;border-radius:10px;background:var(--primary-soft);color:var(--text);border:1px solid var(--line)}.layout{display:grid;grid-template-columns:300px 1fr;gap:1rem;margin-top:1rem}.rules{padding:.6rem;height:max-content}.rule{padding:.8rem;border-radius:12px;display:grid;gap:.4rem;cursor:pointer;border:1px solid transparent}.rule:hover,.rule.selected{background:var(--primary-soft);border-color:var(--line)}.rule div{display:grid}.rule em{justify-self:start;font-style:normal;color:#ffd08a;text-transform:uppercase;font-size:.68rem}.rule em.enabled{color:#74e9b3}.designer{padding:1rem;display:grid;gap:1rem}.section{padding:1rem}.section h3{margin-top:0}.two{display:grid;grid-template-columns:1fr 1fr;gap:1rem}label{display:grid;gap:.4rem;color:var(--muted)}input,select,textarea{background:#0c1323;color:var(--text);border:1px solid var(--line);padding:.75rem;border-radius:10px;width:100%}.flow{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}.flow section{border:1px solid var(--line);border-radius:14px;padding:1rem}.step{font-weight:900;font-size:.72rem;letter-spacing:.12em;margin-bottom:.5rem}.when{color:#7fb8ff}.if{color:#ffd08a}.then{color:#74e9b3}.head,.toolbar{display:flex;justify-content:space-between;gap:.6rem;align-items:center}.row{display:grid;grid-template-columns:2fr 1fr 2fr auto;gap:.5rem;margin:.5rem 0}.action{display:grid;grid-template-columns:1.2fr 2fr auto;gap:.5rem;margin:.5rem 0}.danger{color:#ff91a5}.check{display:flex;grid-auto-flow:column;justify-content:start;align-items:center}.check input{width:auto}.modal{position:fixed;inset:0;background:rgba(2,5,12,.78);display:grid;place-items:center;padding:1rem;z-index:20}.dialog{width:min(850px,100%);padding:1rem;max-height:90vh;overflow:auto}.dialog pre{white-space:pre-wrap;background:#09101d;padding:1rem;border-radius:12px}.notice{padding:1rem}.err{color:#ff91a5}.empty{padding:1rem;color:var(--muted)}@media(max-width:900px){.layout{grid-template-columns:1fr}.two,.flow{grid-template-columns:1fr}.row,.action{grid-template-columns:1fr}.hero{align-items:flex-start;flex-direction:column}}`]
})
export class AutomationsComponent implements OnInit{
 guildId='';items:AutomationRule[]=[];selected:AutomationRule|null=null;editing:any=null;catalog:any=null;actionJson:string[]=[];error='';saving=false;showDry=false;contextJson='{"member":{"id":"123","account_age_days":30,"roles":[]}}';dryResult:any=null;
 constructor(private api:AutomationService,private route:ActivatedRoute,private i18n:TranslationService,private modal:ModalService,private toast:ToastService){}
 ngOnInit(){this.guildId=this.route.snapshot.paramMap.get('guildId') ?? '';this.api.catalog(this.guildId).subscribe(v=>this.catalog=v);this.load()}
 load(){this.api.list(this.guildId).subscribe({next:v=>this.items=v,error:e=>this.error=e?.error?.detail||this.i18n.t('automations.load_error','Unable to load automations.')})}
 newRule(){this.selected=null;this.editing={name:'New automation',description:'',trigger_type:'member.joined',conditions:[] as AutomationCondition[],actions:[{type:'audit.write',parameters:{event_type:'automation.triggered'}} as AutomationAction],stop_on_error:true,max_failures:5};this.syncJson()}
 select(item:AutomationRule){this.selected=item;this.editing=JSON.parse(JSON.stringify(item));this.syncJson()}
 syncJson(){this.actionJson=(this.editing?.actions||[]).map((a:AutomationAction)=>JSON.stringify(a.parameters||{},null,2))}
 labelTrigger(key:string){return this.catalog?.triggers?.find((x:any)=>x.key===key)?.label||key}
 addCondition(){this.editing.conditions.push({field:'member.id',operator:'exists',value:null})}
 addAction(){this.editing.actions.push({type:'audit.write',parameters:{}});this.actionJson.push('{}')}
 removeAction(i:number){this.editing.actions.splice(i,1);this.actionJson.splice(i,1)}
 parseAction(i:number){try{this.editing.actions[i].parameters=JSON.parse(this.actionJson[i]||'{}');this.error=''}catch{this.error=this.i18n.t('automations.action_json_error','Action {index} parameters must be valid JSON.').replace('{index}',String(i+1))}}
 save(){for(let i=0;i<this.actionJson.length;i++)this.parseAction(i);if(this.error)return;this.saving=true;const payload={name:this.editing.name,description:this.editing.description||null,trigger_type:this.editing.trigger_type,conditions:this.editing.conditions,actions:this.editing.actions,stop_on_error:this.editing.stop_on_error,max_failures:this.editing.max_failures||5};const req=this.selected?this.api.update(this.guildId,this.selected.id,payload):this.api.create(this.guildId,payload);req.subscribe({next:v=>{this.saving=false;this.selected=v;this.editing=JSON.parse(JSON.stringify(v));this.syncJson();this.load()},error:e=>{this.saving=false;this.error=e?.error?.detail||this.i18n.t('automations.save_error','Unable to save rule.')}})}
 changeStatus(status:string){if(!this.selected)return;this.api.status(this.guildId,this.selected.id,status).subscribe({next:v=>{this.selected=v;this.editing=JSON.parse(JSON.stringify(v));this.load()},error:e=>this.error=e?.error?.detail||this.i18n.t('automations.status_error','Unable to change status.')})}
 openDryRun(){this.showDry=true;this.dryResult=null}
 runDry(){if(!this.selected)return;try{const context=JSON.parse(this.contextJson);this.api.dryRun(this.guildId,this.selected.id,context).subscribe({next:v=>this.dryResult=v,error:e=>this.error=e?.error?.detail||this.i18n.t('automations.dry_error','Dry-run failed.')})}catch{this.error=this.i18n.t('automations.dry_json_error','Dry-run context must be valid JSON.')}}
 async remove(){if(!this.selected||!await this.modal.confirm(this.i18n.t('automations.delete_confirm','Delete {name}?').replace('{name}',this.selected.name),{title:this.i18n.t('ui.confirm_title','Confirm action'),confirmLabel:this.i18n.t('ui.confirm','Confirm'),cancelLabel:this.i18n.t('ui.cancel','Cancel'),danger:true}))return;this.api.remove(this.guildId,this.selected.id).subscribe({next:()=>{this.selected=null;this.editing=null;this.load();this.toast.success(this.i18n.t('ui.success','Completed'),this.i18n.t('automations.deleted_success','Automation rule deleted.'))},error:e=>this.error=e?.error?.detail||this.i18n.t('automations.delete_error','Unable to delete rule.')})}
}
