import {Component,OnInit,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {DatePipe,DecimalPipe,NgTemplateOutlet} from '@angular/common';
import {BillingPayment,BillingPlan,BillingProviders,BillingService,BillingSubscription,BillingWallet} from '../core/billing.service';
import {ShellComponent} from '../shared/shell.component';
import {TranslationService} from '../core/translation.service';

type BillingTab='merchant'|'modules'|'pricing'|'payments';

@Component({standalone:true,imports:[FormsModule,DatePipe,DecimalPipe,NgTemplateOutlet,ShellComponent],template:`
<sn-shell title="Billing"><main class="page">
<header><span>SUPERADMIN</span><h2>Billing</h2><p>Server subscriptions, merchant providers and payment operations.</p></header>
<nav class="tabs" aria-label="Billing sections">
  <button [class.active]="tab()==='merchant'" (click)="tab.set('merchant')">Merchant</button>
  <button [class.active]="tab()==='modules'" (click)="tab.set('modules')">Module groups</button>
  <button [class.active]="tab()==='pricing'" (click)="tab.set('pricing')">Pricing</button>
  <button [class.active]="tab()==='payments'" (click)="tab.set('payments')">Processed payments</button>
</nav>
@if(error()){<div class="notice error">{{error()}}</div>}@if(success()){<div class="notice success">{{success()}}</div>}

@if(tab()==='merchant'){<section class="tab-page"><div class="section-head"><div><h3>Merchant settings</h3><p>Credentials are encrypted in the platform vault. Blank secrets keep their current values.</p></div></div>
<div class="gateway-grid">
<article class="card"><div class="gateway-head"><h3>LiqPay</h3><button type="button" class="gateway-toggle" [class.on]="providerForm.liqpay_enabled" (click)="providerForm.liqpay_enabled=!providerForm.liqpay_enabled">{{providerForm.liqpay_enabled?'Enabled':'Disabled'}}</button></div><label>Public key<input [(ngModel)]="providerForm.liqpay_public_key"></label><label>Private key<input type="password" [(ngModel)]="providerForm.liqpay_private_key" [placeholder]="secretSaved('liqpay','private_key')?'Saved · enter only to replace':''"></label><ng-container *ngTemplateOutlet="gatewayStatus;context:{$implicit:'liqpay'}"></ng-container></article>
<article class="card"><div class="gateway-head"><h3>Hutko</h3><button type="button" class="gateway-toggle" [class.on]="providerForm.hutko_enabled" (click)="providerForm.hutko_enabled=!providerForm.hutko_enabled">{{providerForm.hutko_enabled?'Enabled':'Disabled'}}</button></div><label>Merchant ID<input [(ngModel)]="providerForm.hutko_merchant_id"></label><label>Secret key<input type="password" [(ngModel)]="providerForm.hutko_secret_key" [placeholder]="secretSaved('hutko','secret_key')?'Saved · enter only to replace':''"></label><ng-container *ngTemplateOutlet="gatewayStatus;context:{$implicit:'hutko'}"></ng-container></article>
<article class="card"><div class="gateway-head"><h3>Tranzzo</h3><button type="button" class="gateway-toggle" [class.on]="providerForm.tranzzo_enabled" (click)="providerForm.tranzzo_enabled=!providerForm.tranzzo_enabled">{{providerForm.tranzzo_enabled?'Enabled':'Disabled'}}</button></div><label>POS ID<input [(ngModel)]="providerForm.tranzzo_pos_id"></label><label>API key<input type="password" [(ngModel)]="providerForm.tranzzo_api_key" [placeholder]="secretSaved('tranzzo','api_key')?'Saved · enter only to replace':''"></label><label>Endpoints key<input type="password" [(ngModel)]="providerForm.tranzzo_endpoints_key" [placeholder]="secretSaved('tranzzo','endpoints_key')?'Saved · enter only to replace':''"></label><label>API secret<input type="password" [(ngModel)]="providerForm.tranzzo_api_secret" [placeholder]="secretSaved('tranzzo','api_secret')?'Saved · enter only to replace':''"></label><ng-container *ngTemplateOutlet="gatewayStatus;context:{$implicit:'tranzzo'}"></ng-container></article>
<article class="card"><div class="gateway-head"><h3>PayPro Global</h3><button type="button" class="gateway-toggle" [class.on]="providerForm.payproglobal_enabled" (click)="providerForm.payproglobal_enabled=!providerForm.payproglobal_enabled">{{providerForm.payproglobal_enabled?'Enabled':'Disabled'}}</button></div><label>Product ID<input [(ngModel)]="providerForm.payproglobal_product_id"></label><label>API key<input type="password" [(ngModel)]="providerForm.payproglobal_api_key" [placeholder]="secretSaved('payproglobal','api_key')?'Saved · enter only to replace':''"></label><label>Webhook secret<input type="password" [(ngModel)]="providerForm.payproglobal_webhook_secret" [placeholder]="secretSaved('payproglobal','webhook_secret')?'Saved · enter only to replace':''"></label><ng-container *ngTemplateOutlet="gatewayStatus;context:{$implicit:'payproglobal'}"></ng-container></article>
<article class="card"><div class="gateway-head"><h3>Paddle</h3><button type="button" class="gateway-toggle" [class.on]="providerForm.paddle_enabled" (click)="providerForm.paddle_enabled=!providerForm.paddle_enabled">{{providerForm.paddle_enabled?'Enabled':'Disabled'}}</button></div><label>Client-side token<input [(ngModel)]="providerForm.paddle_client_token"></label><label>API key<input type="password" [(ngModel)]="providerForm.paddle_api_key" [placeholder]="secretSaved('paddle','api_key')?'Saved · enter only to replace':''"></label><label>Webhook secret<input type="password" [(ngModel)]="providerForm.paddle_webhook_secret" [placeholder]="secretSaved('paddle','webhook_secret')?'Saved · enter only to replace':''"></label><div class="period-ids"><label>Monthly price ID<input [(ngModel)]="providerForm.paddle_monthly_price_id"></label><label>Quarterly price ID<input [(ngModel)]="providerForm.paddle_quarterly_price_id"></label><label>Yearly price ID<input [(ngModel)]="providerForm.paddle_yearly_price_id"></label></div><ng-container *ngTemplateOutlet="gatewayStatus;context:{$implicit:'paddle'}"></ng-container></article>
<article class="card"><div class="gateway-head"><h3>FastSpring</h3><button type="button" class="gateway-toggle" [class.on]="providerForm.fastspring_enabled" (click)="providerForm.fastspring_enabled=!providerForm.fastspring_enabled">{{providerForm.fastspring_enabled?'Enabled':'Disabled'}}</button></div><label>Store ID<input [(ngModel)]="providerForm.fastspring_store_id"></label><div class="two-fields"><label>API username<input type="password" [(ngModel)]="providerForm.fastspring_api_username" [placeholder]="secretSaved('fastspring','api_username')?'Saved · enter only to replace':''"></label><label>API password<input type="password" [(ngModel)]="providerForm.fastspring_api_password" [placeholder]="secretSaved('fastspring','api_password')?'Saved · enter only to replace':''"></label></div><label>Webhook secret<input type="password" [(ngModel)]="providerForm.fastspring_webhook_secret" [placeholder]="secretSaved('fastspring','webhook_secret')?'Saved · enter only to replace':''"></label><div class="period-ids"><label>Monthly product<input [(ngModel)]="providerForm.fastspring_monthly_product"></label><label>Quarterly product<input [(ngModel)]="providerForm.fastspring_quarterly_product"></label><label>Yearly product<input [(ngModel)]="providerForm.fastspring_yearly_product"></label></div><ng-container *ngTemplateOutlet="gatewayStatus;context:{$implicit:'fastspring'}"></ng-container></article>
</div>
<ng-template #gatewayStatus let-provider><span class="status" [class.ready]="providerInfo(provider)?.active">{{providerInfo(provider)?.active?'Ready':providerInfo(provider)?.configured?'Disabled':'Configuration required'}}</span></ng-template>
<button class="primary save-wide" (click)="saveProviderSettings()">Save merchant settings</button>
</section>}

@if(tab()==='modules'){<section class="tab-page"><div class="section-head"><div><h3>Free and Paid modules</h3><p>One Paid Modules subscription unlocks every module assigned to the Paid group.</p></div></div>
<article class="card plans"><div class="plan heading"><span>Module</span><span>Group</span><span></span></div>@for(plan of plans();track plan.plugin_key){<div class="plan"><div><b>{{plan.name||plan.plugin_key}}</b><small>{{plan.plugin_key}}</small></div><select [(ngModel)]="plan.is_free"><option [ngValue]="true">Free</option><option [ngValue]="false">Paid</option></select><button class="primary" (click)="save(plan)">Save</button></div>}</article></section>}

@if(tab()==='pricing'){<section class="tab-page"><div class="section-head"><div><h3>Server activation price</h3><p>Set the monthly price for one Discord server and discounts for longer activation periods.</p></div></div>
<article class="card package"><label>Monthly price, USD<input type="number" min="0" step="1" [(ngModel)]="package.monthly_price"></label><label>3-month discount, %<input type="number" min="0" max="90" step="0.01" [(ngModel)]="package.quarterly_discount_percent"><small>Total: {{calculatedPrice(3,package.quarterly_discount_percent)|number:'1.2-2'}} USD</small></label><label>12-month discount, %<input type="number" min="0" max="90" step="0.01" [(ngModel)]="package.yearly_discount_percent"><small>Total: {{calculatedPrice(12,package.yearly_discount_percent)|number:'1.2-2'}} USD</small></label><button class="primary" (click)="savePackage()">Save pricing</button></article>
<div class="grid"><article class="card"><h3>Grant subscription manually</h3><label>Discord server ID<input type="text" inputmode="numeric" pattern="[0-9]*" [(ngModel)]="grant.guild_id"></label><label>Period<select [(ngModel)]="grant.billing_period"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option><option value="manual">Manual</option></select></label><label>Access days<input type="number" min="1" max="3660" [(ngModel)]="grant.days"></label><button class="primary" (click)="grantAccess()">Grant Paid Modules</button></article>
<article class="card"><div class="title"><div><h3>Subscriptions</h3><p>Active and historical access.</p></div><button class="secondary" (click)="load()">Refresh</button></div><div class="subscriptions">@for(x of subscriptions();track x.id){<div class="subscription"><div><b>Guild {{x.guild_id}}</b><small>{{x.billing_period}}</small></div><span [class.ready]="x.status==='active'">{{x.status}}</span><time>{{x.expires_at|date:'mediumDate'}}</time>@if(x.status==='active'){<button class="danger" (click)="revoke(x)">Revoke</button>}</div>}@empty{<p>No subscriptions yet.</p>}</div></article></div></section>}

@if(tab()==='payments'){<section class="tab-page"><div class="section-head"><div><h3>Processed payments</h3><p>Latest 250 payment attempts with provider and verification status.</p></div><button class="secondary" (click)="load()">Refresh</button></div>
<article class="card payments"><div class="payment heading"><span>Order</span><span>Server</span><span>Package</span><span>Amount</span><span>Provider</span><span>Status</span><span>Date</span></div>@for(x of payments();track x.id){<div class="payment"><code [title]="x.order_reference">{{x.order_reference}}</code><span class="payment-server"><b>{{x.guild_name||'Discord server'}}</b><small>{{x.guild_id}}</small></span><span>Paid Modules</span><span>{{x.amount}} {{x.currency}}</span><span>{{providerLabel(x.provider)}}</span><b [class.ready]="x.status==='paid'">{{paymentStatus(x.status)}}</b><time>{{x.created_at|date:'short'}}</time></div>}@empty{<p>No payment attempts yet.</p>}</article></section>}
</main></sn-shell>`,styles:[`
.page{max-width:1200px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}header span{color:var(--primary);font-size:.68rem;font-weight:900;letter-spacing:.14em}h2,h3,p{margin:.25rem 0}p,small{color:var(--muted)}
.tabs{display:flex;gap:.45rem;padding:.4rem;background:var(--panel);border:1px solid var(--line);border-radius:13px;overflow:auto}.tabs button{min-height:54px;white-space:nowrap;color:var(--muted);background:transparent;border:1px solid transparent;line-height:1.2}.tabs button.active{color:#07120f;background:var(--primary);border-color:var(--primary)}
.tab-page{display:grid;gap:1rem}.section-head{display:flex;justify-content:space-between;align-items:center;padding:.3rem .2rem}.card,.notice{padding:1.1rem;border:1px solid var(--line);border-radius:15px;background:var(--panel);display:grid;gap:1rem}.title{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.grid.single{grid-template-columns:minmax(0,720px)}.package{grid-template-columns:repeat(3,minmax(0,1fr)) minmax(180px,auto);align-items:stretch}.package label{grid-template-rows:1.1rem 52px 1rem;align-content:end}.package input{height:52px;box-sizing:border-box}.package>.primary{height:52px;align-self:center;white-space:nowrap}.plans,.payments{overflow:auto}.plan{min-width:620px;display:grid;grid-template-columns:minmax(0,1fr) minmax(160px,225px) minmax(125px,auto);gap:.8rem;align-items:center;padding:.7rem;border-top:1px solid var(--line)}.plan div{display:grid;min-width:0}.plan b,.plan small{overflow:hidden;text-overflow:ellipsis}.plan button{width:100%;white-space:nowrap}.heading{color:var(--muted);font-size:.68rem;text-transform:uppercase}.wallet strong{color:var(--primary)}
label{display:grid;gap:.35rem;color:var(--muted);font-size:.75rem}input,select{padding:.7rem;color:var(--text);background:var(--panel-2);border:1px solid var(--line);border-radius:9px}button{padding:.67rem .85rem;border-radius:9px;font-weight:800;cursor:pointer}.primary{border:0;background:var(--primary)}.secondary,.danger{background:transparent;color:var(--text);border:1px solid var(--line)}.danger{color:#ff8d96}.save-wide{justify-self:end}.status{color:var(--muted)}.ready{color:var(--success)!important}
.subscription{display:grid;grid-template-columns:1fr 80px 120px 75px;gap:.6rem;align-items:center;padding:.7rem;border-top:1px solid var(--line)}.subscription div,.wallet div{display:grid}.wallet{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding:.75rem;border-top:1px solid var(--line)}.payment{min-width:1120px;display:grid;grid-template-columns:minmax(250px,1.7fr) minmax(210px,1.2fr) 1fr .7fr .7fr 1fr .9fr;gap:.8rem;padding:.7rem;border-top:1px solid var(--line);align-items:center}.payment code{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.payment-server{display:grid;min-width:0}.payment-server b,.payment-server small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.error{color:#ff8d96}.success{color:var(--success)}
.check{display:flex;align-items:center;gap:.5rem}.gateway-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.gateway-grid .card{align-content:start}.gateway-head{display:flex;justify-content:space-between;align-items:center;gap:1rem}.gateway-toggle{min-width:110px;background:transparent;color:var(--muted);border:1px solid var(--line)}.gateway-toggle.on{color:var(--success);border-color:var(--success)}.period-ids{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.6rem}.two-fields{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.form-actions{display:flex;gap:.6rem;flex-wrap:wrap}.form-actions .primary{flex:1}.smtp{margin-top:1rem}.smtp-grid{display:grid;grid-template-columns:2fr .6fr 1.2fr 1.2fr 1.2fr 1.2fr;gap:.7rem}.smtp-test{display:grid;grid-template-columns:minmax(220px,1fr) auto auto;gap:.6rem}.rules,.cards{display:grid;gap:.4rem}.rule-row,.card-entry{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.5rem}.rule-main,.card-row{display:grid;gap:.7rem;padding:.65rem;border:1px solid var(--line);border-radius:8px;text-align:left;color:var(--text);background:var(--panel-2)}.rule-main{grid-template-columns:1fr auto auto}.card-row{grid-template-columns:1fr .5fr .7fr .7fr}.rule-row>.danger,.card-entry>.danger{white-space:nowrap}
@media(max-width:850px){.grid,.package,.smtp-grid,.gateway-grid{grid-template-columns:1fr}.smtp-test{grid-template-columns:1fr}.subscription{grid-template-columns:1fr auto}.subscription time{grid-column:1}.plan{min-width:520px;grid-template-columns:minmax(0,1fr) 150px 120px}}
@media(max-width:650px){.period-ids,.two-fields{grid-template-columns:1fr}}
@media(max-width:600px){.plan{min-width:0;grid-template-columns:1fr}.plan.heading{display:none}}
`]})
export class BillingComponent implements OnInit{
 tab=signal<BillingTab>('merchant');plans=signal<BillingPlan[]>([]);subscriptions=signal<BillingSubscription[]>([]);providers=signal<BillingProviders|null>(null);payments=signal<BillingPayment[]>([]);wallets=signal<BillingWallet[]>([]);discounts=signal<any>({cards:[],tenure:[],maximum_combined_percent:50});
 package:BillingPlan={plugin_key:'__paid_modules__',is_free:false,enabled:true,currency:'USD',monthly_price:1.10,quarterly_price:2.89,yearly_price:10.07,quarterly_discount_percent:10,yearly_discount_percent:23.5};error=signal('');success=signal('');
 grant={guild_id:'',plugin_key:'__paid_modules__',billing_period:'monthly',days:30};credit={discord_user_id:'',amount:0,comment:''};
 cardForm:any={code:'',amount_usd:null,active:true,valid_from:null,valid_until:null,max_redemptions:null};tenureForm:any={minimum_months:6,percent:5,active:true};
 providerForm:any={liqpay_enabled:true,liqpay_public_key:'',liqpay_private_key:'',hutko_enabled:false,hutko_merchant_id:'',hutko_secret_key:'',tranzzo_enabled:false,tranzzo_pos_id:'',tranzzo_api_key:'',tranzzo_endpoints_key:'',tranzzo_api_secret:'',payproglobal_enabled:false,payproglobal_product_id:'',payproglobal_api_key:'',payproglobal_webhook_secret:'',paddle_enabled:false,paddle_client_token:'',paddle_api_key:'',paddle_webhook_secret:'',paddle_monthly_price_id:'',paddle_quarterly_price_id:'',paddle_yearly_price_id:'',fastspring_enabled:false,fastspring_store_id:'',fastspring_api_username:'',fastspring_api_password:'',fastspring_webhook_secret:'',fastspring_monthly_product:'',fastspring_quarterly_product:'',fastspring_yearly_product:''};
 constructor(private api:BillingService,private i18n:TranslationService){}ngOnInit(){this.load()}
 async load(){
  this.error.set('');
  const requests=[this.api.plans(),this.api.subscriptions(),this.api.providers(),this.api.payments(),this.api.paidPackage()];
  const [p,s,c,j,pkg]=await Promise.allSettled(requests);
  if(p.status==='fulfilled')this.plans.set(p.value as BillingPlan[]);
  if(s.status==='fulfilled')this.subscriptions.set(s.value as BillingSubscription[]);
  if(j.status==='fulfilled')this.payments.set(j.value as BillingPayment[]);
  if(pkg.status==='fulfilled')this.package=pkg.value as BillingPlan;
  if(c.status==='fulfilled'){
   const providers=c.value as BillingProviders;this.providers.set(providers);
   for(const provider of ['liqpay','hutko','tranzzo','payproglobal','paddle','fastspring']){const config:any=(providers as any)[provider]||{};this.providerForm[provider+'_enabled']=!!config.enabled;for(const [key,value] of Object.entries(config)){if(!['enabled','configured','active','secret_saved'].includes(key))this.providerForm[provider+'_'+key]=value||''}}
  }
  const failed=[p,s,c,j,pkg].find(x=>x.status==='rejected') as PromiseRejectedResult|undefined;
  if(failed){const e:any=failed.reason;this.error.set(e?.error?.detail||this.t('load_error','Some billing data could not be loaded.'))}
 }
 async saveCard(){try{const{id,...values}=this.cardForm;const payload={...values,valid_until:values.valid_until?new Date(values.valid_until).toISOString():null};if(id)await this.api.updateDiscountCard(id,payload);else await this.api.saveDiscountCard(payload);this.resetCard();this.done(this.t('card_saved','Discount card saved.'));await this.load()}catch(e:any){this.fail(e,this.t('card_save_error','Unable to save discount card.'))}}
 editCard(x:any){this.cardForm={...x,valid_until:x.valid_until?String(x.valid_until).slice(0,16):null}}
 resetCard(){this.cardForm={code:'',amount_usd:null,active:true,valid_from:null,valid_until:null,max_redemptions:null}}
 async deleteCard(x:any){try{await this.api.deleteDiscountCard(x.id);if(this.cardForm.id===x.id)this.resetCard();this.done(this.t('card_deleted','Discount card deleted.'));await this.load()}catch(e:any){this.fail(e,this.t('card_delete_error','Unable to delete discount card.'))}}
 async saveTenure(){try{const{id,...payload}=this.tenureForm;if(id)await this.api.updateTenureDiscount(id,payload);else await this.api.saveTenureDiscount(payload);this.resetTenure();this.done(this.t('loyalty_saved','Loyalty rule saved.'));await this.load()}catch(e:any){this.fail(e,this.t('loyalty_save_error','Unable to save loyalty rule.'))}}
 editTenure(x:any){this.tenureForm={...x}}
 resetTenure(){this.tenureForm={minimum_months:6,percent:5,active:true}}
 async deleteTenure(x:any){try{await this.api.deleteTenureDiscount(x.id);if(this.tenureForm.id===x.id)this.resetTenure();this.done(this.t('loyalty_deleted','Loyalty rule deleted.'));await this.load()}catch(e:any){this.fail(e,this.t('loyalty_delete_error','Unable to delete loyalty rule.'))}}
 calculatedPrice(months:number,discount:number|undefined){return Number(this.package.monthly_price||0)*months*(1-Number(discount||0)/100)}
 async savePackage(){try{this.package=await this.api.savePackage(this.package);this.done(this.t('pricing_saved','Server activation pricing saved.'))}catch(e:any){this.fail(e,this.t('pricing_save_error','Unable to save pricing.'))}}
 async topUp(){try{await this.api.creditWallet(this.credit);this.credit.amount=0;this.credit.comment='';this.done(this.t('balance_updated','Owner balance updated.'));await this.load()}catch(e:any){this.fail(e,this.t('funds_error','Unable to add funds.'))}}
 async saveProviderSettings(){try{await this.api.saveProviders(this.providerForm);for(const key of Object.keys(this.providerForm)){if(['private_key','secret_key','api_key','webhook_secret','api_username','api_password','endpoints_key','api_secret'].some(x=>key.endsWith(x)))this.providerForm[key]=''}this.done(this.t('merchant_saved','Merchant settings saved.'));await this.load()}catch(e:any){this.fail(e,this.t('merchant_save_error','Unable to save merchant settings.'))}}
 async save(x:BillingPlan){try{await this.api.savePlan(x);this.done(this.t('group_saved','Module group saved.'))}catch(e:any){this.fail(e,this.t('group_save_error','Unable to save module group.'))}}
 async grantAccess(){try{await this.api.grant(this.grant);this.done(this.t('subscription_granted','Paid Modules subscription granted.'));await this.load()}catch(e:any){this.fail(e,this.t('subscription_grant_error','Unable to grant subscription.'))}}
 async revoke(x:BillingSubscription){try{await this.api.revoke(x.id);this.done(this.t('subscription_revoked','Subscription revoked.'));await this.load()}catch(e:any){this.fail(e,this.t('subscription_revoke_error','Unable to revoke subscription.'))}}
 paymentStatus(status:string){return status==='created'?this.t('payment_created','Created · not paid'):status==='paid'?this.t('payment_paid','Paid'):status==='failed'?this.t('payment_failed','Failed'):status}
 providerInfo(provider:string):any{return(this.providers() as any)?.[provider]}
 secretSaved(provider:string,field:string){const saved=this.providerInfo(provider)?.secret_saved;return typeof saved==='boolean'?saved:!!saved?.[field]}
 providerLabel(provider:string){const labels:Record<string,string>={liqpay:'LiqPay',hutko:'Hutko',tranzzo:'Tranzzo',payproglobal:'PayPro Global',paddle:'Paddle',fastspring:'FastSpring',balance:'Balance'};return labels[provider]||'Legacy gateway'}
 t(key:string,fallback:string){return this.i18n.t(`billing.${key}`,fallback)}
 done(message:string){this.error.set('');this.success.set(message)}fail(e:any,fallback:string){this.success.set('');const detail=e?.error?.detail;this.error.set(Array.isArray(detail)?detail.map((x:any)=>x?.msg||String(x)).join(' · '):(typeof detail==='string'?detail:fallback))}
}
