import {Component,OnInit,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {DatePipe} from '@angular/common';
import {BillingPlan,BillingService,BillingSubscription} from '../core/billing.service';
import {ShellComponent} from '../shared/shell.component';
@Component({standalone:true,imports:[FormsModule,DatePipe,ShellComponent],template:`
<sn-shell title="Billing"><main class="page"><header><span>SUPERADMIN</span><h2>Billing</h2><p>Plugin prices, subscriptions and payment access.</p></header>
@if(error()){<div class="notice error">{{error()}}</div>}@if(success()){<div class="notice success">{{success()}}</div>}
<section class="card"><div class="title"><div><h3>Plugin plans</h3><p>The core and selected plugins remain free. Prices are per Discord server.</p></div></div>
<div class="plans"><div class="plan head"><span>Plugin</span><span>Access</span><span>1 month</span><span>3 months</span><span>12 months</span><span></span></div>
@for(plan of plans();track plan.plugin_key){<div class="plan"><div><b>{{plan.name||plan.plugin_key}}</b><small>{{plan.plugin_key}}</small></div><label class="free"><input type="checkbox" [(ngModel)]="plan.is_free"> Free</label><label><input type="number" min="0" step="1" [(ngModel)]="plan.monthly_price" [disabled]="plan.is_free"><small>{{plan.currency}}</small></label><label><input type="number" min="0" step="1" [(ngModel)]="plan.quarterly_price" [disabled]="plan.is_free"><small>{{plan.currency}}</small></label><label><input type="number" min="0" step="1" [(ngModel)]="plan.yearly_price" [disabled]="plan.is_free"><small>{{plan.currency}}</small></label><button (click)="save(plan)">Save</button></div>}</div></section>
<section class="grid"><article class="card"><h3>Grant subscription</h3><label>Discord server ID<input type="number" [(ngModel)]="grant.guild_id"></label><label>Plugin<select [(ngModel)]="grant.plugin_key">@for(plan of plans();track plan.plugin_key){@if(!plan.is_free){<option [value]="plan.plugin_key">{{plan.name||plan.plugin_key}}</option>}}</select></label><label>Period<select [(ngModel)]="grant.billing_period"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option><option value="manual">Manual</option></select></label><label>Access days<input type="number" min="1" max="3660" [(ngModel)]="grant.days"></label><button (click)="grantAccess()">Grant access</button></article>
<article class="card"><div class="title"><div><h3>Subscriptions</h3><p>Active and historical access grants.</p></div><button class="secondary" (click)="load()">Refresh</button></div><div class="subscriptions">@for(x of subscriptions();track x.id){<div class="subscription"><div><b>{{x.plugin_key}}</b><small>Guild {{x.guild_id}} · {{x.billing_period}}</small></div><span [class.active]="x.status==='active'">{{x.status}}</span><time>{{x.expires_at|date:'mediumDate'}}</time>@if(x.status==='active'){<button class="danger" (click)="revoke(x)">Revoke</button>}</div>}@empty{<p>No subscriptions yet.</p>}</div></article></section>
</main></sn-shell>`,styles:[`.page{max-width:1200px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}header span{color:var(--primary);font-size:.68rem;font-weight:900;letter-spacing:.14em}h2,h3,p{margin:.25rem 0}p,small{color:var(--muted)}.card,.notice{padding:1.1rem;border:1px solid var(--line);border-radius:15px;background:var(--panel);display:grid;gap:1rem}.title{display:flex;justify-content:space-between;align-items:center}.plans{display:grid;overflow:auto}.plan{min-width:900px;display:grid;grid-template-columns:1.5fr .65fr repeat(3,1fr) 80px;gap:.6rem;align-items:center;padding:.65rem;border-top:1px solid var(--line)}.plan.head{color:var(--muted);font-size:.7rem;text-transform:uppercase}.plan div,.subscriptions div{display:grid}.plan label:not(.free){display:grid;grid-template-columns:1fr auto;align-items:center;gap:.3rem}.free{display:flex;align-items:center;gap:.4rem}.grid{display:grid;grid-template-columns:340px 1fr;gap:1rem}label{display:grid;gap:.3rem;color:var(--muted);font-size:.75rem}input,select{padding:.65rem;color:var(--text);background:var(--panel-2);border:1px solid var(--line);border-radius:8px}button{padding:.65rem .8rem;border:0;border-radius:8px;background:var(--primary);font-weight:800}.secondary,.danger{background:transparent;color:var(--text);border:1px solid var(--line)}.danger{color:#ff8d96}.subscription{display:grid;grid-template-columns:1fr 90px 130px 80px;gap:.6rem;align-items:center;padding:.7rem;border-top:1px solid var(--line)}.subscription>span{text-transform:uppercase;color:var(--muted)}.subscription>span.active{color:var(--success)}.error{color:#ff8d96}.success{color:var(--success)}@media(max-width:850px){.grid{grid-template-columns:1fr}.subscription{grid-template-columns:1fr auto}.subscription time{grid-column:1}}`]})
export class BillingComponent implements OnInit{plans=signal<BillingPlan[]>([]);subscriptions=signal<BillingSubscription[]>([]);error=signal('');success=signal('');grant={guild_id:0,plugin_key:'',billing_period:'monthly',days:30};constructor(private api:BillingService){}ngOnInit(){this.load()}async load(){try{const[p,s]=await Promise.all([this.api.plans(),this.api.subscriptions()]);this.plans.set(p);this.subscriptions.set(s);if(!this.grant.plugin_key)this.grant.plugin_key=p.find(x=>!x.is_free)?.plugin_key||''}catch(e:any){this.error.set(e?.error?.detail||'Unable to load billing.')}}async save(x:BillingPlan){try{await this.api.savePlan(x);this.success.set(`${x.plugin_key} pricing saved.`);await this.load()}catch(e:any){this.error.set(e?.error?.detail||'Unable to save plan.')}}async grantAccess(){try{await this.api.grant(this.grant);this.success.set('Subscription granted.');await this.load()}catch(e:any){this.error.set(e?.error?.detail||'Unable to grant subscription.')}}async revoke(x:BillingSubscription){try{await this.api.revoke(x.id);this.success.set('Subscription revoked.');await this.load()}catch(e:any){this.error.set(e?.error?.detail||'Unable to revoke subscription.')}}}
