import {DatePipe,DecimalPipe} from '@angular/common';
import {HttpClient} from '@angular/common/http';
import {Component,OnInit,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {firstValueFrom} from 'rxjs';
import {BillingService} from '../core/billing.service';
import {GuildService} from '../core/guild.service';
import {TranslationService} from '../core/translation.service';
import {TranslatePipe} from '../core/translate.pipe';
import {ShellComponent} from '../shared/shell.component';

declare global{interface Window{LiqPayCheckout?:any}}

@Component({standalone:true,imports:[ShellComponent,FormsModule,TranslatePipe,DatePipe,DecimalPipe],template:`
<sn-shell [title]="'custom_bot.title'|snT:'Custom Discord bot'"><main class="page">
 <header><span>{{'custom_bot.eyebrow'|snT:'CLIENT BOT'}}</span><h2>{{'custom_bot.title'|snT:'Custom Discord bot'}}</h2><p>{{'custom_bot.intro'|snT:'Run GuildConsole under your own Discord bot identity. This feature has a separate subscription.'}}</p></header>
 @if(error()){<div class="notice error">{{error()}}</div>} @if(success()){<div class="notice success">{{success()}}</div>}
 <section class="panel"><label>{{'custom_bot.server'|snT:'Discord server'}}<select [(ngModel)]="guildId" (change)="load()">@for(g of guilds;track g.guild_id){<option [value]="g.guild_id">{{g.name}}</option>}</select></label></section>
 @if(billing()){<section class="panel"><div class="head"><div><h3>{{'custom_bot.subscription'|snT:'Custom bot subscription'}}</h3><p>{{'custom_bot.subscription_help'|snT:'The subscription is independent from the server subscription.'}}</p></div>@if(active()){<b>{{'custom_bot.active_until'|snT:'Active until'}} {{subscription()?.expires_at|date:'mediumDate'}}</b>}</div>
  @if(providers().length){<label>{{'billing.payment_gateway'|snT:'Payment gateway'}}<select [(ngModel)]="provider">@for(p of providers();track p){<option [value]="p">{{p==='monobank'?'monobank · UAH':'LiqPay · USD'}}</option>}</select></label>}
  @for(plan of plans();track plan.plugin_key){<div class="periods">@for(p of periods;track p.key){@if(price(plan,p.key)!==null){<article><span>{{('billing.'+p.key)|snT:p.label}}</span><strong>{{displayAmount(price(plan,p.key))|number:'1.2-2'}} {{currency()}}</strong><button [disabled]="busy()||!providers().length" (click)="purchase(p.key)">{{'billing.pay_subscription'|snT:'Pay for subscription'}}</button></article>}}</div>}
 </section>}
 <section class="panel settings" [class.locked]="!active()"><div class="head"><div><h3>{{'custom_bot.settings'|snT:'Bot connection'}}</h3><p>{{'custom_bot.settings_help'|snT:'Create a bot in Discord Developer Portal and paste its bot token. The token is encrypted and is never shown again.'}}</p></div>@if(status()?.configured){<b>{{status()?.username}}</b>}</div>
  @if(!active()){<div class="notice">{{'custom_bot.activate_first'|snT:'Activate the custom bot subscription to configure this feature.'}}</div>}
  <label>{{'custom_bot.token'|snT:'Discord bot token'}}<input type="password" [(ngModel)]="token" [disabled]="!active()" autocomplete="new-password" placeholder="••••••••••••••••"></label>
  <div class="actions"><button [disabled]="!active()||busy()||token.trim().length<20" (click)="save()">{{'custom_bot.validate_save'|snT:'Validate and save token'}}</button>@if(status()?.invite_url){<a class="button" [href]="status().invite_url" target="_blank" rel="noopener">{{'custom_bot.add_to_server'|snT:'Add bot to server'}}</a>}@if(status()?.configured){<button class="danger" [disabled]="busy()" (click)="remove()">{{'custom_bot.remove_token'|snT:'Remove token'}}</button>}</div>
  <div class="help"><h3>{{'custom_bot.discord_setup'|snT:'Discord setup'}}</h3><ol><li>{{'custom_bot.step1'|snT:'Create an application and bot in Discord Developer Portal.'}}</li><li>{{'custom_bot.step2'|snT:'Enable Server Members Intent and Message Content Intent.'}}</li><li>{{'custom_bot.step3'|snT:'Save the token here, then use Add bot to server.'}}</li></ol></div>
 </section>
 <section class="panel settings"><div><h3>{{'custom_bot.expiry_title'|snT:'Subscription expiry notification'}}</h3><p>{{'custom_bot.expiry_help'|snT:'Send one advance notification before the custom bot subscription expires.'}}</p></div>
  @if(active()){<label class="check"><input type="checkbox" [(ngModel)]="expiryEnabled"> {{'billing.enable_expiry'|snT:'Enable subscription expiry reminder'}}</label><label>{{'billing.days_before'|snT:'Notify before, days'}}<input type="number" min="1" max="30" [(ngModel)]="expiryDays"></label><fieldset [disabled]="!expiryEnabled"><legend>{{'billing.send_notification_to'|snT:'Send notification to'}}</legend><label class="check"><input type="checkbox" [(ngModel)]="expiryDiscordDm"> {{'billing.discord_dm'|snT:'Discord DM'}}</label><label class="check" [class.disabled]="!billing()?.email_available||!billing()?.smtp_available"><input type="checkbox" [(ngModel)]="expiryEmail" [disabled]="!billing()?.email_available||!billing()?.smtp_available"> {{'billing.email'|snT:'Email'}}</label></fieldset><button [disabled]="busy()" (click)="saveReminder()">{{'billing.save_alerts'|snT:'Save notification settings'}}</button>}@else{<div class="notice">{{'custom_bot.activate_reminder'|snT:'Activate the custom bot subscription before configuring its reminder.'}}</div>}
 </section>
</main></sn-shell>`,styles:[`
.page{max-width:1100px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}.page header span{color:var(--primary);font-weight:800;letter-spacing:.12em}h2,h3,p{margin:.3rem 0}p{color:var(--muted)}.panel,.notice{border:1px solid var(--line);background:var(--panel);border-radius:15px;padding:1rem}.notice.error{color:#ff8d96}.notice.success,.head b{color:var(--success)}label{display:grid;gap:.45rem}input,select,button,.button{padding:.75rem;border-radius:9px;border:1px solid var(--line);background:var(--panel-2);color:var(--text)}button,.button{background:var(--primary);color:#07110f;font-weight:800;cursor:pointer;text-decoration:none;text-align:center}.head,.actions{display:flex;justify-content:space-between;align-items:center;gap:.7rem;flex-wrap:wrap}.periods{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem;margin-top:1rem}.periods article{display:grid;gap:.55rem;padding:.9rem;background:var(--panel-2);border-radius:10px}.periods strong{color:var(--primary);font-size:1.2rem}.settings{display:grid;gap:1rem}.settings.locked{opacity:.8}.danger{background:#5a2430;color:#fff}.help{border-top:1px solid var(--line);padding-top:.7rem}.help li{margin:.5rem 0;color:var(--muted)}.check{display:flex;align-items:center;gap:.6rem}.check input{width:18px;height:18px;padding:0}fieldset{display:grid;gap:.7rem;border:1px solid var(--line);border-radius:10px;padding:1rem}.disabled{opacity:.55}button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:760px){.periods{grid-template-columns:1fr}.actions>*{width:100%}}
`]})
export class CustomBotComponent implements OnInit{
 guilds:any[]=[];guildId='';token='';provider='monobank';expiryEnabled=false;expiryDays=3;expiryDiscordDm=true;expiryEmail=false;billing=signal<any>(null);status=signal<any>(null);busy=signal(false);error=signal('');success=signal('');periods=[{key:'monthly',label:'Monthly'},{key:'quarterly',label:'Quarterly'},{key:'yearly',label:'Yearly'}];
 constructor(private guildApi:GuildService,private bill:BillingService,private http:HttpClient,private route:ActivatedRoute,private i18n:TranslationService){}
 async ngOnInit(){this.guilds=(await this.guildApi.list()).filter(x=>x.is_owner);const q=this.route.snapshot.queryParamMap.get('guild_id');this.guildId=this.guilds.some(x=>String(x.guild_id)===q)?String(q):String(this.guilds[0]?.guild_id||'');if(this.guildId){await this.load();const order=this.route.snapshot.queryParamMap.get('payment');if(order)await this.refreshPayment(order)}else this.error.set(this.i18n.t('billing.no_owned_servers','No Discord servers owned by this account.'))}
 async load(){this.error.set('');try{const [billing,status]=await Promise.all([this.bill.guildBilling(this.guildId),firstValueFrom(this.http.get<any>(`/api/v1/discord/guilds/${this.guildId}/custom-bot`))]);this.billing.set(billing);this.status.set(status);if(!billing.providers?.[this.provider]?.active)this.provider=this.providers()[0]||'monobank';const s=this.subscription();this.expiryEnabled=!!s?.expiry_notice_enabled;this.expiryDays=Number(s?.expiry_notice_days||3);this.expiryDiscordDm=s?.expiry_notice_discord_dm!==false;this.expiryEmail=!!s?.expiry_notice_email}catch(e:any){this.error.set(this.err(e,'Unable to load custom bot settings.'))}}
 plans(){return(this.billing()?.plans||[]).filter((x:any)=>x.plugin_key==='__custom_bot__'&&!x.is_free)} subscription(){return(this.billing()?.subscriptions||[]).find((x:any)=>x.plugin_key==='__custom_bot__'&&x.status==='active')||null} active(){const s=this.subscription();return !!s&&new Date(s.expires_at)>new Date()} providers(){return(['monobank','liqpay'] as const).filter(p=>this.billing()?.providers?.[p]?.active)} price(p:any,k:string){return p['discounted_'+k+'_price']} currency(){return this.provider==='monobank'&&this.billing()?.uah_quote&&this.i18n.locale()==='uk'?'UAH':'USD'} displayAmount(x:any){const n=Number(x||0);return this.currency()==='UAH'?Math.round(n*Number(this.billing().uah_quote.rate)*100)/100:n}
 private loadScript(){return new Promise<void>((resolve,reject)=>{if(document.getElementById('liqpay-widget')){resolve();return}const s=document.createElement('script');s.id='liqpay-widget';s.src='https://static.liqpay.ua/libjs/checkout.js';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Payment widget failed to load.'));document.head.appendChild(s)})}
 async purchase(period:string){this.busy.set(true);this.error.set('');try{const r=await this.bill.checkout(this.guildId,{plugin_key:'__custom_bot__',billing_period:period,provider:this.provider,locale:this.i18n.locale()});if(r.provider==='monobank'){window.location.assign(r.checkout_url);return}await this.loadScript();if(!window.LiqPayCheckout)throw new Error('Payment gateway unavailable.');let host=document.getElementById('custom_bot_liqpay');if(!host){host=document.createElement('div');host.id='custom_bot_liqpay';document.querySelector('.page')?.appendChild(host)}window.LiqPayCheckout.init({data:r.fields.data,signature:r.fields.signature,embedTo:'#custom_bot_liqpay',language:this.i18n.locale(),mode:'embed'}).on('liqpay.callback',()=>void this.load())}catch(e:any){this.error.set(this.err(e,'Unable to start payment.'))}finally{this.busy.set(false)}}
 async refreshPayment(order:string){for(let i=0;i<6;i++){try{const r=await this.bill.refreshPayment(order);if(r.status==='paid'){this.success.set(this.i18n.t('custom_bot.payment_confirmed','Payment confirmed. Custom bot subscription is active.'));await this.load();return}if(r.status==='failed')break}catch{}await new Promise(x=>setTimeout(x,2000))}this.error.set(this.i18n.t('billing.payment_pending','Payment is still being confirmed.'))}
 async save(){this.busy.set(true);this.error.set('');try{this.status.set(await firstValueFrom(this.http.put<any>(`/api/v1/discord/guilds/${this.guildId}/custom-bot`,{token:this.token.trim()})));this.token='';this.success.set(this.i18n.t('custom_bot.saved','Bot token validated and saved securely.'))}catch(e:any){this.error.set(this.err(e,'Unable to save the bot token.'))}finally{this.busy.set(false)}}
 async remove(){this.busy.set(true);this.error.set('');try{this.status.set(await firstValueFrom(this.http.delete<any>(`/api/v1/discord/guilds/${this.guildId}/custom-bot`)));this.success.set(this.i18n.t('custom_bot.removed','Bot token removed.'))}catch(e:any){this.error.set(this.err(e,'Unable to remove the bot token.'))}finally{this.busy.set(false)}}
 async saveReminder(){this.busy.set(true);this.error.set('');try{await this.bill.saveSubscriptionReminder(this.guildId,{enabled:this.expiryEnabled,days_before:this.expiryDays,discord_dm:this.expiryDiscordDm,email:this.expiryEmail},'__custom_bot__');this.success.set(this.i18n.t('billing.alerts_saved','Notification settings saved.'));await this.load()}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.alerts_save_error','Unable to save notification settings.')))}finally{this.busy.set(false)}}
 err(e:any,f:string){return e?.error?.detail||e?.message||f}
}
