import {CommonModule} from '@angular/common';
import {Component,HostListener,OnInit,signal} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {firstValueFrom} from 'rxjs';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {GuildPluginMarketplaceItem,GuildPluginService} from '../core/guild-plugin.service';
import {ShellComponent} from '../shared/shell.component';
import {TranslatePipe} from '../core/translate.pipe';
import {TranslationService} from '../core/translation.service';

type Guide={purpose:string;features:string[];setup:string[]};
type GuideSection={title:string;body?:string;items?:string[]};
type LocalGuide={purpose:string;configuration:string;check:string;sections?:GuideSection[]};
type DocsFile={common:{requirements:string[];steps:string[];troubleshooting:string[];configuration_title:string;check_title:string;troubleshooting_title:string;full_documentation?:string;close?:string};plugins:Record<string,LocalGuide>};

@Component({standalone:true,imports:[CommonModule,RouterLink,ShellComponent,TranslatePipe],template:`
<sn-shell [title]="'documentation.title' | snT:'Documentation'"><main class="page">
  <header><span>GUILDCONSOLE KNOWLEDGE BASE</span><h2>{{selected() ? localizedName(selected()!) : ('documentation.heading' | snT:'Internal documentation')}}</h2><p>{{selected() ? localized(selected()!).purpose : ('documentation.description' | snT:'Guides for installing, configuring and operating GuildConsole plugins.') }}</p></header>
  @if(error()){<div class="notice error">{{error()}}</div>}
  @if(selected();as plugin){
    <nav class="crumbs"><a [routerLink]="['/guild',guildId,'plugin-runtime']">{{'documentation.store'|snT:'Plugin store'}}</a><span>›</span><a [routerLink]="['/guild',guildId,'documentation']">{{'documentation.all_plugins'|snT:'All documentation'}}</a><span>›</span><b>{{localizedName(plugin)}}</b></nav>
    <section class="hero card"><div class="icon">{{plugin.plugin_key.slice(0,1).toUpperCase()}}</div><div><h3>{{localizedName(plugin)}}</h3></div><div class="tags"><span>v{{plugin.version||'—'}}</span><span>{{plugin.category}}</span><span>{{plugin.installed?('plugins.installed'|snT:'Installed'):('runtime_usage.not_installed'|snT:'Not installed')}}</span></div></section>
    <section class="columns"><article class="card"><h3>{{'documentation.purpose'|snT:'Purpose'}}</h3><p>{{localized(plugin).purpose}}</p><h3>{{docs()?.common?.configuration_title||('documentation.features'|snT:'Configuration')}}</h3><p>{{localized(plugin).configuration}}</p><h3>{{docs()?.common?.check_title||'Verification'}}</h3><p>{{localized(plugin).check}}</p></article><article class="card"><h3>{{'documentation.quick_start'|snT:'Step-by-step setup'}}</h3><h4>{{'documentation.requirements'|snT:'Before you start'}}</h4><ul>@for(item of docs()?.common?.requirements||guide(plugin).features;track item){<li>{{replacePlugin(item,localizedName(plugin))}}</li>}</ul><ol>@for(item of docs()?.common?.steps||guide(plugin).setup;track item){<li>{{replacePlugin(item,localizedName(plugin))}}</li>}</ol><a class="primary" [routerLink]="['/guild',guildId,'plugin-runtime']">{{'documentation.open_store'|snT:'Open plugin store'}}</a></article></section>
    @if(localized(plugin).sections?.length){<button class="primary full-docs" (click)="detailsOpen.set(true)">{{docs()?.common?.full_documentation||('documentation.read_more'|snT:'Full documentation')}}</button>}
    <section class="card"><h3>{{docs()?.common?.troubleshooting_title||'Troubleshooting'}}</h3><ul>@for(item of docs()?.common?.troubleshooting||[];track item){<li>{{replacePlugin(item,localizedName(plugin))}}</li>}</ul></section>
    <section class="card"><h3>{{'documentation.lifecycle'|snT:'Plugin lifecycle'}}</h3><div class="steps"><div><b>1</b><span>{{'documentation.install_step'|snT:'Install creates a separate configuration for this Discord server.'}}</span></div><div><b>2</b><span>{{'documentation.enable_step'|snT:'Enable validates access and starts the plugin runtime.'}}</span></div><div><b>3</b><span>{{'documentation.disable_step'|snT:'Disable stops processing while preserving settings.'}}</span></div><div><b>4</b><span>{{'documentation.remove_step'|snT:'Uninstall permanently removes the server installation and its settings.'}}</span></div></div></section>
    @if(detailsOpen()){
      <div class="modal-backdrop" role="presentation" (click)="detailsOpen.set(false)"><section class="modal card" role="dialog" aria-modal="true" (click)="$event.stopPropagation()"><header class="modal-head"><div><span>GUILDCONSOLE KNOWLEDGE BASE</span><h2>{{localizedName(plugin)}}</h2></div><button class="close" (click)="detailsOpen.set(false)">×</button></header><div class="modal-summary"><h3>{{'documentation.purpose'|snT:'Purpose'}}</h3><p>{{localized(plugin).purpose}}</p><h3>{{docs()?.common?.configuration_title||('documentation.features'|snT:'Configuration')}}</h3><p>{{localized(plugin).configuration}}</p><h3>{{docs()?.common?.check_title||'Verification'}}</h3><p>{{localized(plugin).check}}</p></div>@for(section of localized(plugin).sections||[];track section.title){<article class="detail-section"><h3>{{section.title}}</h3>@if(section.body){<p>{{section.body}}</p>}@if(section.items?.length){<ul>@for(item of section.items;track item){<li>{{item}}</li>}</ul>}</article>}<button class="primary modal-close" (click)="detailsOpen.set(false)">{{docs()?.common?.close||('ui.close'|snT:'Close')}}</button></section></div>
    }
  } @else if(guildId){
    <section class="docs-grid">@for(plugin of plugins();track plugin.plugin_key){<a class="doc-card" [routerLink]="['/guild',guildId,'plugins',plugin.plugin_key,'documentation']"><div class="icon">{{plugin.plugin_key.slice(0,1).toUpperCase()}}</div><div><h3>{{localizedName(plugin)}}</h3><p>{{localized(plugin).purpose||('plugins.no_description'|snT:'No description supplied.')}}</p><small>{{'documentation.read_more'|snT:'Read documentation'}} →</small></div></a>}@empty{<div class="notice">{{'documentation.empty'|snT:'Plugin documentation is not available.'}}</div>}</section>
  } @else {
    <section class="card"><h3>{{'documentation.getting_started'|snT:'Getting started'}}</h3><ol><li>{{'documentation.choose_server'|snT:'Choose a Discord server from the Servers page.'}}</li><li>{{'documentation.open_plugins'|snT:'Open Plugin store in the server administration menu.'}}</li><li>{{'documentation.install_enable'|snT:'Install the required plugin, configure it, then enable it.'}}</li></ol><a class="primary" routerLink="/servers">{{'shell.servers'|snT:'Servers'}}</a></section>
  }
</main></sn-shell>`,styles:[`.page{max-width:1120px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}header span{color:var(--primary);font-size:.7rem;font-weight:900;letter-spacing:.12em}h2,h3,p{margin:.3rem 0}header p,.card p{color:var(--muted)}.card,.notice,.doc-card{padding:1.15rem;border:1px solid var(--line);border-radius:15px;background:var(--panel)}.crumbs{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;color:var(--muted)}.crumbs a{color:var(--primary);text-decoration:none}.hero{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:1rem}.icon{width:48px;height:48px;border-radius:13px;display:grid;place-items:center;background:rgba(53,226,178,.13);color:var(--primary);font-weight:900}.tags{display:flex;gap:.4rem;flex-wrap:wrap}.tags span{padding:.3rem .5rem;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:.72rem}.columns{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{display:grid;gap:.75rem}.card ul,.card ol{margin:.2rem 0;display:grid;gap:.65rem;color:var(--muted)}.primary{justify-self:start;padding:.7rem 1rem;border:0;border-radius:9px;background:var(--primary);color:#07110f;text-decoration:none;font-weight:800;cursor:pointer}.full-docs{margin:.15rem 0}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:.7rem}.steps div{display:grid;gap:.5rem;padding:.85rem;background:var(--panel-2);border-radius:10px}.steps b{color:var(--primary);font-size:1.2rem}.docs-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.doc-card{display:grid;grid-template-columns:auto 1fr;gap:.8rem;color:var(--text);text-decoration:none}.doc-card p{color:var(--muted);min-height:3.3rem}.doc-card small{color:var(--primary)}.error{color:#ff8d96}.modal-backdrop{position:fixed;inset:0;z-index:1200;padding:1rem;display:grid;place-items:center;background:rgba(2,7,12,.82);backdrop-filter:blur(5px)}.modal{width:min(920px,100%);max-height:92vh;overflow:auto;padding:1.4rem}.modal-head{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;padding-bottom:1rem;border-bottom:1px solid var(--line)}.modal-head h2{margin-top:.35rem}.close{width:42px;height:42px;border:1px solid var(--line);border-radius:10px;background:var(--panel-2);color:var(--text);font-size:1.5rem;cursor:pointer}.modal-summary,.detail-section{display:grid;gap:.55rem;padding:1rem 0;border-bottom:1px solid var(--line)}.modal-summary p,.detail-section p,.detail-section li{color:var(--muted);line-height:1.65}.detail-section ul{display:grid;gap:.45rem;margin:.15rem 0;padding-left:1.25rem}.modal-close{margin-top:.5rem}@media(max-width:850px){.docs-grid,.steps{grid-template-columns:repeat(2,1fr)}.columns{grid-template-columns:1fr}}@media(max-width:560px){.docs-grid,.steps{grid-template-columns:1fr}.hero{grid-template-columns:auto 1fr}.tags{grid-column:1/-1}.modal-backdrop{padding:.5rem}.modal{padding:1rem;max-height:96vh}}`]})
export class DocumentationComponent implements OnInit{
  guildId='';pluginKey='';plugins=signal<GuildPluginMarketplaceItem[]>([]);selected=signal<GuildPluginMarketplaceItem|null>(null);docs=signal<DocsFile|null>(null);error=signal('');detailsOpen=signal(false);
  constructor(private route:ActivatedRoute,private api:GuildPluginService,private http:HttpClient,private i18n:TranslationService){}
  async ngOnInit(){this.guildId=this.route.snapshot.paramMap.get('guildId')||'';this.pluginKey=this.route.snapshot.paramMap.get('pluginKey')||'';await this.loadDocs(this.i18n.locale());if(!this.guildId)return;try{const items=await this.api.marketplace(this.guildId);this.plugins.set(items);if(this.pluginKey)this.selected.set(items.find(x=>x.plugin_key===this.pluginKey)||null);if(this.pluginKey&&!this.selected())this.error.set(this.i18n.t('documentation.not_found','Plugin documentation was not found.'))}catch(e:any){this.error.set(e?.error?.detail||this.i18n.t('documentation.load_error','Unable to load plugin documentation.'))}}
  @HostListener('window:guildconsole-locale-changed',['$event']) async localeChanged(event:CustomEvent<string>){await this.loadDocs(event.detail||this.i18n.locale())}
  private async loadDocs(locale:string){const supported=new Set(['en','uk','ru','de','ar','fr','it','pl']);const code=supported.has(locale)?locale:'en';try{this.docs.set(await firstValueFrom(this.http.get<DocsFile>(`/plugin-docs/${code}.json?v=6`)))}catch{if(code!=='en'){try{this.docs.set(await firstValueFrom(this.http.get<DocsFile>('/plugin-docs/en.json?v=6')))}catch{}}}}
  localized(plugin:GuildPluginMarketplaceItem):LocalGuide{return this.docs()?.plugins?.[plugin.plugin_key]||{purpose:this.guide(plugin).purpose,configuration:this.guide(plugin).features.join(' · '),check:this.guide(plugin).setup.at(-1)||''}}
  localizedName(plugin:GuildPluginMarketplaceItem):string{const key=plugin.plugin_key==='verification_level1'?'verification':plugin.plugin_key;return this.i18n.t(`plugin_names.${key}`,plugin.name)}
  replacePlugin(value:string,name:string){return value.replaceAll('{plugin}',name)}
  guide(plugin:GuildPluginMarketplaceItem):Guide{const known:Record<string,Guide>={
    welcome:{purpose:'Welcomes new members and guides them through the first steps on the server.',features:['Configurable welcome messages','Channel and role based delivery','Delayed and conditional messages'],setup:['Install the plugin.','Open its settings from the server menu.','Select the channel, compose the messages and save.','Enable the plugin.']},
    antiflood:{purpose:'Protects channels from message floods and repeated unwanted activity.',features:['Rate limits per rule','Channel and role exceptions','Automatic moderation actions'],setup:['Install the plugin.','Create flood protection rules.','Review bot moderation permissions.','Enable the plugin.']},
    translator_groups:{purpose:'Synchronizes messages between language channels and translates them through AI Center.',features:['Multiple translation groups','Text, files and image forwarding','Language configured per channel'],setup:['Install the plugin.','Create a translation group.','Add at least two channels with different languages.','Configure AI Center and enable the plugin.']},
    first_introduction:{purpose:'Lets members choose language roles with flag reactions in configured channels or threads.',features:['Multiple independent language groups','Automatic role creation by mask','Default language role'],setup:['Install the plugin.','Create a language group and select its channel.','Choose languages and create or map roles.','Publish the reaction post and enable the plugin.']},
    verification_level1:{purpose:'Verifies members through configurable identity forms and AI assisted image checks.',features:['Several verification levels','Custom commands and nickname templates','AI markers and multiple accepted values'],setup:['Install the plugin.','Configure the first verification level and review channel.','Add optional image verification levels.','Assign result roles and enable the plugin.']},
    voting:{purpose:'Creates Discord votes using reusable visual templates.',features:['Template library','Preview with demo data','Result rendering'],setup:['Install the plugin.','Select a voting template.','Configure the target channel and vote options.','Enable and publish the vote.']},
    'guild-dm-broadcast':{purpose:'Sends controlled direct-message campaigns to selected members of the server.',features:['Audience filters and delivery limits','Campaign preview and delivery status','Safe queued sending'],setup:['Install the plugin.','Create a campaign and choose its audience.','Write and preview the message.','Enable the plugin and start delivery.']},
    role_menu:{purpose:'Lets members assign approved roles to themselves using buttons or select menus.',features:['Several role panels','Button and select-menu layouts','Mutually exclusive role groups'],setup:['Install the plugin.','Create a role panel and select a Discord channel.','Add the permitted roles and labels.','Publish the panel and enable the plugin.']},
    ai_automod:{purpose:'Analyses messages through AI Center and applies configured moderation actions.',features:['Configurable risk categories','Warnings, deletion and timeouts','Channel and role exclusions'],setup:['Configure an AI provider in AI Center.','Install the plugin and select monitored channels.','Choose categories, thresholds and actions.','Test with a harmless sample before enabling.']},
    event_manager:{purpose:'Schedules server events, records attendance and sends reminders.',features:['Event schedules and time zones','RSVP collection','Automatic reminders'],setup:['Install the plugin.','Select the announcement channel and time zone.','Create an event with reminder times.','Enable the plugin and publish the event.']},
    war_planner:{purpose:'Coordinates alliance wars, waves, targets and participant assignments.',features:['War and wave planning','Target assignments','Participant status tracking'],setup:['Install the plugin.','Create a war and define its dates.','Add waves, targets and participants.','Enable the plugin and publish the plan.']},
    activity_ranking:{purpose:'Awards XP for useful text and voice activity, calculates levels and grants reward roles.',features:['Message and voice XP','Configurable level curve','Automatic reward roles','Discord leaderboard command'],setup:['Install the plugin.','Set message and voice XP values, cooldown and level curve.','Add each reward level and its Discord role. Keep the bot role above every reward role.','Configure exclusions, save the settings and enable the plugin.','Generate test activity and verify the level, reward role and /leaderboard output.']},
    audit_security:{purpose:'Records security-sensitive Discord events and sends filtered audit alerts.',features:['Message, member, role and channel events','Alert channel and mention role','Configurable retention'],setup:['Install the plugin.','Select the audit channel and event types.','Set retention and optional mention role.','Enable the plugin and perform a harmless test change.']},
    backup_restore:{purpose:'Creates versioned snapshots of server configuration and restores selected settings.',features:['Roles, channels and plugin settings snapshots','Version history','Controlled restore workflow'],setup:['Install the plugin.','Create the first snapshot.','Review the recorded sections and retention policy.','Use restore only after reviewing the generated change plan.']},
    cross_guild_network:{purpose:'Links trusted Discord servers and synchronizes network announcements.',features:['Trusted server network','Synchronized announcement channels','Membership and delivery controls'],setup:['Install the plugin on every participating server.','Create a network and add trusted servers.','Map one announcement channel per server.','Enable the plugin and send a test announcement.']},
    moderation:{purpose:'Manages reports, evidence, warnings, sanctions, appeals and moderator workload.',features:['Case lifecycle and evidence','Sanctions and appeals','Moderator assignment and deadlines'],setup:['Install the plugin.','Configure moderator roles and operational channels.','Define case categories and sanctions.','Enable the plugin and create a test case.']}
  };return known[plugin.plugin_key]||{purpose:plugin.summary||`Adds ${plugin.name} capabilities to this Discord server.`,features:['Independent settings for each Discord server','Controlled enable and disable lifecycle','Integrated GuildConsole access control'],setup:['Install the plugin from the store.','Open its settings page and complete required fields.','Enable the plugin.','Verify its operation in the selected Discord channel.']}}
}
