import {Component,OnInit,signal} from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {DatePipe,DecimalPipe} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {BillingService} from '../core/billing.service';
import {ShellComponent} from '../shared/shell.component';
import {TranslationService} from '../core/translation.service';

@Component({standalone:true,imports:[ShellComponent,DatePipe,DecimalPipe,FormsModule],template:`
<sn-shell title="Subscriptions"><main class="page"><header><span>BILLING</span><h2>Plugin subscriptions</h2><p>Prices are shown in {{currency}} using the official NBU rate. A checkout quote is fixed for 30 minutes.</p></header>
@if(error()){<div class="notice">{{error()}}</div>}@if(data()){<section class="summary"><div><small>Owner balance</small><strong>{{data().wallet.balance|number:'1.2-2'}} {{data().wallet.currency}}</strong></div><div><small>Display currency</small><strong>{{currency}}</strong></div><div><small>NBU rate</small><strong>1 {{currency}} = {{data().exchange_rate.uah_per_unit|number:'1.2-4'}} UAH</strong><small>{{data().exchange_rate.effective_at|date:'mediumDate'}}</small></div></section>
<section class="discount"><div><h3>Discount card</h3><p>Enter a card code once for this server. Loyalty and card discounts combine up to 50%.</p></div><input [(ngModel)]="discountCode" placeholder="CARD CODE" maxlength="64"><button (click)="redeem()">Apply</button>@if(data().plans[0]?.discount?.total_percent){<strong>Current discount: {{data().plans[0].discount.total_percent}}%</strong>}</section>
<section class="plans">@for(p of paidPlans();track p.plugin_key){<article class="card"><div class="head"><div><h3>{{name(p.plugin_key)}}</h3><small>{{p.plugin_key}}</small></div>@if(active(p.plugin_key)){<b class="active">ACTIVE</b>}</div><div class="periods">@for(period of periods;track period.key){@if(price(p,period.key)!==null){<div class="period"><span>{{periodLabel(period.key)}}</span><strong>{{price(p,period.key)|number:'1.2-2'}} {{currency}}</strong><div class="actions"><button [disabled]="busy()" (click)="pay(p.plugin_key,period.key,'wayforpay')">{{payLabel(p,period.key)}} · WayForPay</button><button [disabled]="busy()" (click)="pay(p.plugin_key,period.key,'liqpay')">{{payLabel(p,period.key)}} · LiqPay</button><button class="balance" [disabled]="busy()" (click)="pay(p.plugin_key,period.key,'balance')">{{t('pay_from_balance','Pay from balance')}} · {{price(p,period.key)|number:'1.2-2'}} {{currency}}</button></div></div>}}</div></article>}@empty{<article class="card"><p>No paid plugin plans are configured yet.</p></article>}</section>}
</main></sn-shell>`,styles:[`.page{max-width:1100px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}header span{color:var(--primary);font-size:.65rem;font-weight:900;letter-spacing:.14em}h2,h3,p{margin:.3rem 0}p,small{color:var(--muted)}.notice,.card,.summary,.discount{border:1px solid var(--line);background:var(--panel);border-radius:15px;padding:1rem}.notice{color:#ff9da8}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.summary div{display:grid;gap:.25rem}.summary strong{font-size:1.05rem}.discount{display:grid;grid-template-columns:1fr 220px auto auto;gap:.7rem;align-items:center}.discount input{padding:.7rem;background:var(--panel-2);color:var(--text);border:1px solid var(--line);border-radius:8px}.discount>strong{color:var(--success)}.plans{display:grid;gap:1rem}.head{display:flex;justify-content:space-between;align-items:center}.active{color:var(--success)}.periods{display:grid;grid-template-columns:repeat(3,1fr);gap:.75rem;margin-top:1rem}.period{display:grid;gap:.35rem;padding:.9rem;background:var(--panel-2);border:1px solid var(--line);border-radius:12px}.period>strong{font-size:1.3rem;color:var(--primary)}.actions{display:grid;gap:.45rem;margin-top:.5rem}button{padding:.65rem;border:0;border-radius:8px;background:var(--primary);font-weight:850}button.balance{background:transparent;color:var(--text);border:1px solid var(--line)}button:disabled{opacity:.5}@media(max-width:850px){.periods,.summary,.discount{grid-template-columns:1fr}}`]})
export class GuildBillingComponent implements OnInit{guildId='';currency=localStorage.getItem('guildconsole_currency')||'UAH';discountCode='';data=signal<any>(null);error=signal('');busy=signal(false);periods=[{key:'monthly'},{key:'quarterly'},{key:'yearly'}];constructor(private route:ActivatedRoute,private api:BillingService,private i18n:TranslationService){}ngOnInit(){this.guildId=this.route.snapshot.paramMap.get('guildId')||'';this.load()}async load(){try{this.data.set(await this.api.guildBilling(this.guildId))}catch(e:any){this.error.set(e?.error?.detail||this.t('subscriptions_load_error','Unable to load subscriptions.'))}}async redeem(){try{await this.api.redeemDiscount(this.guildId,this.discountCode);this.discountCode='';await this.load()}catch(e:any){this.error.set(e?.error?.detail||this.t('discount_apply_error','Unable to apply discount card.'))}}paidPlans(){return(this.data()?.plans||[]).filter((x:any)=>!x.is_free)}price(p:any,k:string){return p[`display_${k}_price`]}periodLabel(k:string){return this.t(k,k)}payLabel(p:any,k:string){return `${this.t('pay','Pay')} ${Number(this.price(p,k)).toFixed(2)} ${this.currency}`}active(k:string){return(this.data()?.subscriptions||[]).some((x:any)=>x.plugin_key===k&&x.status==='active'&&new Date(x.expires_at)>new Date())}name(k:string){return k==='__paid_modules__'?this.t('paid_modules','Paid Modules'):k.split('_').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' ')}async pay(plugin_key:string,billing_period:string,provider:string){this.busy.set(true);this.error.set('');try{const r=await this.api.checkout(this.guildId,{plugin_key,billing_period,provider,display_currency:this.currency});if(provider==='balance'){await this.load();return}const form=document.createElement('form');form.method='POST';form.action=r.action;for(const[key,value]of Object.entries(r.fields||{})){const values=Array.isArray(value)?value:[value];for(const item of values){const input=document.createElement('input');input.type='hidden';input.name=Array.isArray(value)?`${key}[]`:key;input.value=String(item);form.appendChild(input)}}document.body.appendChild(form);form.submit()}catch(e:any){this.error.set(e?.error?.detail||this.t('checkout_error','Unable to create checkout.'))}finally{this.busy.set(false)}}t(key:string,fallback:string){return this.i18n.t(`billing.${key}`,fallback)}}
