import {DatePipe,DecimalPipe} from '@angular/common';
import {Component,OnInit,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {BillingService} from '../core/billing.service';
import {GuildService} from '../core/guild.service';
import {TranslationService} from '../core/translation.service';
import {TranslatePipe} from '../core/translate.pipe';
import {ShellComponent} from '../shared/shell.component';

declare global{interface Window{LiqPayCheckout?:any}}

@Component({standalone:true,imports:[ShellComponent,DatePipe,DecimalPipe,FormsModule,TranslatePipe],template:`
<sn-shell [title]="'billing.title'|snT:'Billing'"><main class="page">
<header><span>{{'billing.eyebrow'|snT:'BILLING'}}</span><h2>{{'billing.server_subscription_title'|snT:'Server subscription'}}</h2><p>{{'billing.direct_payment_help'|snT:'Pay directly for a selected access period. The subscription does not renew automatically.'}}</p></header>
@if(error()){<div class="notice error">{{error()}}</div>}
@if(success()){<div class="notice success">{{success()}}</div>}
@if(data()){
<nav class="tabs"><button [class.active]="tab()==='activation'" (click)="tab.set('activation')">1. {{'billing.user_tab_activation'|snT:'Server activation'}}</button><button [class.active]="tab()==='alerts'" (click)="tab.set('alerts')">2. {{'billing.expiry_title'|snT:'Server subscription expiry'}}</button></nav>
@if(tab()==='activation'){
 <section class="panel"><label>{{'billing.discord_server'|snT:'Discord server'}}<select [(ngModel)]="selectedGuildId" (change)="changeGuild()">@for(g of guilds;track g.guild_id){<option [value]="g.guild_id">{{g.name}}</option>}</select></label>
 @if(currentSubscription();as subscription){<p>{{'billing.active_until'|snT:'Access until'}} {{subscription.expires_at|date:'mediumDate'}}</p>}</section>
 @if(availableProviders().length){<section class="panel"><label>{{'billing.payment_gateway'|snT:'Payment gateway'}}<select [(ngModel)]="selectedProvider">@for(provider of availableProviders();track provider){<option [value]="provider">{{provider==='monobank'?'monobank':'LiqPay'}}{{provider==='monobank'?' · UAH':' · USD'}}</option>}</select></label>@if(selectedProvider==='monobank'&&data()?.uah_quote){<small>{{'billing.monobank_uah_notice'|snT:'The final amount is calculated and sent to Monobank in Ukrainian hryvnias.'}} 1 USD = {{data().uah_quote.rate|number:'1.2-4'}} UAH</small>}</section>}
 <section class="plans">@for(p of paidPlans();track p.plugin_key){<article class="panel"><div class="head"><h3>{{name(p.plugin_key)}}</h3>@if(active(p.plugin_key)){<b>{{'billing.active'|snT:'ACTIVE'}}</b>}</div><div class="periods">@for(period of periods;track period.key){@if(price(p,period.key)!==null){<div class="period"><span>{{periodLabel(period.key)}}</span>@if(period.key!=='monthly'&&periodDiscount(p,period.key)>0){<small>{{'billing.save_discount'|snT:'Save'}} {{periodDiscount(p,period.key)}}%</small>}<strong>{{displayAmount(price(p,period.key))|number:'1.2-2'}} {{displayCurrency()}}</strong><button [disabled]="busy()||!providerActive()" (click)="purchase(period.key)">{{'billing.pay_subscription'|snT:'Pay for subscription'}}</button></div>}}</div></article>}</section>
 <section class="panel custom-days"><div><h3>{{'billing.custom_days_title'|snT:'Choose your number of days'}}</h3><p>{{'billing.custom_days_help'|snT:'The price includes the period rate and any available loyalty discount.'}}</p></div><div class="custom-controls"><label>{{'billing.days_count'|snT:'Number of days'}}<input type="number" min="1" max="3660" step="1" [(ngModel)]="customDays" (ngModelChange)="quote.set(null)"></label><button [disabled]="busy()||!validDays()" (click)="calculate()">{{'billing.calculate_price'|snT:'Calculate'}}</button></div>
 @if(quote();as q){<div class="quote-breakdown"><div><span>{{'billing.base_price'|snT:'Price before discounts'}}</span><strong>{{displayAmount(q.original_amount)|number:'1.2-2'}} {{displayCurrency()}}</strong></div><div><span>{{'billing.period_discount'|snT:'Period discount'}}</span><strong>−{{displayAmount(q.period_discount_amount)|number:'1.2-2'}} {{displayCurrency()}}</strong></div><div><span>{{'billing.loyalty_discount'|snT:'Loyalty discount'}} ({{q.tenure_discount_percent}}%)</span><strong>−{{displayAmount(q.tenure_discount_amount)|number:'1.2-2'}} {{displayCurrency()}}</strong></div><div class="quote-total"><span>{{'billing.amount_due'|snT:'Amount due'}}</span><strong>{{displayAmount(q.total_amount)|number:'1.2-2'}} {{displayCurrency()}}</strong></div></div><button [disabled]="busy()||!providerActive()" (click)="purchaseCustom()">{{'billing.pay_subscription'|snT:'Pay for subscription'}}</button>}
 </section>
 <section class="panel custom-days"><div><h3>{{'billing.server_voucher_title'|snT:'Subscription voucher'}}</h3><p>{{'billing.server_voucher_help'|snT:'Apply a code directly to the selected server. Preview the access days before redeeming.'}}</p></div><div class="custom-controls"><label>{{'billing.voucher_code'|snT:'Voucher code'}}<input [(ngModel)]="voucherCode" (ngModelChange)="voucherPreview.set(null)" maxlength="64" autocomplete="off"></label><button [disabled]="busy()||voucherCode.trim().length<3" (click)="previewVoucher()">{{'billing.preview_voucher'|snT:'Check voucher'}}</button></div>@if(voucherPreview();as v){<p>{{'billing.voucher_grants'|snT:'This voucher grants'}} <strong>{{v.days}} {{'billing.days_unit'|snT:'days'}}</strong> {{'billing.to_selected_server'|snT:'to the selected server.'}}</p><button [disabled]="busy()" (click)="redeemVoucher()">{{'billing.redeem_server_voucher'|snT:'Activate with voucher'}}</button>}</section>
 @if(!availableProviders().length){<div class="notice error">{{'billing.no_gateway'|snT:'No payment gateway is currently active.'}}</div>}
 <div id="liqpay_checkout"></div>
}
@if(tab()==='alerts'){<section class="panel alert-card"><div><h3>{{'billing.expiry_title'|snT:'Server subscription expiry'}}</h3><p>{{'billing.expiry_help'|snT:'Warn before the selected server subscription expires.'}}</p></div>@if(currentSubscription()){<label class="check"><input type="checkbox" [(ngModel)]="expiryEnabled"> {{'billing.enable_expiry'|snT:'Enable subscription expiry reminder'}}</label><label>{{'billing.days_before'|snT:'Notify before, days'}}<input type="number" min="1" max="30" [(ngModel)]="expiryDays"></label><fieldset [disabled]="!expiryEnabled"><legend>{{'billing.send_notification_to'|snT:'Send notification to'}}</legend><label class="check"><input type="checkbox" [(ngModel)]="expiryDiscordDm"> {{'billing.discord_dm'|snT:'Discord DM'}}</label><label class="check" [class.disabled]="!data().email_available||!data().smtp_available"><input type="checkbox" [(ngModel)]="expiryEmail" [disabled]="!data().email_available||!data().smtp_available"> {{'billing.email'|snT:'Email'}}</label></fieldset>}@else{<div class="notice">{{'billing.no_subscription_reminder'|snT:'Activate the server subscription before configuring its reminder.'}}</div>}</section><div class="alert-actions"><div class="dm-test"><button type="button" class="secondary" [disabled]="dmChecking()" (click)="testDm()">{{dmChecking()?('billing.dm_checking'|snT:'Checking…'):('billing.check_dm'|snT:'Check DM')}}</button>@if(dmCheckResult()){<small [class.ok]="dmCheckOk()" [class.bad]="!dmCheckOk()">{{dmCheckResult()}}</small>}</div><button [disabled]="busy()||!currentSubscription()" (click)="saveAlerts()">{{'billing.save_alerts'|snT:'Save notification settings'}}</button></div>}
}
</main></sn-shell>`,styles:[`
.page{max-width:1100px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}.page header span,.head b{color:var(--primary)}h2,h3,p{margin:.3rem 0}small,p{color:var(--muted)}.panel,.notice{border:1px solid var(--line);background:var(--panel);border-radius:15px;padding:1rem}.panel,label{display:grid;gap:.5rem}.tabs{display:flex;gap:.45rem;padding:.4rem;border:1px solid var(--line);border-radius:13px;background:var(--panel)}.tabs button{flex:1;background:transparent;color:var(--muted)}.tabs button.active{background:var(--primary);color:#07110f}.plans{display:grid;gap:1rem}.periods{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem;margin-top:1rem}.period{display:grid;gap:.5rem;padding:.8rem;background:var(--panel-2);border-radius:10px}.period strong{color:var(--primary);font-size:1.2rem}.head,.alert-actions,.dm-test{display:flex;align-items:center;justify-content:space-between;gap:.75rem;flex-wrap:wrap}.alert-card{max-width:700px}.check{display:flex;align-items:center;gap:.65rem;min-height:24px}.check input{width:18px;height:18px;min-width:18px;margin:0}fieldset{display:grid;gap:.85rem;padding:1rem;border:1px solid var(--line);border-radius:10px}.disabled{opacity:.55}.ok{color:var(--success)}.bad,.notice.error{color:#ff8d96}.notice.success{color:var(--success)}.secondary{color:var(--text);background:var(--panel-2)}input:not([type=checkbox]),select,button{padding:.75rem;border-radius:9px;border:1px solid var(--line);background:var(--panel-2);color:var(--text)}button{background:var(--primary);color:#07110f;font-weight:800;cursor:pointer}button:disabled{opacity:.55;cursor:not-allowed}.custom-days{gap:1rem}.custom-controls{display:flex;align-items:end;gap:.7rem;flex-wrap:wrap}.custom-controls label{max-width:220px}.quote-breakdown{display:grid;gap:.6rem;max-width:520px}.quote-breakdown>div{display:flex;justify-content:space-between;gap:1rem}.quote-total{padding-top:.6rem;border-top:1px solid var(--line);font-size:1.12rem}.quote-total strong{color:var(--primary)}#liqpay_checkout:empty{display:none}@media(max-width:800px){.periods{grid-template-columns:1fr}.alert-actions button{width:100%}}
`]})
export class GuildBillingComponent implements OnInit{
 tab=signal<'activation'|'alerts'>('activation');guildId='';selectedGuildId='';selectedProvider='monobank';guilds:any[]=[];currency='USD';customDays:number|null=30;quote=signal<any>(null);voucherCode='';voucherPreview=signal<any>(null);expiryEnabled=false;expiryDays=3;expiryDiscordDm=true;expiryEmail=false;data=signal<any>(null);error=signal('');success=signal('');busy=signal(false);dmChecking=signal(false);dmCheckResult=signal('');dmCheckOk=signal(false);periods=[{key:'monthly'},{key:'quarterly'},{key:'yearly'}];
 constructor(private route:ActivatedRoute,private api:BillingService,private guildApi:GuildService,private i18n:TranslationService){}
 async ngOnInit(){this.guilds=(await this.guildApi.list()).filter(x=>x.is_owner);const returnedGuild=this.route.snapshot.queryParamMap.get('guild_id');this.guildId=this.route.snapshot.paramMap.get('guildId')||(this.guilds.some(x=>String(x.guild_id)===returnedGuild)?returnedGuild:'')||this.guilds[0]?.guild_id||'';this.selectedGuildId=this.guildId;if(this.guildId){await this.load();const order=this.route.snapshot.queryParamMap.get('payment');if(order)void this.refreshReturnedPayment(order)}else this.error.set(this.i18n.t('billing.no_owned_servers','No Discord servers owned by this account.'))}
 private async refreshReturnedPayment(order:string){for(let attempt=0;attempt<6;attempt++){try{const result=await this.api.refreshPayment(order);if(result.status==='paid'){this.success.set(this.i18n.t('billing.payment_confirmed','Payment confirmed. Server subscription is active.'));await this.load();return}if(result.status==='failed'){this.error.set(this.i18n.t('billing.payment_failed','Payment was not completed.'));return}}catch(e:any){if(e?.status!==503){this.error.set(this.err(e,this.i18n.t('billing.purchase_error','Unable to confirm payment.')));return}}await new Promise(resolve=>setTimeout(resolve,2000))}this.success.set(this.i18n.t('billing.payment_pending','Payment is being confirmed. Refresh this page shortly.'))}
 async load(){try{this.data.set(await this.api.guildBilling(this.guildId));if(!this.providerActive())this.selectedProvider=this.availableProviders()[0]||'monobank';const s=this.currentSubscription();this.expiryEnabled=!!s?.expiry_notice_enabled;this.expiryDays=Number(s?.expiry_notice_days||3);this.expiryDiscordDm=s?.expiry_notice_discord_dm!==false;this.expiryEmail=!!s?.expiry_notice_email}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.load_error','Unable to load billing.')))}}
 changeGuild(){if(this.selectedGuildId!==this.guildId){this.guildId=this.selectedGuildId;this.quote.set(null);this.voucherPreview.set(null);void this.load()}}
 currentSubscription(){return this.data()?.subscriptions?.find((x:any)=>x.plugin_key==='__paid_modules__')||null}
 async saveAlerts(){this.busy.set(true);this.error.set('');try{await this.api.saveSubscriptionReminder(this.guildId,{enabled:this.expiryEnabled,days_before:this.expiryDays,discord_dm:this.expiryDiscordDm,email:this.expiryEmail});this.success.set(this.i18n.t('billing.alerts_saved','Notification settings saved.'));await this.load()}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.alerts_save_error','Unable to save notification settings.')))}finally{this.busy.set(false)}}
 async testDm(){if(this.dmChecking())return;this.dmChecking.set(true);this.dmCheckResult.set('');this.dmCheckOk.set(false);try{const queued=await this.api.testDiscordDm(this.guildId);for(let attempt=0;attempt<12;attempt++){await new Promise(resolve=>setTimeout(resolve,1000));const result=await this.api.discordDmCheck(queued.id);if(result.status==='completed'){this.dmCheckOk.set(true);this.dmCheckResult.set(this.i18n.t('billing.dm_available','DM delivered successfully.'));return}if(result.status==='failed'){this.dmCheckResult.set(this.i18n.t('billing.dm_unavailable','DM could not be delivered. Allow direct messages from server members and try again.'));return}}this.dmCheckResult.set(this.i18n.t('billing.dm_pending','The check is still being processed. Try again shortly.'))}catch(e:any){this.dmCheckResult.set(this.err(e,this.i18n.t('billing.dm_check_error','Unable to check Discord DM.')))}finally{this.dmChecking.set(false)}}
 private loadScript(id:string,src:string){return new Promise<void>((resolve,reject)=>{if(document.getElementById(id)){resolve();return}const s=document.createElement('script');s.id=id;s.src=src;s.onload=()=>resolve();s.onerror=()=>reject(new Error(this.i18n.t('billing.widget_load_error','Payment widget failed to load')));document.head.appendChild(s)})}
 private async openWidget(r:any){await this.loadScript('liqpay-widget','https://static.liqpay.ua/libjs/checkout.js');if(!window.LiqPayCheckout)throw new Error(this.i18n.t('billing.liqpay_unavailable','Payment gateway unavailable'));window.LiqPayCheckout.init({data:r.fields.data,signature:r.fields.signature,embedTo:'#liqpay_checkout',language:this.i18n.locale(),mode:'embed'}).on('liqpay.callback',()=>void this.load()).on('liqpay.close',()=>void this.load())}
 private async openCheckout(r:any){if(r.provider==='monobank'){window.location.assign(r.checkout_url);return}await this.openWidget(r)}
 availableProviders(){return(['monobank','liqpay'] as const).filter(p=>this.data()?.providers?.[p]?.active)}
 providerActive(){return !!this.data()?.providers?.[this.selectedProvider]?.active}
 displayCurrency(){return this.selectedProvider==='monobank'&&this.data()?.uah_quote&&this.i18n.locale()==='uk'?'UAH':'USD'}
 displayAmount(amount:any){const value=Number(amount||0);return this.displayCurrency()==='UAH'?Math.round(value*Number(this.data().uah_quote.rate)*100)/100:value}
 async purchase(period:string){if(this.busy())return;this.busy.set(true);this.error.set('');try{const checkout=await this.api.checkout(this.guildId,{plugin_key:'__paid_modules__',billing_period:period,provider:this.selectedProvider});await this.openCheckout(checkout)}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.purchase_error','Unable to purchase subscription.')))}finally{this.busy.set(false)}}
 validDays(){return this.customDays!==null&&Number.isInteger(Number(this.customDays))&&Number(this.customDays)>=1&&Number(this.customDays)<=3660}
 async calculate(){if(!this.validDays()||this.busy())return;this.busy.set(true);this.error.set('');this.quote.set(null);try{this.quote.set(await this.api.quoteDays(this.guildId,Number(this.customDays)))}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.quote_error','Unable to calculate the price.')))}finally{this.busy.set(false)}}
 async purchaseCustom(){const q=this.quote();if(!q||this.busy()||q.days!==Number(this.customDays))return;this.busy.set(true);this.error.set('');try{const checkout=await this.api.checkout(this.guildId,{plugin_key:'__paid_modules__',billing_period:'custom',days:q.days,provider:this.selectedProvider});if(Number(checkout.base_amount_usd??checkout.charge_amount)!==Number(q.total_amount)){this.quote.set(null);throw new Error(this.i18n.t('billing.price_changed','The price changed. Calculate again before paying.'))}await this.openCheckout(checkout)}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.purchase_error','Unable to purchase subscription.')))}finally{this.busy.set(false)}}
 async previewVoucher(){if(this.busy()||this.voucherCode.trim().length<3)return;this.busy.set(true);this.error.set('');this.voucherPreview.set(null);try{this.voucherPreview.set(await this.api.previewServerVoucher(this.guildId,this.voucherCode.trim()))}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.voucher_error','Unable to check voucher.')))}finally{this.busy.set(false)}}
 async redeemVoucher(){const preview=this.voucherPreview();if(this.busy()||!preview||preview.code!==this.voucherCode.trim().toUpperCase())return;this.busy.set(true);this.error.set('');try{const result=await this.api.redeemServerVoucher(this.guildId,preview.code);this.voucherPreview.set(null);this.voucherCode='';this.success.set(this.i18n.t('billing.voucher_activated','Server subscription activated with voucher.')+` +${result.days} ${this.i18n.t('billing.days_unit','days')}`);await this.load()}catch(e:any){this.error.set(this.err(e,this.i18n.t('billing.voucher_error','Unable to use voucher.')))}finally{this.busy.set(false)}}
 paidPlans(){return(this.data()?.plans||[]).filter((x:any)=>!x.is_free)}price(p:any,k:string){return p['discounted_'+k+'_price']}periodLabel(k:string){return this.i18n.t('billing.'+k,k)}periodDiscount(p:any,k:string){return Number(k==='quarterly'?p.quarterly_discount_percent:k==='yearly'?p.yearly_discount_percent:0)}active(k:string){return(this.data()?.subscriptions||[]).some((x:any)=>x.plugin_key===k&&x.status==='active'&&new Date(x.expires_at)>new Date())}name(k:string){return k==='__paid_modules__'?this.i18n.t('billing.server_activation','Server activation'):k}err(e:any,f:string){const detail=e?.error?.detail||e?.message;const keys:Record<string,string>={monobank_invoice_rejected:'monobank_invoice_rejected',monobank_rate_limited:'monobank_rate_limited',monobank_unavailable:'monobank_unavailable'};return keys[detail]?this.i18n.t('billing.'+keys[detail],f):detail||f}
}
