import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom, Subscription } from 'rxjs';
import { EventBusService, ShieldNetEvent } from '../core/event-bus.service';
import { OperationsService } from '../core/operations.service';
import { ShellComponent } from '../shared/shell.component';

interface LogRow { id: string; time: string; level: string; source: string; type: string; message: string; }
@Component({selector:'sn-live-logs',standalone:true,imports:[CommonModule,FormsModule,ShellComponent],template:`
<sn-shell title="Live Logs"><header class="hero"><div><div class="eyebrow">EVENTBUS STREAM</div><h2>Live Logs</h2><p>Unified audit and runtime event stream without page reloads.</p></div><div class="state" [class.online]="eventBus.state()==='online'"><span></span>{{eventBus.state()}}</div></header>
<div class="toolbar"><select [(ngModel)]="level"><option value="">All levels</option><option>INFO</option><option>WARNING</option><option>ERROR</option><option>DEBUG</option></select><input [(ngModel)]="query" placeholder="Search event, source or message"><label><input type="checkbox" [(ngModel)]="paused"> Pause stream</label><button (click)="rows.set([])">Clear</button></div>
<section class="console">@for(row of filtered();track row.id){<article><time>{{row.time|date:'HH:mm:ss'}}</time><b [class]="row.level.toLowerCase()">{{row.level}}</b><span>{{row.source}}</span><strong>{{row.type}}</strong><p>{{row.message}}</p></article>}@empty{<div class="empty">No matching log entries.</div>}</section>
</sn-shell>`,styles:[`.hero{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin-bottom:1rem}.eyebrow{font-size:.7rem;letter-spacing:.14em;color:var(--primary);font-weight:800}.hero h2{margin:.3rem 0}.hero p{margin:0;color:var(--muted)}.state{display:flex;align-items:center;gap:.5rem;border:1px solid var(--line);padding:.5rem .8rem;border-radius:999px;text-transform:uppercase;font-size:.72rem}.state span{width:.6rem;height:.6rem;border-radius:50%;background:var(--danger)}.state.online span{background:var(--success);box-shadow:0 0 10px color-mix(in srgb,var(--success) 70%,transparent)}.toolbar{display:flex;gap:.7rem;flex-wrap:wrap;margin-bottom:1rem}.toolbar select,.toolbar input:not([type=checkbox]),.toolbar button,.toolbar label{border:1px solid var(--line);border-radius:10px;padding:.65rem .8rem;background:var(--panel);color:var(--text)}.toolbar input:not([type=checkbox]){min-width:260px;flex:1 1 360px}.toolbar label{display:flex;align-items:center;gap:.55rem}.toolbar label input{width:18px;height:18px;margin:0;accent-color:var(--primary)}.console{background:var(--panel);border:1px solid var(--line);border-radius:16px;overflow:auto;max-height:70vh;font-family:ui-monospace,monospace;box-shadow:var(--shadow)}.console article{display:grid;grid-template-columns:76px 72px minmax(90px,120px) minmax(180px,280px) minmax(260px,1fr);gap:.7rem;padding:.7rem .9rem;border-bottom:1px solid var(--line);align-items:start}.console article>*{min-width:0}.console time,.console span{color:var(--muted)}.console b{font-size:.72rem}.console b.info{color:var(--accent)}.console b.warning{color:var(--warning)}.console b.error{color:var(--danger)}.console b.debug{color:var(--primary)}.console strong{color:var(--text);overflow-wrap:anywhere}.console p{margin:0;color:var(--muted);overflow-wrap:anywhere}.empty{padding:2rem;text-align:center;color:var(--muted)}@media(max-width:900px){.console article{grid-template-columns:65px 65px minmax(0,1fr)}.console article span{display:none}.console article p{grid-column:1/-1}.hero{align-items:flex-start;flex-direction:column}}` ]})
export class LiveLogsComponent implements OnInit,OnDestroy{readonly rows=signal<LogRow[]>([]);level='';query='';paused=false;private sub?:Subscription;constructor(public readonly eventBus:EventBusService,private readonly operations:OperationsService){}async ngOnInit(){this.eventBus.connect();try{const s=await firstValueFrom(this.operations.snapshot());this.rows.set(s.events.map(e=>({id:e.id,time:e.created_at,level:this.resultLevel(e.result),source:'audit',type:e.event_type,message:e.message||e.target_type||'Platform event'})));}catch{}this.sub=this.eventBus.events$.subscribe(e=>this.push(e));}ngOnDestroy(){this.sub?.unsubscribe();}filtered(){const q=this.query.trim().toLowerCase();return this.rows().filter(r=>(!this.level||r.level===this.level)&&(!q||`${r.source} ${r.type} ${r.message}`.toLowerCase().includes(q)));}private push(e:ShieldNetEvent){if(this.paused||e.type.startsWith('system.'))return;const payload=e.payload as Record<string,unknown>;const level=String(payload?.['level']||this.resultLevel(String(payload?.['result']||''))).toUpperCase();const row={id:e.correlation_id||`${Date.now()}-${Math.random()}`,time:e.created_at||new Date().toISOString(),level,source:e.source||'eventbus',type:e.type,message:String(payload?.['message']||payload?.['title']||JSON.stringify(payload||{}))};this.rows.update(items=>[row,...items].slice(0,500));}private resultLevel(v:string){const x=v.toLowerCase();return x.includes('fail')||x.includes('error')?'ERROR':x.includes('warn')||x.includes('stale')?'WARNING':'INFO';}}
