import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';

import { MemberActionService } from '../core/member-action.service';
import { CaseAppeal, CaseEvidence, Member, MemberAction, MemberCase, MemberService, MemberStats } from '../core/member.service';
import { ShellComponent } from '../shared/shell.component';
import { TranslatePipe } from '../core/translate.pipe';
import { TranslationService } from '../core/translation.service';
import { ModalService } from '../core/modal.service';
import { ToastService } from '../core/toast.service';

@Component({
  standalone:true,
  imports:[FormsModule, ShellComponent,TranslatePipe],
  template:`
  <sn-shell [title]="'members.title' | snT:'Members Control Center'">
    <section class="topline">
      <div><div class="eyebrow">SHIELDNET v5.1</div><h2>{{ "members.heading" | snT:"Members Control Center" }}</h2><p>{{ "members.description" | snT:"Search, inspect and manage Discord members from one secure console." }}</p></div>
      <button class="btn secondary" (click)="reload()">↻ {{ "members.refresh" | snT:"Refresh" }}</button>
    </section>

    @if (stats()) {
      <section class="stats">
        <button (click)="setStatus('active')"><strong>{{stats()!.total}}</strong><span>{{ "members.active" | snT:"Active" }}</span></button>
        <button (click)="setType('human')"><strong>{{stats()!.humans}}</strong><span>{{ "members.humans" | snT:"Humans" }}</span></button>
        <button (click)="setType('bot')"><strong>{{stats()!.bots}}</strong><span>{{ "members.bots" | snT:"Bots" }}</span></button>
        <button (click)="setStatus('active')"><strong>{{stats()!.active_24h}}</strong><span>{{ "members.active_24h" | snT:"Active 24h" }}</span></button>
        <button (click)="setStatus('inactive')"><strong>{{stats()!.inactive_30d}}</strong><span>{{ "members.inactive_30d" | snT:"Inactive 30d" }}</span></button>
        <button (click)="setStatus('blocked')"><strong>{{stats()!.blocked}}</strong><span>{{ "members.blocked" | snT:"Blocked" }}</span></button>
        <button (click)="setStatus('watchlist')"><strong>{{stats()!.watchlisted}}</strong><span>{{ "members.watchlist" | snT:"Watchlist" }}</span></button>
        <button (click)="setStatus('review_due')"><strong>{{stats()!.review_due}}</strong><span>{{ "members.review_due" | snT:"Review due" }}</span></button>
        <button (click)="setStatus('watchlist')"><strong>{{stats()!.high_risk}}</strong><span>{{ "members.high_risk" | snT:"High risk" }}</span></button>
      </section>
    }

    <section class="card filters">
      <input [(ngModel)]="query" (keyup.enter)="loadMembers()" [placeholder]="'members.search_placeholder' | snT:'Search Discord name, game nickname, alliance, language or ID'">
      <select [(ngModel)]="memberType" (change)="loadMembers()"><option value="all">{{ "members.all_types" | snT:"All types" }}</option><option value="human">{{ "members.humans" | snT:"Humans" }}</option><option value="bot">{{ "members.bots" | snT:"Bots" }}</option></select>
      <select [(ngModel)]="statusFilter" (change)="loadMembers()"><option value="active">{{ "members.active_filter" | snT:"Active" }}</option><option value="pending">{{ "members.pending" | snT:"Pending" }}</option><option value="timed_out">{{ "members.timed_out" | snT:"Timed out" }}</option><option value="blocked">{{ "members.blocked_filter" | snT:"ShieldNet blocked" }}</option><option value="inactive">{{ "members.inactive_filter" | snT:"Inactive 30d" }}</option><option value="watchlist">{{ "members.watchlist_filter" | snT:"Watchlist" }}</option><option value="review_due">{{ "members.review_due_filter" | snT:"Review due" }}</option><option value="left">{{ "members.left_server" | snT:"Left server" }}</option></select>
      <select [(ngModel)]="sort" (change)="loadMembers()"><option value="activity">{{ "members.recent_activity" | snT:"Recent activity" }}</option><option value="name">{{ "members.name_az" | snT:"Name A–Z" }}</option><option value="joined">{{ "members.newest_joined" | snT:"Newest joined" }}</option><option value="oldest">{{ "members.oldest_joined" | snT:"Oldest joined" }}</option></select>
      <button class="btn" (click)="loadMembers()">{{ "members.search" | snT:"Search" }}</button>
    </section>

    @if (selectedIds.size) {
      <section class="card bulk">
        <strong>{{ selectedIds.size }} {{ "members.selected" | snT:"selected" }}</strong>
        <input [(ngModel)]="bulkMessage" [placeholder]="'members.bulk_message' | snT:'Message for selected members'">
        <button class="btn secondary" (click)="bulk('send_dm')">{{ "members.send_dm" | snT:"Send DM" }}</button>
        <button class="btn secondary" (click)="bulk('shieldnet_block')">{{ "members.block" | snT:"Block" }}</button>
        <button class="btn secondary" (click)="bulk('shieldnet_unblock')">{{ "members.unblock" | snT:"Unblock" }}</button>
        <button class="link" (click)="clearSelection()">{{ "members.clear" | snT:"Clear" }}</button>
      </section>
    }

    @if (error()) { <section class="card alert">{{error()}}</section> }

    <section class="workspace">
      <div class="card table-card">
        <div class="table-head"><label><input type="checkbox" [checked]="allSelected()" (change)="toggleAll($event)"> {{ "members.select_all" | snT:"Select all" }}</label><span>{{ total }} {{ "members.members" | snT:"members" }}</span></div>
        @if (loading()) { <div class="empty">{{ "members.loading" | snT:"Loading members…" }}</div> }
        @for (member of members(); track member.discord_user_id) {
          <article class="member" [class.active]="selected()?.discord_user_id===member.discord_user_id" (click)="open(member)">
            <input type="checkbox" [checked]="selectedIds.has(member.discord_user_id)" (click)="$event.stopPropagation()" (change)="toggle(member.discord_user_id)">
            <div class="avatar">@if(member.avatar_url){<img [src]="member.avatar_url" alt="">}@else{<span>{{initial(member)}}</span>}</div>
            <div class="identity"><strong>{{displayName(member)}}</strong><span>@{{member.username}} · {{member.discord_user_id}}</span><div class="chips">@if(member.bot){<i>{{ "members.bot_badge" | snT:"BOT" }}</i>} @if(member.pending){<i>{{ "members.pending_badge" | snT:"Pending" }}</i>} @if(member.shieldnet_blocked){<i class="danger">{{ "members.blocked_badge" | snT:"Blocked" }}</i>} @if(member.watchlisted){<i class="risk" [class]="member.risk_level">{{member.risk_level}} {{ "members.risk_suffix" | snT:"risk" }}</i>} @for(tag of member.tags; track tag){<i>{{tag}}</i>}</div></div>
            <div class="roles">@for(role of member.roles.slice(0,2); track role.discord_role_id){<span>{{role.role_name}}</span>} @if(member.roles.length>2){<span>+{{member.roles.length-2}}</span>}</div>
            <div class="activity"><strong>{{relative(member.last_activity_at)}}</strong><span>{{ "members.last_activity" | snT:"Last activity" }}</span></div>
          </article>
        } @empty { @if(!loading()){<div class="empty">{{ "members.empty" | snT:"No members match these filters." }}</div>} }
        <div class="pager"><button [disabled]="page===1" (click)="changePage(-1)">{{ "members.previous" | snT:"Previous" }}</button><span>{{ "members.page" | snT:"Page" }} {{ page }} / {{ pages }}</span><button [disabled]="page>=pages" (click)="changePage(1)">{{ "members.next" | snT:"Next" }}</button></div>
      </div>

      <aside class="card inspector" [class.open]="selected()">
        @if (selected(); as member) {
          <div class="profile"><div class="avatar large">@if(member.avatar_url){<img [src]="member.avatar_url" alt="">}@else{<span>{{initial(member)}}</span>}</div><h3>{{displayName(member)}}</h3><p>@{{member.username}}</p><code>{{member.discord_user_id}}</code><button class="btn secondary" (click)="openFullInspector(member)">{{ "members.open_inspector" | snT:"Open full inspector" }}</button></div>
          <div class="quick-actions"><button (click)="promptAction('send_dm')">{{ "members.message" | snT:"Message" }}</button><button (click)="promptAction('rename')">{{ "members.rename" | snT:"Rename" }}</button><button (click)="promptAction(member.shieldnet_blocked?'shieldnet_unblock':'shieldnet_block')">{{ member.shieldnet_blocked ? ('members.unblock' | snT:'Unblock') : ('members.block' | snT:'Block') }}</button><button class="danger" (click)="promptAction('kick')">{{ "members.kick" | snT:"Kick" }}</button><button class="danger" (click)="promptAction('ban')">{{ "members.ban" | snT:"Ban" }}</button></div>
          <div class="facts"><div><span>{{ "members.joined" | snT:"Joined" }}</span><strong>{{date(member.joined_at)}}</strong></div><div><span>{{ "members.last_activity" | snT:"Last activity" }}</span><strong>{{date(member.last_activity_at)}}</strong></div><div><span>{{ "members.roles" | snT:"Roles" }}</span><strong>{{member.roles.length}}</strong></div><div><span>{{ "members.status" | snT:"Status" }}</span><strong>{{ member.is_active ? ('members.active' | snT:'Active') : ('members.left' | snT:'Left') }}</strong></div></div>
          <div class="review-grid"><label class="check"><input type="checkbox" [(ngModel)]="watchlisted"> {{ "members.watchlist_member" | snT:"Watchlist member" }}</label><label class="field">{{ "members.risk_level" | snT:"Risk level" }}<select [(ngModel)]="riskLevel"><option value="low">{{ "members.low" | snT:"Low" }}</option><option value="medium">{{ "members.medium" | snT:"Medium" }}</option><option value="high">{{ "members.high" | snT:"High" }}</option><option value="critical">{{ "members.critical" | snT:"Critical" }}</option></select></label></div>
          <label class="field">{{ "members.review_due_label" | snT:"Review due" }}<input type="datetime-local" [(ngModel)]="reviewDueAt"></label>
          <label class="field">{{ "members.review_reason" | snT:"Review reason" }}<textarea [(ngModel)]="reviewReason" rows="3" [placeholder]="'members.review_reason_placeholder' | snT:'Reason for monitoring or follow-up'"></textarea></label>
          <label class="field">{{ "members.tags" | snT:"Tags" }}<input [(ngModel)]="tagsText" [placeholder]="'members.tags_placeholder' | snT:'trusted, vip, review'"></label>
          <label class="field">{{ "members.private_note" | snT:"Private admin note" }}<textarea [(ngModel)]="adminNote" rows="5" [placeholder]="'members.private_note_placeholder' | snT:'Visible only to authorized ShieldNet staff'"></textarea></label>
          <button class="btn save" (click)="saveProfile()">{{ "members.save_profile" | snT:"Save profile" }}</button>
          <div class="section"><h4>{{ "members.member_cases" | snT:"Member cases" }}</h4>
            <div class="case-form">
              <input [(ngModel)]="caseTitle" [placeholder]="'members.case_title' | snT:'Case title'">
              <select [(ngModel)]="caseCategory"><option value="warning">{{ "members.warning" | snT:"Warning" }}</option><option value="spam">{{ "members.spam" | snT:"Spam" }}</option><option value="harassment">{{ "members.harassment" | snT:"Harassment" }}</option><option value="security">{{ "members.security" | snT:"Security" }}</option><option value="appeal">{{ "members.appeal" | snT:"Appeal" }}</option><option value="other">{{ "members.other" | snT:"Other" }}</option></select>
              <select [(ngModel)]="caseSeverity"><option value="low">{{ "members.low" | snT:"Low" }}</option><option value="medium">{{ "members.medium" | snT:"Medium" }}</option><option value="high">{{ "members.high" | snT:"High" }}</option><option value="critical">{{ "members.critical" | snT:"Critical" }}</option></select>
              <textarea [(ngModel)]="caseDescription" rows="3" [placeholder]="'members.incident_details' | snT:'Incident details'"></textarea>
              <button class="btn" (click)="createCase()">{{ "members.create_case" | snT:"Create case" }}</button>
            </div>
            @for(item of cases(); track item.id){<article class="case-item" [class.selected-case]="selectedCaseId===item.id"><div><strong>{{item.title}}</strong><span>{{item.category}} · {{item.severity}}</span></div><select [ngModel]="item.status" (ngModelChange)="changeCaseStatus(item,$event)"><option value="open">{{ "members.open" | snT:"Open" }}</option><option value="investigating">{{ "members.investigating" | snT:"Investigating" }}</option><option value="resolved">{{ "members.resolved" | snT:"Resolved" }}</option><option value="dismissed">{{ "members.dismissed" | snT:"Dismissed" }}</option></select><p>{{ item.description || ('members.no_description' | snT:'No description') }}</p><small>{{date(item.created_at)}}</small><button class="case-open" (click)="openCase(item)">{{ "members.evidence_appeals" | snT:"Evidence & appeals" }}</button></article>} @empty {<p class="muted">{{ "members.no_cases" | snT:"No cases recorded." }}</p>}
          </div>
          @if(selectedCaseId){
            <div class="section case-center"><h4>{{ "members.evidence_appeals" | snT:"Evidence & appeals" }}</h4>
              <div class="case-form"><strong>{{ "members.evidence" | snT:"Evidence" }}</strong><input [(ngModel)]="evidenceTitle" [placeholder]="'members.evidence_title' | snT:'Evidence title'"><select [(ngModel)]="evidenceType"><option value="link">{{ "members.link" | snT:"Link" }}</option><option value="screenshot">{{ "members.screenshot" | snT:"Screenshot" }}</option><option value="message">{{ "members.message_type" | snT:"Message" }}</option><option value="document">{{ "members.document" | snT:"Document" }}</option><option value="other">{{ "members.other" | snT:"Other" }}</option></select><input [(ngModel)]="evidenceUrl" [placeholder]="'members.evidence_url_placeholder' | snT:'https://...'"><textarea [(ngModel)]="evidenceNotes" rows="2" [placeholder]="'members.evidence_notes' | snT:'Evidence notes'"></textarea><button class="btn" (click)="createEvidence()">{{ "members.add_evidence" | snT:"Add evidence" }}</button></div>
              @for(item of evidence(); track item.id){<article class="evidence-item"><div><strong>{{item.title}}</strong><span>{{item.evidence_type}} · {{date(item.created_at)}}</span></div>@if(item.source_url){<a [href]="item.source_url" target="_blank" rel="noopener">{{ "members.open_source" | snT:"Open source" }}</a>}<p>{{ item.notes || ('members.no_notes' | snT:'No notes') }}</p><button class="danger-link" (click)="removeEvidence(item)">{{ "members.delete" | snT:"Delete" }}</button></article>} @empty {<p class="muted">{{ "members.no_evidence" | snT:"No evidence attached." }}</p>}
              <div class="case-form"><strong>{{ "members.appeal" | snT:"Appeal" }}</strong><input [(ngModel)]="appealName" [placeholder]="'members.submitted_by' | snT:'Submitted by'"><textarea [(ngModel)]="appealStatement" rows="3" [placeholder]="'members.appeal_statement' | snT:'Appeal statement'"></textarea><button class="btn secondary" (click)="createAppeal()">{{ "members.register_appeal" | snT:"Register appeal" }}</button></div>
              @for(item of appeals(); track item.id){<article class="appeal-item"><div><strong>{{ item.submitted_by_name || ('members.member_appeal' | snT:'Member appeal') }}</strong><span>{{date(item.created_at)}}</span></div><select [ngModel]="item.status" (ngModelChange)="changeAppealStatus(item,$event)"><option value="submitted">{{ "members.submitted" | snT:"Submitted" }}</option><option value="under_review">{{ "members.under_review" | snT:"Under review" }}</option><option value="accepted">{{ "members.accepted" | snT:"Accepted" }}</option><option value="rejected">{{ "members.rejected" | snT:"Rejected" }}</option><option value="withdrawn">{{ "members.withdrawn" | snT:"Withdrawn" }}</option></select><p>{{item.statement}}</p>@if(item.decision){<small>{{ "members.decision" | snT:"Decision" }}: {{item.decision}}</small>}<button class="case-open" (click)="setAppealDecision(item)">{{ "members.set_decision" | snT:"Set decision" }}</button></article>} @empty {<p class="muted">{{ "members.no_appeals" | snT:"No appeals registered." }}</p>}
            </div>
          }
          <div class="section"><h4>{{ "members.roles_heading" | snT:"Roles" }}</h4><div class="role-list">@for(role of member.roles; track role.discord_role_id){<span>{{role.role_name}}</span>}</div></div>
          <div class="section"><h4>{{ "members.action_history" | snT:"Action history" }}</h4>@for(action of actions(); track action.id){<div class="history"><span>{{action.action_type}}</span><b [class]="action.status">{{action.status}}</b><small>{{ action.result_message || ('members.queued_bot' | snT:'Queued through Discord bot') }}</small></div>} @empty {<p class="muted">{{ "members.no_actions" | snT:"No actions recorded." }}</p>}</div>
        } @else { <div class="empty inspector-empty">{{ "members.select_member" | snT:"Select a member to open the control panel." }}</div> }
      </aside>
    </section>
  </sn-shell>`,
  styles:[`
    h2,h3,h4,p{margin:.2rem 0}.topline{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem}.topline p,.eyebrow{color:var(--muted)}.eyebrow{font-size:.72rem;letter-spacing:.18em;font-weight:800;color:#8e9aff}
    .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem;margin-bottom:1rem}.stats button{background:var(--panel);border:1px solid var(--line);color:var(--text);border-radius:14px;padding:1rem;text-align:left}.stats strong{display:block;font-size:1.45rem}.stats span{color:var(--muted);font-size:.8rem}
    .profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem}.filters{display:grid;grid-template-columns:minmax(260px,2fr) repeat(3,minmax(130px,1fr)) auto;gap:.7rem;padding:.8rem;margin-bottom:1rem}.filters input,.filters select,.bulk input,.field input,.field textarea{width:100%;background:var(--panel-2);border:1px solid var(--line);border-radius:10px;color:var(--text);padding:.72rem}.bulk{display:flex;align-items:center;gap:.7rem;padding:.8rem;margin-bottom:1rem}.bulk input{flex:1}.link{background:none;color:var(--muted)}.alert{padding:1rem;color:#ffd0d6;margin-bottom:1rem}
    .workspace{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:1rem}.table-card{overflow:hidden}.table-head,.pager{display:flex;justify-content:space-between;padding:.8rem 1rem;color:var(--muted);border-bottom:1px solid var(--line)}.member{display:grid;grid-template-columns:24px 48px minmax(220px,1fr) minmax(130px,.6fr) 110px;gap:.8rem;align-items:center;padding:.8rem 1rem;border-bottom:1px solid var(--line);cursor:pointer}.member:hover,.member.active{background:var(--primary-soft)}
    .avatar{width:46px;height:46px;border-radius:14px;overflow:hidden;background:linear-gradient(135deg,var(--primary),#9a64ff);display:grid;place-items:center;font-weight:900}.avatar img{width:100%;height:100%;object-fit:cover}.identity{min-width:0}.identity>strong,.identity>span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.identity>span,.activity span{color:var(--muted);font-size:.78rem}.chips,.role-list{display:flex;gap:.3rem;flex-wrap:wrap;margin-top:.35rem}.chips i,.roles span,.role-list span{font-style:normal;font-size:.68rem;padding:.2rem .42rem;border-radius:999px;background:var(--panel-2);border:1px solid var(--line)}.chips .danger{color:#ff8997}.chips .risk.medium{color:#ffc76b}.chips .risk.high,.chips .risk.critical{color:#ff8997}.review-grid{display:grid;grid-template-columns:1fr 1fr;gap:.7rem;align-items:end}.check{display:flex;align-items:center;gap:.5rem;color:var(--muted);font-size:.8rem;padding:.75rem 0}.field select{width:100%;background:var(--panel-2);border:1px solid var(--line);border-radius:10px;color:var(--text);padding:.72rem}.roles{display:flex;gap:.3rem;flex-wrap:wrap}.activity{text-align:right}.activity strong{display:block;font-size:.82rem}.empty{padding:2rem;text-align:center;color:var(--muted)}.pager{border:0}.pager button{background:var(--panel-2);border:1px solid var(--line);color:var(--text);padding:.5rem .8rem;border-radius:8px}.pager button:disabled{opacity:.4}
    .inspector{padding:1rem;align-self:start;position:sticky;top:1rem;max-height:calc(100vh - 2rem);overflow:auto}.profile{text-align:center;padding:.5rem}.avatar.large{width:76px;height:76px;border-radius:22px;margin:auto}.profile p,.profile code{color:var(--muted)}.quick-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:.4rem;margin:1rem 0}.quick-actions button{padding:.6rem .3rem;border-radius:9px;background:var(--panel-2);border:1px solid var(--line);color:var(--text)}button.danger,.quick-actions .danger{color:#ff8997}.facts{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin-bottom:1rem}.facts div{background:var(--panel-2);border-radius:10px;padding:.7rem}.facts span,.facts strong{display:block}.facts span{font-size:.7rem;color:var(--muted)}.field{display:grid;gap:.35rem;color:var(--muted);font-size:.8rem;margin:.8rem 0}.save{width:100%}.section{border-top:1px solid var(--line);margin-top:1rem;padding-top:1rem}.history{display:grid;grid-template-columns:1fr auto;gap:.25rem;padding:.55rem 0;border-bottom:1px solid var(--line);font-size:.8rem}.history small{grid-column:1/-1;color:var(--muted)}.history b{font-size:.68rem;text-transform:uppercase}.case-form{display:grid;gap:.45rem;margin:.6rem 0}.case-form input,.case-form select,.case-form textarea,.case-item select{width:100%;background:var(--panel-2);border:1px solid var(--line);border-radius:9px;color:var(--text);padding:.6rem}.case-item{display:grid;grid-template-columns:1fr 130px;gap:.35rem;padding:.7rem 0;border-bottom:1px solid var(--line)}.case-item div span,.case-item small{display:block;color:var(--muted);font-size:.72rem}.case-item p,.case-item small{grid-column:1/-1}.case-item p{margin:.25rem 0;font-size:.82rem}.case-open,.danger-link{background:none;border:0;color:#91a2ff;text-align:left;padding:.25rem 0;cursor:pointer}.danger-link{color:#ff8997}.selected-case{background:var(--primary-soft)}.case-center{display:grid;gap:.55rem}.evidence-item,.appeal-item{display:grid;grid-template-columns:1fr auto;gap:.35rem;padding:.7rem;border:1px solid var(--line);border-radius:10px;background:var(--panel-2)}.evidence-item span,.appeal-item span,.appeal-item small{display:block;color:var(--muted);font-size:.72rem}.evidence-item p,.appeal-item p,.evidence-item .danger-link,.appeal-item .case-open,.appeal-item small{grid-column:1/-1}.appeal-item select{background:var(--panel);border:1px solid var(--line);border-radius:8px;color:var(--text);padding:.45rem}.completed{color:var(--success)}.failed{color:var(--danger)}.processing{color:var(--warning)}
    @media(max-width:1200px){.stats{grid-template-columns:repeat(3,1fr)}.workspace{grid-template-columns:1fr}.inspector{position:static;max-height:none}}@media(max-width:760px){.profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem}.filters{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.member{grid-template-columns:24px 46px 1fr}.roles,.activity{display:none}.bulk{flex-wrap:wrap}.topline{align-items:flex-start}.topline p{display:none}}
  `]
})
export class MembersComponent implements OnInit {
  readonly guildId=this.route.snapshot.paramMap.get('guildId') ?? '';
  readonly members=signal<Member[]>([]); readonly selected=signal<Member|null>(null); readonly stats=signal<MemberStats|null>(null); readonly actions=signal<MemberAction[]>([]); readonly cases=signal<MemberCase[]>([]); readonly evidence=signal<CaseEvidence[]>([]); readonly appeals=signal<CaseAppeal[]>([]); readonly loading=signal(false); readonly error=signal('');
  query=''; memberType='all'; statusFilter='active'; sort='activity'; page=1; pageSize=50; total=0; selectedIds=new Set<string>(); adminNote=''; tagsText=''; bulkMessage=''; gameNickname=''; allianceTag=''; leadershipRank:'R5'|'R4'|'member'|null=null; preferredLanguage=''; verificationStatus:'not_verified'|'pending'|'verified'|'rejected'|'expired'='not_verified'; watchlisted=false; riskLevel:'low'|'medium'|'high'|'critical'='low'; reviewDueAt=''; reviewReason=''; caseTitle=''; caseCategory:'warning'|'spam'|'harassment'|'security'|'appeal'|'other'='other'; caseSeverity:'low'|'medium'|'high'|'critical'='medium'; caseDescription=''; selectedCaseId=''; evidenceTitle=''; evidenceType:'link'|'screenshot'|'message'|'document'|'other'='link'; evidenceUrl=''; evidenceNotes=''; appealName=''; appealStatement='';
  constructor(private route:ActivatedRoute,private service:MemberService,private actionService:MemberActionService,private router:Router,private i18n:TranslationService,private modal:ModalService,private toast:ToastService){}
  async ngOnInit(){await this.reload();}
  get pages(){return Math.max(1,Math.ceil(this.total/this.pageSize));}
  async reload(){await Promise.all([this.loadMembers(),this.loadStats()]);}
  async loadStats(){try{this.stats.set(await this.service.stats(this.guildId));}catch{}}
  async loadMembers(){this.loading.set(true);this.error.set('');try{const r=await this.service.list(this.guildId,{query:this.query,page:this.page,page_size:this.pageSize,member_type:this.memberType,status_filter:this.statusFilter,sort:this.sort});this.members.set(r.items);this.total=r.total;}catch(error){this.error.set(this.requestError(error,this.i18n.t('members.load_error','Unable to load members.')));}finally{this.loading.set(false)}}
  private requestError(error: unknown, fallback: string): string {
    if (error instanceof HttpErrorResponse) {
      if (error.status === 401) return 'Your session has expired. Sign in again.';
      if (error.status === 403) return 'You do not have permission to manage this server.';
      if (error.status === 0) return 'The server is temporarily unavailable.';
      const detail = typeof error.error?.detail === 'string' ? error.error.detail : '';
      if (detail) return detail;
    }
    return fallback;
  }

  async open(m:Member){try{const full=await this.service.detail(this.guildId,m.discord_user_id);this.selected.set(full);this.gameNickname=full.game_nickname||'';this.allianceTag=full.alliance_tag||'';this.leadershipRank=full.leadership_rank;this.preferredLanguage=full.preferred_language||'';this.verificationStatus=full.verification_status;this.adminNote=full.admin_note||'';this.tagsText=full.tags.join(', ');this.watchlisted=full.watchlisted;this.riskLevel=full.risk_level;this.reviewDueAt=this.toLocalInput(full.review_due_at);this.reviewReason=full.review_reason||'';this.actions.set(await this.service.actions(this.guildId,m.discord_user_id));this.cases.set(await this.service.cases(this.guildId,m.discord_user_id));this.selectedCaseId='';this.evidence.set([]);this.appeals.set([]);}catch{this.error.set(this.i18n.t('members.open_profile_error','Unable to open member profile.'))}}
  displayName(m:Member){return m.nickname||m.global_name||m.username} initial(m:Member){return this.displayName(m).slice(0,1).toUpperCase()}
  relative(value:string|null){if(!value)return 'No activity';const ms=Date.now()-new Date(value).getTime(),d=Math.floor(ms/86400000),h=Math.floor(ms/3600000);return d>0?`${d}d ago`:h>0?`${h}h ago`:'Recently'}
  date(value:string|null){return value?new Date(value).toLocaleString():'—'}
  toLocalInput(value:string|null){if(!value)return '';const d=new Date(value),pad=(v:number)=>String(v).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
  toIso(value:string){return value?new Date(value).toISOString():null}
  setStatus(v:string){this.statusFilter=v;this.page=1;this.loadMembers()} setType(v:string){this.memberType=v;this.page=1;this.loadMembers()}
  toggle(id:string){this.selectedIds.has(id)?this.selectedIds.delete(id):this.selectedIds.add(id)} allSelected(){return this.members().length>0&&this.members().every(m=>this.selectedIds.has(m.discord_user_id))}
  toggleAll(e:Event){const checked=(e.target as HTMLInputElement).checked;this.members().forEach(m=>checked?this.selectedIds.add(m.discord_user_id):this.selectedIds.delete(m.discord_user_id))} clearSelection(){this.selectedIds.clear()}
  async changePage(delta:number){this.page+=delta;await this.loadMembers()}
  async saveProfile(){const m=this.selected();if(!m)return;try{const tags=this.tagsText.split(',').map(v=>v.trim()).filter(Boolean);const updated=await this.service.updateProfile(this.guildId,m.discord_user_id,{game_nickname:this.gameNickname||null,alliance_tag:this.allianceTag||null,leadership_rank:this.leadershipRank,preferred_language:this.preferredLanguage||null,verification_status:this.verificationStatus,admin_note:this.adminNote||null,tags,watchlisted:this.watchlisted,risk_level:this.riskLevel,review_due_at:this.toIso(this.reviewDueAt),review_reason:this.reviewReason||null});this.selected.set(updated);await this.loadMembers();}catch{this.error.set(this.i18n.t('members.profile_error','Unable to save member profile.'))}}
  async promptAction(type:string){const m=this.selected();if(!m)return;let payload:Record<string,unknown>={};if(type==='send_dm'){const message=await this.modal.prompt(this.i18n.t('members.direct_message_prompt','Direct message'),'',{title:this.i18n.t('ui.enter_value','Enter value'),confirmLabel:this.i18n.t('ui.save','Save'),cancelLabel:this.i18n.t('ui.cancel','Cancel'),required:true});if(!message)return;payload={message}}if(type==='rename'){const nickname=await this.modal.prompt(this.i18n.t('members.new_nickname_prompt','New nickname'),m.nickname||'',{title:this.i18n.t('ui.enter_value','Enter value'),confirmLabel:this.i18n.t('ui.save','Save'),cancelLabel:this.i18n.t('ui.cancel','Cancel')});if(nickname===null)return;payload={nickname}}if(type==='kick'||type==='ban'){const confirmation=this.i18n.t('members.confirm_action','Confirm {action} for {member}?').replace('{action}',type).replace('{member}',this.displayName(m));if(!await this.modal.confirm(confirmation,{title:this.i18n.t('ui.confirm_title','Confirm action'),confirmLabel:this.i18n.t('ui.confirm','Confirm'),cancelLabel:this.i18n.t('ui.cancel','Cancel'),danger:type==='ban'}))return}try{await this.actionService.create(this.guildId,m.discord_user_id,type,payload);this.actions.set(await this.service.actions(this.guildId,m.discord_user_id));this.cases.set(await this.service.cases(this.guildId,m.discord_user_id));this.toast.success(this.i18n.t('ui.success','Completed'),this.i18n.t('members.action_queued','Member action queued.'))}catch{const message=this.i18n.t('members.action_error','Unable to create the requested member action.');this.error.set(message);this.toast.error(this.i18n.t('ui.error','Operation failed'),message)}}

  async createCase(){const m=this.selected();if(!m||!this.caseTitle.trim())return;try{await this.service.createCase(this.guildId,m.discord_user_id,{title:this.caseTitle,category:this.caseCategory,severity:this.caseSeverity,description:this.caseDescription||null});this.caseTitle='';this.caseDescription='';this.cases.set(await this.service.cases(this.guildId,m.discord_user_id));}catch{this.error.set(this.i18n.t('members.create_case_error','Unable to create member case.'))}}
  async changeCaseStatus(item:MemberCase,status:string){const m=this.selected();if(!m)return;try{await this.service.updateCase(this.guildId,m.discord_user_id,item.id,{status});this.cases.set(await this.service.cases(this.guildId,m.discord_user_id));}catch{this.error.set(this.i18n.t('members.update_case_error','Unable to update member case.'))}}
  async openCase(item:MemberCase){const m=this.selected();if(!m)return;this.selectedCaseId=item.id;try{const [evidence,appeals]=await Promise.all([this.service.evidence(this.guildId,m.discord_user_id,item.id),this.service.appeals(this.guildId,m.discord_user_id,item.id)]);this.evidence.set(evidence);this.appeals.set(appeals);}catch{this.error.set(this.i18n.t('members.case_details_error','Unable to load case evidence and appeals.'))}}
  async createEvidence(){const m=this.selected();if(!m||!this.selectedCaseId||!this.evidenceTitle.trim())return;try{await this.service.createEvidence(this.guildId,m.discord_user_id,this.selectedCaseId,{title:this.evidenceTitle,evidence_type:this.evidenceType,source_url:this.evidenceUrl||null,notes:this.evidenceNotes||null});this.evidenceTitle='';this.evidenceUrl='';this.evidenceNotes='';this.evidence.set(await this.service.evidence(this.guildId,m.discord_user_id,this.selectedCaseId));}catch{this.error.set(this.i18n.t('members.evidence_create_error','Unable to add evidence. Verify that the URL is valid.'))}}
  async removeEvidence(item:CaseEvidence){const m=this.selected();if(!m||!this.selectedCaseId)return;if(!await this.modal.confirm(this.i18n.t('members.evidence_delete_confirm','Delete this evidence record?'),{title:this.i18n.t('ui.confirm_title','Confirm action'),confirmLabel:this.i18n.t('ui.confirm','Confirm'),cancelLabel:this.i18n.t('ui.cancel','Cancel'),danger:true}))return;try{await this.service.deleteEvidence(this.guildId,m.discord_user_id,this.selectedCaseId,item.id);this.evidence.set(await this.service.evidence(this.guildId,m.discord_user_id,this.selectedCaseId));this.toast.success(this.i18n.t('ui.success','Completed'),this.i18n.t('members.evidence_deleted','Evidence deleted.'))}catch{const message=this.i18n.t('members.evidence_delete_error','Unable to delete evidence.');this.error.set(message);this.toast.error(this.i18n.t('ui.error','Operation failed'),message)}}
  async createAppeal(){const m=this.selected();if(!m||!this.selectedCaseId||!this.appealStatement.trim())return;try{await this.service.createAppeal(this.guildId,m.discord_user_id,this.selectedCaseId,{statement:this.appealStatement,submitted_by_name:this.appealName||null});this.appealName='';this.appealStatement='';this.appeals.set(await this.service.appeals(this.guildId,m.discord_user_id,this.selectedCaseId));}catch{this.error.set(this.i18n.t('members.appeal_create_error','Unable to register appeal.'))}}
  async changeAppealStatus(item:CaseAppeal,status:string){const m=this.selected();if(!m||!this.selectedCaseId)return;try{await this.service.updateAppeal(this.guildId,m.discord_user_id,this.selectedCaseId,item.id,{status});this.appeals.set(await this.service.appeals(this.guildId,m.discord_user_id,this.selectedCaseId));}catch{this.error.set(this.i18n.t('members.appeal_update_error','Unable to update appeal.'))}}
  async setAppealDecision(item:CaseAppeal){const m=this.selected();if(!m||!this.selectedCaseId)return;const decision=await this.modal.prompt(this.i18n.t('members.appeal_decision_prompt','Appeal decision'),item.decision||'',{title:this.i18n.t('ui.enter_value','Enter value'),confirmLabel:this.i18n.t('ui.save','Save'),cancelLabel:this.i18n.t('ui.cancel','Cancel'),required:true});if(decision===null)return;try{await this.service.updateAppeal(this.guildId,m.discord_user_id,this.selectedCaseId,item.id,{decision});this.appeals.set(await this.service.appeals(this.guildId,m.discord_user_id,this.selectedCaseId));this.toast.success(this.i18n.t('ui.success','Completed'),this.i18n.t('members.appeal_updated','Appeal decision saved.'))}catch{const message=this.i18n.t('members.appeal_decision_error','Unable to save appeal decision.');this.error.set(message);this.toast.error(this.i18n.t('ui.error','Operation failed'),message)}}
  openFullInspector(member:Member){this.router.navigate(['/guild',this.guildId,'members',member.discord_user_id]);}
  async bulk(type:string){if(type==='send_dm'&&!this.bulkMessage.trim())return;const ids=[...this.selectedIds];try{await Promise.all(ids.map(id=>this.actionService.create(this.guildId,id,type,type==='send_dm'?{message:this.bulkMessage}:{})));this.clearSelection();this.bulkMessage='';}catch{this.error.set(this.i18n.t('members.bulk_queue_error','One or more bulk actions could not be queued.'))}}
}
