import {CommonModule} from '@angular/common';
import {Component,OnInit,effect,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {RouterLink} from '@angular/router';
import {AuthService} from '../core/auth.service';
import {MerchantContent,MerchantPageService} from '../core/merchant-page.service';
import {TranslatePipe} from '../core/translate.pipe';
import {TranslationService} from '../core/translation.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,TranslatePipe],template:`
<main class="legal-page">
  <header class="top"><a routerLink="/login" class="brand">GuildConsole</a><div class="toolbar">
    <label class="language"><span>{{'privacy_page.language'|snT:'Language'}}</span><select [ngModel]="locale()" (ngModelChange)="changeLocale($event)">@for(language of i18n.languages();track language.code){<option [value]="language.code">{{language.icon}} {{language.name}}</option>}</select></label>
    @if(auth.profile()?.is_superadmin){<button class="edit-button" (click)="editing.set(!editing())">{{editing()?('privacy_page.close_editor'|snT:'Close editor'):('privacy_page.edit'|snT:'Edit page')}}</button>}
    <a routerLink="/login" class="back">← {{'merchant.back'|snT:'Back to sign in'}}</a>
  </div></header>
  @if(loading()){<section class="state">{{'merchant.loading'|snT:'Loading information…'}}</section>}@else if(content();as c){
    <section class="hero"><span>{{'privacy_page.eyebrow'|snT:'LEGAL & PRIVACY'}}</span><h1>{{'privacy_page.title'|snT:'Privacy policy and service terms'}}</h1><p>{{'privacy_page.subtitle'|snT:'How GuildConsole processes data, provides digital services, accepts payments and handles refunds.'}}</p></section>
    @if(editing()&&auth.profile()?.is_superadmin){
      <section class="editor"><header><div><span>SUPERADMIN · {{locale().toUpperCase()}}</span><h2>{{'merchant.editor'|snT:'Edit public information'}}</h2><p>{{'privacy_page.locale_hint'|snT:'You are editing content for the selected language.'}}</p></div><div class="editor-actions"><button class="secondary" (click)="editing.set(false)">{{'privacy_page.cancel'|snT:'Cancel'}}</button><button (click)="save()" [disabled]="saving()">{{saving()?('merchant.saving'|snT:'Saving…'):('merchant.save'|snT:'Save changes')}}</button></div></header>
        @if(message()){<p class="message">{{message()}}</p>}
        <div class="form-grid"><label>{{'merchant.business_name'|snT:'Business name'}}<input [(ngModel)]="c.business_name"></label><label>{{'merchant.tax_id'|snT:'Registration / tax number'}}<input [(ngModel)]="c.tax_id"></label><label>{{'merchant.legal_address'|snT:'Legal address'}}<input [(ngModel)]="c.legal_address"></label><label>{{'merchant.actual_address'|snT:'Actual address'}}<input [(ngModel)]="c.actual_address"></label><label>{{'merchant.phone'|snT:'Phone'}}<input [(ngModel)]="c.phone"></label><label>Email<input type="email" [(ngModel)]="c.email"></label></div>
        <label>{{'merchant.service'|snT:'Service description'}}<textarea rows="4" [(ngModel)]="c.service_description"></textarea></label><label>{{'merchant.fulfillment'|snT:'Provision and activation'}}<textarea rows="4" [(ngModel)]="c.service_terms"></textarea></label><label>{{'merchant.payment'|snT:'Payment methods'}}<textarea rows="4" [(ngModel)]="c.payment_methods"></textarea></label><label>{{'merchant.area'|snT:'Service territory'}}<textarea rows="3" [(ngModel)]="c.service_area"></textarea></label><label>{{'merchant.refunds'|snT:'Refund policy'}}<textarea rows="6" [(ngModel)]="c.refund_policy"></textarea></label><label>{{'merchant.cancellation'|snT:'Cancellation policy'}}<textarea rows="5" [(ngModel)]="c.cancellation_policy"></textarea></label><label>{{'merchant.offer'|snT:'Public offer and terms'}}<textarea rows="8" [(ngModel)]="c.public_offer"></textarea></label><label>{{'merchant.privacy'|snT:'Privacy policy'}}<textarea rows="8" [(ngModel)]="c.privacy_policy"></textarea></label>
      </section>
    }@else{
      <section class="grid">
        <article class="wide privacy"><h2>{{'merchant.privacy'|snT:'Privacy policy'}}</h2><p>{{c.privacy_policy}}</p></article>
        <article><h2>{{'merchant.service'|snT:'Service description'}}</h2><p>{{c.service_description}}</p></article><article><h2>{{'merchant.fulfillment'|snT:'Provision and activation'}}</h2><p>{{c.service_terms}}</p></article>
        <article><h2>{{'merchant.payment'|snT:'Payment methods'}}</h2><p>{{c.payment_methods}}</p></article><article><h2>{{'merchant.area'|snT:'Service territory'}}</h2><p>{{c.service_area}}</p></article>
        <article><h2>{{'merchant.refunds'|snT:'Refund policy'}}</h2><p>{{c.refund_policy}}</p></article><article><h2>{{'merchant.cancellation'|snT:'Cancellation policy'}}</h2><p>{{c.cancellation_policy}}</p></article>
        <article class="wide"><h2>{{'merchant.offer'|snT:'Public offer and terms'}}</h2><p>{{c.public_offer}}</p></article>
        <article class="wide seller"><h2>{{'merchant.seller'|snT:'Seller information'}}</h2><dl><div><dt>{{'merchant.business_name'|snT:'Business name'}}</dt><dd>{{c.business_name||'—'}}</dd></div><div><dt>{{'merchant.tax_id'|snT:'Registration / tax number'}}</dt><dd>{{c.tax_id||'—'}}</dd></div><div><dt>{{'merchant.legal_address'|snT:'Legal address'}}</dt><dd>{{c.legal_address||'—'}}</dd></div><div><dt>{{'merchant.actual_address'|snT:'Actual address'}}</dt><dd>{{c.actual_address||'—'}}</dd></div><div><dt>{{'merchant.phone'|snT:'Phone'}}</dt><dd>{{c.phone||'—'}}</dd></div><div><dt>Email</dt><dd>{{c.email||'—'}}</dd></div></dl></article>
      </section>
    }
  }<footer>© GuildConsole · LRM-IT</footer>
</main>`,styles:[`
.legal-page{min-height:100vh;padding:1.2rem clamp(1rem,4vw,4rem);background:var(--bg);color:var(--text)}.top{max-width:1200px;margin:auto;display:flex;justify-content:space-between;align-items:center;padding:.8rem 0}.brand{color:var(--primary);font-weight:900;font-size:1rem}.toolbar{display:flex;align-items:center;gap:.65rem}.back{color:var(--muted);font-size:.75rem}.language{display:flex;align-items:center;gap:.5rem;color:var(--muted);font-size:.68rem}.language select{min-height:38px;width:auto;padding:.45rem 2rem .45rem .65rem}.edit-button,.editor button{min-height:38px;padding:.55rem .8rem;border:0;border-radius:9px;background:var(--primary);color:#042f2e;font-weight:800}.hero{max-width:1200px;margin:3.5rem auto 1.5rem}.hero>span,.editor header span{color:var(--primary);font-size:.65rem;font-weight:900;letter-spacing:.15em}.hero h1{max-width:850px;margin:.55rem 0;font-size:clamp(2.1rem,5vw,4.5rem);line-height:1.03}.hero p{max-width:760px;color:var(--muted);font-size:1rem}.grid{max-width:1200px;margin:auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.grid article,.editor,.state{padding:1.35rem;border:1px solid var(--line);border-radius:16px;background:var(--panel)}article h2{margin:0 0 .8rem;font-size:1.05rem}article p{white-space:pre-wrap;color:var(--muted);line-height:1.75}.wide{grid-column:1/-1}.privacy{border-color:var(--line-strong)!important;background:linear-gradient(145deg,var(--primary-soft),transparent 42%),var(--panel)!important}.seller dl{display:grid;grid-template-columns:repeat(2,1fr);gap:0 2rem;margin:0}dl div{display:grid;grid-template-columns:minmax(130px,.7fr) 1fr;gap:1rem;padding:.7rem 0;border-bottom:1px solid var(--line)}dt{color:var(--muted);font-size:.7rem}dd{margin:0;word-break:break-word}.editor{max-width:1158px;margin:1rem auto;display:grid;gap:1rem;border-color:var(--line-strong)}.editor>header{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem}.editor h2{margin:.3rem 0}.editor header p{margin:0;color:var(--muted)}.editor-actions{display:flex;gap:.5rem}.editor button.secondary{color:var(--text);background:var(--panel-2);border:1px solid var(--line)}.editor label{display:grid;gap:.4rem;color:var(--muted);font-size:.72rem}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.message{padding:.65rem .8rem;border-radius:9px;color:var(--success);background:rgba(52,211,153,.08)}.state{max-width:1200px;margin:4rem auto}footer{max-width:1200px;margin:2rem auto;padding:1rem 0;color:var(--muted);border-top:1px solid var(--line)}@media(max-width:750px){.top{align-items:flex-start}.toolbar{flex-wrap:wrap;justify-content:flex-end}.language span,.back{display:none}.grid,.form-grid,.seller dl{grid-template-columns:1fr}.wide{grid-column:auto}dl div{grid-template-columns:1fr}.editor>header{display:grid}.hero{margin-top:2rem}}
`]})
export class MerchantInformationComponent implements OnInit{
  content=signal<MerchantContent|null>(null);loading=signal(true);saving=signal(false);editing=signal(false);message=signal('');locale=signal('en');
  constructor(private api:MerchantPageService,public auth:AuthService,public i18n:TranslationService){effect(()=>{if(this.i18n.ready()){const code=this.i18n.locale();if(code!==this.locale())void this.load(code)}})}
  async ngOnInit(){await this.load(this.i18n.locale())}
  async load(locale:string){this.locale.set(locale);this.loading.set(true);try{this.content.set(await this.api.get(locale))}finally{this.loading.set(false)}}
  async changeLocale(locale:string){await this.i18n.setLocale(locale,false);await this.load(locale)}
  async save(){const value=this.content();if(!value||this.saving())return;this.saving.set(true);this.message.set('');try{this.content.set(await this.api.save(value,this.locale()));this.message.set(this.i18n.t('merchant.saved','Public information saved.'))}catch(e:any){this.message.set(e?.error?.detail||this.i18n.t('merchant.save_error','Unable to save public information.'))}finally{this.saving.set(false)}}
}
