import {CommonModule} from '@angular/common';
import {Component,OnInit,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {RouterLink} from '@angular/router';
import {AuthService} from '../core/auth.service';
import {MerchantContent,MerchantPageService} from '../core/merchant-page.service';
import {TranslatePipe} from '../core/translate.pipe';
import {TranslationService} from '../core/translation.service';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,TranslatePipe],template:`
<main class="legal-page"><header><a routerLink="/login" class="brand">GUILDCONSOLE</a><a routerLink="/login">← {{'merchant.back'|snT:'Back to sign in'}}</a></header>
@if(loading()){<section class="state">{{'merchant.loading'|snT:'Loading information…'}}</section>}@else if(content();as c){
<section class="hero"><span>{{'merchant.eyebrow'|snT:'CUSTOMER INFORMATION'}}</span><h1>{{'merchant.title'|snT:'Terms, payment and refunds'}}</h1><p>{{'merchant.subtitle'|snT:'Information about the seller and the provision of GuildConsole digital services.'}}</p></section>
<section class="grid">
 <article><h2>{{'merchant.seller'|snT:'Seller information'}}</h2><dl><div><dt>{{'merchant.business_name'|snT:'Business name'}}</dt><dd>{{c.business_name||'—'}}</dd></div><div><dt>{{'merchant.tax_id'|snT:'Registration / tax number'}}</dt><dd>{{c.tax_id||'—'}}</dd></div><div><dt>{{'merchant.legal_address'|snT:'Legal address'}}</dt><dd>{{c.legal_address||'—'}}</dd></div><div><dt>{{'merchant.actual_address'|snT:'Actual address'}}</dt><dd>{{c.actual_address||'—'}}</dd></div><div><dt>{{'merchant.phone'|snT:'Phone'}}</dt><dd>{{c.phone||'—'}}</dd></div><div><dt>Email</dt><dd>{{c.email||'—'}}</dd></div></dl></article>
 <article><h2>{{'merchant.service'|snT:'Service description'}}</h2><p>{{c.service_description}}</p></article>
 <article><h2>{{'merchant.fulfillment'|snT:'Provision and activation'}}</h2><p>{{c.service_terms}}</p></article>
 <article><h2>{{'merchant.payment'|snT:'Payment methods'}}</h2><p>{{c.payment_methods}}</p></article>
 <article><h2>{{'merchant.area'|snT:'Service territory'}}</h2><p>{{c.service_area}}</p></article>
 <article><h2>{{'merchant.refunds'|snT:'Refund policy'}}</h2><p>{{c.refund_policy}}</p></article>
 <article><h2>{{'merchant.cancellation'|snT:'Cancellation policy'}}</h2><p>{{c.cancellation_policy}}</p></article>
 <article class="wide"><h2>{{'merchant.offer'|snT:'Public offer and terms'}}</h2><p>{{c.public_offer}}</p></article>
 <article class="wide"><h2>{{'merchant.privacy'|snT:'Privacy policy'}}</h2><p>{{c.privacy_policy}}</p></article>
</section>
@if(auth.profile()?.is_superadmin){<section class="editor"><header><div><span>SUPERADMIN</span><h2>{{'merchant.editor'|snT:'Edit public information'}}</h2></div><button (click)="save()" [disabled]="saving()">{{saving()?('merchant.saving'|snT:'Saving…'):('merchant.save'|snT:'Save changes')}}</button></header>@if(message()){<p class="message">{{message()}}</p>}<div class="form-grid"><label>{{'merchant.business_name'|snT:'Business name'}}<input [(ngModel)]="c.business_name"></label><label>{{'merchant.tax_id'|snT:'Registration / tax number'}}<input [(ngModel)]="c.tax_id"></label><label>{{'merchant.legal_address'|snT:'Legal address'}}<input [(ngModel)]="c.legal_address"></label><label>{{'merchant.actual_address'|snT:'Actual address'}}<input [(ngModel)]="c.actual_address"></label><label>{{'merchant.phone'|snT:'Phone'}}<input [(ngModel)]="c.phone"></label><label>Email<input type="email" [(ngModel)]="c.email"></label></div><label>{{'merchant.service'|snT:'Service description'}}<textarea rows="4" [(ngModel)]="c.service_description"></textarea></label><label>{{'merchant.fulfillment'|snT:'Provision and activation'}}<textarea rows="4" [(ngModel)]="c.service_terms"></textarea></label><label>{{'merchant.payment'|snT:'Payment methods'}}<textarea rows="4" [(ngModel)]="c.payment_methods"></textarea></label><label>{{'merchant.area'|snT:'Service territory'}}<textarea rows="3" [(ngModel)]="c.service_area"></textarea></label><label>{{'merchant.refunds'|snT:'Refund policy'}}<textarea rows="6" [(ngModel)]="c.refund_policy"></textarea></label><label>{{'merchant.cancellation'|snT:'Cancellation policy'}}<textarea rows="5" [(ngModel)]="c.cancellation_policy"></textarea></label><label>{{'merchant.offer'|snT:'Public offer and terms'}}<textarea rows="8" [(ngModel)]="c.public_offer"></textarea></label><label>{{'merchant.privacy'|snT:'Privacy policy'}}<textarea rows="8" [(ngModel)]="c.privacy_policy"></textarea></label></section>}
}<footer>GuildConsole · LRM-IT</footer></main>`,styles:[`
.legal-page{min-height:100vh;padding:1.2rem clamp(1rem,4vw,4rem);background:var(--bg);color:var(--text)}.legal-page>header{max-width:1200px;margin:auto;display:flex;justify-content:space-between;align-items:center;padding:.8rem 0}.brand{color:var(--primary);font-weight:950;letter-spacing:.14em}.legal-page>header a:last-child{color:var(--muted);font-size:.75rem}.hero{max-width:1200px;margin:3rem auto 1.5rem}.hero span,.editor header span{color:var(--primary);font-size:.65rem;font-weight:900;letter-spacing:.15em}.hero h1{margin:.5rem 0;font-size:clamp(2rem,5vw,4rem)}.hero p{max-width:760px;color:var(--muted)}.grid{max-width:1200px;margin:auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.grid article,.editor,.state{padding:1.2rem;border:1px solid var(--line);border-radius:15px;background:var(--panel)}article h2{margin:0 0 .8rem;font-size:1.05rem}article p{white-space:pre-wrap;color:var(--muted);line-height:1.65}.wide{grid-column:1/-1}dl{display:grid;margin:0}dl div{display:grid;grid-template-columns:minmax(140px,.7fr) 1fr;gap:1rem;padding:.6rem 0;border-bottom:1px solid var(--line)}dt{color:var(--muted);font-size:.7rem}dd{margin:0;word-break:break-word}.editor{max-width:1158px;margin:1rem auto;display:grid;gap:1rem}.editor>header{display:flex;justify-content:space-between;align-items:center}.editor h2{margin:.3rem 0}.editor label{display:grid;gap:.4rem;color:var(--muted);font-size:.72rem}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}input,textarea{padding:.75rem;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text);font:inherit}textarea{resize:vertical}.editor button{padding:.75rem 1rem;border:0;border-radius:9px;background:var(--primary);color:#04130f;font-weight:900}.message{color:var(--success)}.state{max-width:1200px;margin:4rem auto}footer{max-width:1200px;margin:2rem auto;padding:1rem 0;color:var(--muted);border-top:1px solid var(--line)}@media(max-width:750px){.grid,.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}dl div{grid-template-columns:1fr}.editor>header{display:grid;gap:.8rem}}
`]})
export class MerchantInformationComponent implements OnInit{content=signal<MerchantContent|null>(null);loading=signal(true);saving=signal(false);message=signal('');constructor(private api:MerchantPageService,public auth:AuthService,private i18n:TranslationService){}async ngOnInit(){try{this.content.set(await this.api.get())}finally{this.loading.set(false)}}async save(){const value=this.content();if(!value||this.saving())return;this.saving.set(true);this.message.set('');try{this.content.set(await this.api.save(value));this.message.set(this.i18n.t('merchant.saved','Public information saved.'))}catch(e:any){this.message.set(e?.error?.detail||this.i18n.t('merchant.save_error','Unable to save public information.'))}finally{this.saving.set(false)}}}
