import {CommonModule} from '@angular/common';
import {Component,OnInit,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ShellComponent} from '../shared/shell.component';
import {UserLanguageService,WorkspaceLanguage} from '../core/user-language.service';
@Component({selector:'sn-my-languages',standalone:true,imports:[CommonModule,FormsModule,ShellComponent],template:`
<sn-shell title="My languages"><main class="page"><header><div><small>LANGUAGE WORKSPACE</small><h2>My languages</h2><p>Choose languages used in all plugin dropdowns on your servers.</p></div><button class="primary" (click)="save()" [disabled]="saving()">{{saving()?'Saving…':'Save'}}</button></header>
@if(error()){<div class="notice error">{{error()}}</div>} @if(success()){<div class="notice success">{{success()}}</div>}
<section class="toolbar"><input type="search" [(ngModel)]="query" placeholder="Search language, native name or code"><button (click)="popular()">Select popular</button><button (click)="clear()">Clear</button></section>
<section class="panel"><h3>Selected languages</h3>@for(l of selected();track l.code;let i=$index){<article class="row"><div class="identity"><b>{{l.flag||'🌐'}}</b><span><strong>{{l.name}}</strong><small>{{l.native_name}} · {{l.code}}</small></span></div><label><input type="checkbox" [(ngModel)]="l.enabled"> Enabled</label><label><input type="radio" name="primary" [checked]="l.is_primary" (change)="primary(l)"> Primary</label><label><input type="radio" name="fallback" [checked]="l.is_fallback" (change)="fallback(l)"> Fallback</label><div><button (click)="move(i,-1)" [disabled]="i===0">↑</button><button (click)="move(i,1)" [disabled]="i===selected().length-1">↓</button><button class="danger" (click)="remove(l)">Remove</button></div></article>}@empty{<p>No languages selected.</p>}</section>
<section class="panel"><h3>Global catalogue</h3><div class="catalog">@for(l of filtered();track l.code){<button class="card" (click)="add(l)" [disabled]="l.selected"><b>{{l.flag||'🌐'}}</b><span><strong>{{l.name}}</strong><small>{{l.native_name}} · {{l.code}}</small></span><em>{{l.selected?'Added':'+ Add'}}</em></button>}</div></section>
</main></sn-shell>`,styles:[`.page{display:grid;gap:1rem;padding:1rem}header,.toolbar,.row,.identity{display:flex;align-items:center;gap:.8rem}header{justify-content:space-between}h2,h3,p{margin:0}small{color:var(--muted)}input,button{font:inherit;border:1px solid var(--line);border-radius:8px;background:#081019;color:var(--text);padding:.7rem}.toolbar input{flex:1;min-width:280px}.panel,.notice{border:1px solid var(--line);border-radius:12px;background:var(--surface);padding:1rem}.panel{display:grid;gap:.65rem}.row{justify-content:space-between;border:1px solid var(--line);border-radius:10px;padding:.75rem}.identity{min-width:260px}.identity span{display:grid}.catalog{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem}.card{display:grid;grid-template-columns:34px 1fr auto;text-align:left;align-items:center}.card span{display:grid}.primary{background:var(--primary);color:#03130e}.danger,.error{color:#ff8290}.success{color:var(--success)}@media(max-width:900px){header,.row{align-items:flex-start;flex-direction:column}.catalog{grid-template-columns:1fr}}`]})
export class MyLanguagesComponent implements OnInit{
 private api=inject(UserLanguageService);languages=signal<WorkspaceLanguage[]>([]);saving=signal(false);error=signal('');success=signal('');query='';ngOnInit(){void this.load()}
 selected(){return this.languages().filter(x=>x.selected).sort((a,b)=>a.sort_order-b.sort_order)}
 filtered(){const q=this.query.trim().toLowerCase();return this.languages().filter(x=>!q||x.code.toLowerCase().includes(q)||x.name.toLowerCase().includes(q)||x.native_name.toLowerCase().includes(q))}
 add(l:WorkspaceLanguage){l.selected=true;l.enabled=true;l.sort_order=this.selected().length*10;if(this.selected().length===1){l.is_primary=true;l.is_fallback=true}this.touch()}
 remove(l:WorkspaceLanguage){const p=l.is_primary,f=l.is_fallback;Object.assign(l,{selected:false,enabled:false,is_primary:false,is_fallback:false});const r=this.selected();if(p&&r[0])r[0].is_primary=true;if(f&&r[0])r[0].is_fallback=true;this.reindex()}
 primary(l:WorkspaceLanguage){for(const x of this.languages())x.is_primary=x.code===l.code;l.enabled=true;this.touch()}
 fallback(l:WorkspaceLanguage){for(const x of this.languages())x.is_fallback=x.code===l.code;l.enabled=true;this.touch()}
 move(i:number,d:number){const a=this.selected(),t=i+d;if(t<0||t>=a.length)return;[a[i],a[t]]=[a[t],a[i]];a.forEach((x,n)=>x.sort_order=n*10);this.touch()}
 popular(){const p=new Set(['en','uk','ru','de','fr','es','it','pl']);for(const x of this.languages())if(p.has(x.code)){x.selected=true;x.enabled=true}const a=this.selected();if(!a.some(x=>x.is_primary)&&a[0])a[0].is_primary=true;if(!a.some(x=>x.is_fallback)&&a[0])a[0].is_fallback=true;this.reindex()}
 clear(){for(const x of this.languages())Object.assign(x,{selected:false,enabled:false,is_primary:false,is_fallback:false});this.touch()}
 async save(){const a=this.selected();if(!a.length){this.error.set('Select at least one language.');return}this.saving.set(true);this.error.set('');try{this.languages.set(await this.api.saveMine(a.map((x,i)=>({code:x.code,enabled:x.enabled,is_primary:x.is_primary,is_fallback:x.is_fallback,sort_order:i*10}))));this.success.set('Language set saved.')}catch(e:any){this.error.set(e?.error?.detail||'Unable to save languages.')}finally{this.saving.set(false)}}
 private async load(){try{this.languages.set(await this.api.listMine())}catch(e:any){this.error.set(e?.error?.detail||'Unable to load languages.')}}private reindex(){this.selected().forEach((x,i)=>x.sort_order=i*10);this.touch()}private touch(){this.languages.set([...this.languages()])}
}
