import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { PlatformOwner, PlatformUsersService } from '../core/platform-users.service';
import { TranslationService } from '../core/translation.service';
import { TranslatePipe } from '../core/translate.pipe';
import { ShellComponent } from '../shared/shell.component';

@Component({selector:'sn-platform-user-profile',standalone:true,imports:[CommonModule,FormsModule,RouterLink,ShellComponent,TranslatePipe],template:`
<sn-shell [title]="'platform_users.profile'|snT:'User profile'"><a class="back" routerLink="/platform/users">← {{'platform_users.back'|snT:'Back to users'}}</a>
@if(error()){<div class="notice error">{{error()}}</div>} @if(success()){<div class="notice success">{{success()}}</div>} @if(loading()){<div class="notice">{{'platform_users.loading_profile'|snT:'Loading profile…'}}</div>}
@if(owner();as user){<section class="profile"><header>@if(user.avatar_url){<img [src]="user.avatar_url" alt="">}@else{<span class="avatar">{{initial(user)}}</span>}<div><div class="eyebrow">{{'platform_users.server_owner'|snT:'SERVER OWNER'}}</div><h2>{{user.display_name||user.login}}</h2><p>{{user.email}}</p></div><span class="state">{{user.status}}</span></header><div class="facts"><div><small>Discord ID</small><strong>{{user.discord_user_id}}</strong></div><div><small>{{'platform_users.email_status'|snT:'Email status'}}</small><strong>{{user.email_verified?('platform_users.verified'|snT:'verified'):('platform_users.unverified'|snT:'not verified')}}</strong></div><div><small>{{'platform_users.locale'|snT:'Language'}}</small><strong>{{user.preferred_locale||'—'}}</strong></div><div><small>{{'platform_users.last_login'|snT:'Last login'}}</small><strong>{{user.last_login_at?(user.last_login_at|date:'medium'):('platform_users.never'|snT:'never')}}</strong></div><div><small>{{'platform_users.registered'|snT:'Registered'}}</small><strong>{{user.created_at|date:'mediumDate'}}</strong></div></div></section>
<section class="panel"><div class="eyebrow">{{'platform_users.servers'|snT:'Servers'}}</div><h3>{{'platform_users.owned_servers'|snT:'Owned Discord servers'}} ({{user.guilds.length}})</h3><div class="guilds">@for(guild of user.guilds;track guild.guild_id){<article>@if(guild.icon_url){<img [src]="guild.icon_url" alt="">}<div><strong>{{guild.name}}</strong><small>{{guild.guild_id}}</small><small>{{guildStatus(guild.status)}} · {{botStatus(guild.bot_status)}}</small></div>@if(guild.invite_url){<a class="invite-link" [href]="guild.invite_url" target="_blank" rel="noopener">{{'platform_users.join_server'|snT:'Join server'}} ↗</a>}@else{<span>{{'platform_users.invite_unavailable'|snT:'Invitation unavailable'}}</span>}</article>}</div></section>
<section class="panel"><div class="eyebrow">DISCORD DM</div><h3>{{'platform_users.contact_owner'|snT:'Contact server owner'}}</h3><p>{{'platform_users.dm_hint'|snT:'The bot will deliver this message directly to the owner.'}}</p><form (ngSubmit)="send(user)"><textarea name="message" [(ngModel)]="message" maxlength="2000" rows="6" required [placeholder]="'platform_users.message_placeholder'|snT:'Write a message to the server owner…'"></textarea><div><small>{{message.length}}/2000</small><button [disabled]="sending()||!message.trim()">{{sending()?('platform_users.sending'|snT:'Sending…'):('platform_users.queue'|snT:'Send message')}}</button></div></form></section>}
</sn-shell>`,styles:[`
.back{display:inline-block;margin-bottom:1rem;color:var(--primary);text-decoration:none;font-weight:800}.profile,.panel,.notice{border:1px solid var(--line);border-radius:18px;background:rgba(16,22,38,.72);padding:1.3rem}.notice{margin-bottom:1rem}.error{color:#ff9baa}.success{color:var(--primary)}header{display:flex;align-items:center;gap:1rem}header img,.avatar{width:76px;height:76px;border-radius:18px}header img{object-fit:cover}.avatar{display:grid;place-items:center;background:var(--primary-soft);color:var(--primary);font-size:1.8rem;font-weight:900}header div{flex:1}h2{margin:.25rem 0}p,small{color:var(--muted)}header p{margin:0}.eyebrow{color:var(--primary);font-size:.7rem;font-weight:900;letter-spacing:.14em}.state{padding:.45rem .7rem;border:1px solid var(--line);border-radius:999px;text-transform:uppercase;font-size:.7rem;color:var(--primary)}.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.7rem;margin-top:1.2rem}.facts div{display:grid;gap:.3rem;padding:.8rem;border:1px solid var(--line);border-radius:11px}.panel{margin-top:1rem}.panel h3{margin:.35rem 0}.guilds{display:grid;gap:.65rem;margin-top:1rem}.guilds article{display:flex;align-items:center;gap:.8rem;padding:.85rem;border:1px solid var(--line);border-radius:11px}.guilds img{width:42px;height:42px;border-radius:10px}.guilds div{display:grid;gap:.2rem;flex:1}.guilds>article>span{color:var(--muted);font-size:.75rem}.invite-link{padding:.55rem .7rem;border:1px solid rgba(53,226,178,.35);border-radius:9px;color:var(--primary);text-decoration:none;font-size:.75rem;font-weight:900}textarea,button{font:inherit}textarea{box-sizing:border-box;width:100%;padding:.8rem;border:1px solid var(--line);border-radius:11px;background:rgba(5,9,15,.75);color:var(--text)}form>div{display:flex;align-items:center;justify-content:flex-end;gap:1rem;margin-top:.6rem}form>div small{margin-right:auto}button{padding:.75rem 1rem;border:1px solid rgba(53,226,178,.4);border-radius:10px;background:var(--primary-soft);color:var(--primary);font-weight:900}button:disabled{opacity:.5}@media(max-width:650px){header{align-items:flex-start;flex-wrap:wrap}.state{margin-left:92px}.guilds article{align-items:flex-start;flex-wrap:wrap}.guilds>article>span{width:100%;margin-left:50px}}
`]})
export class PlatformUserProfileComponent implements OnInit{readonly owner=signal<PlatformOwner|null>(null);readonly loading=signal(true);readonly sending=signal(false);readonly error=signal('');readonly success=signal('');message='';constructor(private route:ActivatedRoute,private users:PlatformUsersService,private i18n:TranslationService){}ngOnInit(){void this.load();}async load(){try{this.owner.set(await firstValueFrom(this.users.get(this.route.snapshot.paramMap.get('userId')||'')));}catch(e:any){this.error.set(e?.error?.detail||e?.message||this.i18n.t('platform_users.load_error','Unable to load users.'));}finally{this.loading.set(false);}}initial(u:PlatformOwner){return(u.display_name||u.login||'?').charAt(0).toUpperCase();}guildStatus(value:string){if(value==='need_setup'||value==='active')return this.i18n.t('platform_users.status_active','Connected');if(value==='inactive')return this.i18n.t('platform_users.status_inactive','Not connected');return value;}botStatus(value:string){if(value==='online')return this.i18n.t('platform_users.bot_online','bot online');if(value==='offline')return this.i18n.t('platform_users.bot_offline','bot offline');return value;}async send(u:PlatformOwner){const m=this.message.trim();if(!m)return;this.sending.set(true);this.error.set('');this.success.set('');try{await firstValueFrom(this.users.sendDm(u.id,m));this.success.set(this.i18n.t('platform_users.queued','Message queued for delivery through Discord.'));this.message='';}catch(e:any){this.error.set(e?.error?.detail||e?.message||this.i18n.t('platform_users.send_error','Unable to send the message.'));}finally{this.sending.set(false);}}}
