import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { PlatformOwner, PlatformUsersService } from '../core/platform-users.service';
import { TranslationService } from '../core/translation.service';
import { TranslatePipe } from '../core/translate.pipe';
import { ShellComponent } from '../shared/shell.component';

@Component({selector:'sn-platform-users',standalone:true,imports:[CommonModule,FormsModule,RouterLink,ShellComponent,TranslatePipe],template:`
<sn-shell [title]="'platform_users.title'|snT:'Server owners'">
  <section class="toolbar"><div><div class="eyebrow">{{'platform_users.eyebrow'|snT:'PANEL USERS'}}</div><h2>{{'platform_users.heading'|snT:'Discord server owners'}}</h2><p>{{'platform_users.list_intro'|snT:'Open a user profile to view servers and send a message.'}}</p></div><form (ngSubmit)="load()"><input name="search" [(ngModel)]="search" [placeholder]="'platform_users.search'|snT:'Search by name, email or Discord ID'"><button>{{'platform_users.search_button'|snT:'Search'}}</button></form></section>
  @if(error()){<div class="notice error">{{error()}}</div>} @if(loading()){<div class="notice">{{'platform_users.loading'|snT:'Loading server owners…'}}</div>} @if(!loading()&&!owners().length){<div class="notice">{{'platform_users.empty'|snT:'No server owners found.'}}</div>}
  @if(owners().length){<section class="list"><div class="head"><span>{{'platform_users.user'|snT:'User'}}</span><span>Discord ID</span><span>{{'platform_users.servers'|snT:'Servers'}}</span><span>{{'platform_users.last_login'|snT:'Last login'}}</span><span></span></div>
  @for(owner of owners();track owner.id){<a class="row" [routerLink]="['/platform/users',owner.id]"><span class="user">@if(owner.avatar_url){<img [src]="owner.avatar_url" alt="">}@else{<i>{{initial(owner)}}</i>}<span><strong>{{owner.display_name||owner.login}}</strong><small>{{owner.email}}</small></span></span><span class="discord">{{owner.discord_user_id}}</span><span><b>{{owner.guilds.length}}</b></span><span>{{owner.last_login_at?(owner.last_login_at|date:'medium'):('platform_users.never'|snT:'never')}}</span><span class="open">{{'platform_users.open_profile'|snT:'Open profile'}} →</span></a>}</section>}
</sn-shell>`,styles:[`
.toolbar,.notice,.list{border:1px solid var(--line);border-radius:18px;background:rgba(16,22,38,.72)}.toolbar{padding:1.3rem;display:flex;align-items:end;justify-content:space-between;gap:1rem}.toolbar h2{margin:.3rem 0}.toolbar p,small,.head{color:var(--muted)}.eyebrow{color:var(--primary);font-size:.7rem;font-weight:900;letter-spacing:.14em}.toolbar form{display:flex;gap:.5rem;width:min(520px,100%)}input,button{font:inherit}input{box-sizing:border-box;width:100%;padding:.75rem;border:1px solid var(--line);border-radius:10px;background:rgba(5,9,15,.75);color:var(--text)}button{padding:.72rem 1rem;border:1px solid var(--line);border-radius:10px;background:var(--primary-soft);color:var(--primary);font-weight:800}.notice{padding:1rem;margin-top:1rem}.error{color:#ff9baa}.list{overflow:auto;margin-top:1rem}.head,.row{display:grid;grid-template-columns:minmax(260px,2fr) minmax(180px,1fr) 90px minmax(170px,1fr) 130px;gap:1rem;align-items:center;padding:.85rem 1rem;min-width:900px}.head{font-size:.67rem;font-weight:800;text-transform:uppercase;border-bottom:1px solid var(--line)}.row{color:var(--text);text-decoration:none;border-bottom:1px solid var(--line);transition:.15s}.row:last-child{border-bottom:0}.row:hover{background:var(--primary-soft)}.user{display:flex;align-items:center;gap:.8rem;min-width:0}.user img,.user i{width:42px;height:42px;border-radius:11px}.user img{object-fit:cover}.user i{display:grid;place-items:center;background:var(--primary-soft);color:var(--primary);font-style:normal;font-weight:900}.user>span{display:grid;gap:.15rem;min-width:0}.discord{font-family:monospace}.open{color:var(--primary);font-weight:800;font-size:.78rem}@media(max-width:760px){.toolbar{align-items:stretch;flex-direction:column}.toolbar form{width:100%}}
`]})
export class PlatformUsersComponent implements OnInit{readonly owners=signal<PlatformOwner[]>([]);readonly loading=signal(false);readonly error=signal('');search='';constructor(private users:PlatformUsersService,private i18n:TranslationService){}ngOnInit(){void this.load();}async load(){this.loading.set(true);this.error.set('');try{this.owners.set((await firstValueFrom(this.users.list(this.search.trim()))).items);}catch(e:any){this.error.set(e?.error?.detail||e?.message||this.i18n.t('platform_users.load_error','Unable to load users.'));}finally{this.loading.set(false);}}initial(o:PlatformOwner){return(o.display_name||o.login||'?').charAt(0).toUpperCase();}}
