import {DatePipe} from '@angular/common';
import {Component,OnInit,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {RouterLink} from '@angular/router';
import {EnterpriseDashboardOverview,EnterpriseDashboardService} from '../core/enterprise-dashboard.service';
import {ModalService} from '../core/modal.service';
import {TranslatePipe} from '../core/translate.pipe';
import {TranslationService} from '../core/translation.service';
import {ShellComponent} from '../shared/shell.component';

type PlatformGuild=EnterpriseDashboardOverview['guilds'][number];

@Component({standalone:true,imports:[DatePipe,FormsModule,RouterLink,ShellComponent,TranslatePipe],template:`
<sn-shell [title]="'platform_servers.title'|snT:'All Discord servers'">
<header class="head"><div><span>PLATFORM / DISCORD ESTATE</span><h2>{{'platform_servers.heading'|snT:'Server registry'}}</h2><p>{{'platform_servers.help'|snT:'All Discord servers known to GuildConsole, including disconnected and removed records.'}}</p></div><button (click)="load()" [disabled]="loading()">{{'dashboard.refresh'|snT:'Refresh'}}</button></header>
@if(error()){<div class="notice">{{error()}}</div>}
<section class="filters"><input [(ngModel)]="query" (ngModelChange)="touch()" [placeholder]="'platform_servers.search'|snT:'Search name or server ID'"><select [(ngModel)]="filter" (ngModelChange)="touch()"><option value="all">{{'platform_servers.all_states'|snT:'All states'}}</option><option value="connected">{{'platform_servers.connected'|snT:'Connected'}}</option><option value="offline">{{'platform_servers.offline'|snT:'Offline'}}</option><option value="removed">{{'platform_servers.removed'|snT:'Removed'}}</option><option value="stale">{{'platform_servers.stale'|snT:'Stale'}}</option></select><strong>{{visible().length}} / {{guilds().length}}</strong></section>
<section class="table"><div class="row header"><span>{{'platform_servers.server'|snT:'Server'}}</span><span>{{'platform_servers.record'|snT:'Record'}}</span><span>{{'platform_servers.connection'|snT:'Connection'}}</span><span>{{'platform_servers.sync'|snT:'Synchronization'}}</span><span>{{'platform_servers.members'|snT:'Members'}}</span><span>{{'platform_servers.plugins'|snT:'Plugins'}}</span><span></span></div>@for(g of visible();track g.guild_id){<article class="row"><div class="identity">@if(g.icon_url){<img [src]="g.icon_url" alt="">}@else{<i>{{g.name.slice(0,1)}}</i>}<span><b>{{g.name}}</b><small>{{g.guild_id}}</small></span></div><span class="badge" [class.bad]="g.status==='left'||g.status==='removed'">{{status(g.status)}}</span><span class="badge" [class.ok]="g.bot_status==='online'">{{g.bot_status==='online'?('platform_servers.connected'|snT:'Connected'):('platform_servers.offline'|snT:'Offline')}}</span><span><b>{{sync(g.sync_status)}}</b><small>{{g.last_sync_at?(g.last_sync_at|date:'short'):('server_cards.never'|snT:'Never')}}</small></span><b>{{g.member_count}}</b><b>{{g.enabled_plugins}}</b><div class="actions">@if(g.bot_status==='online'){<a [routerLink]="['/guild',g.guild_id]">{{'platform_servers.open'|snT:'Open'}}</a>}<button (click)="remove(g)">{{'ui.delete'|snT:'Delete'}}</button></div></article>}@empty{<p class="empty">{{'platform_servers.empty'|snT:'No servers match the selected filter.'}}</p>}</section>
</sn-shell>`,styles:[`:host{display:block}.head{display:flex;justify-content:space-between;gap:1rem;align-items:start;margin:1rem 0}.head span{color:var(--accent);font-size:.68rem;font-weight:900;letter-spacing:.14em}.head h2{margin:.35rem 0}.head p{margin:0;color:var(--muted)}button,input,select{padding:.7rem;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text)}button{cursor:pointer}.notice{padding:1rem;border-radius:12px;background:rgba(255,90,110,.08);color:#ff8d96}.filters{display:grid;grid-template-columns:minmax(240px,1fr) 220px auto;gap:.7rem;align-items:center;margin:1rem 0}.table{overflow:auto;border:1px solid var(--line);border-radius:15px;background:var(--panel)}.row{min-width:1050px;display:grid;grid-template-columns:minmax(260px,1.5fr) 120px 130px 170px 80px 70px 180px;gap:.8rem;align-items:center;padding:.85rem 1rem;border-top:1px solid var(--line)}.row.header{border-top:0;color:var(--muted);font-size:.68rem;text-transform:uppercase;letter-spacing:.07em}.identity{display:flex;align-items:center;gap:.7rem}.identity img,.identity i{width:38px;height:38px;border-radius:10px}.identity img{object-fit:cover}.identity i{display:grid;place-items:center;background:rgba(53,226,178,.12);color:var(--accent);font-style:normal;font-weight:900}.identity span,.row>span:not(.badge){display:grid}.row small{color:var(--muted)}.badge{width:max-content;padding:.25rem .45rem;border-radius:6px;background:rgba(240,169,75,.12);color:#f0a94b;font-size:.68rem;text-transform:uppercase}.badge.ok{background:rgba(53,226,178,.1);color:var(--accent)}.badge.bad{background:rgba(255,90,110,.1);color:#ff7379}.actions{display:flex;gap:.4rem}.actions a,.actions button{padding:.5rem .65rem;border:1px solid var(--line);border-radius:8px;color:var(--text);text-decoration:none;background:transparent}.actions button{color:#ff7379}.empty{padding:2rem;color:var(--muted)}@media(max-width:700px){.head,.filters{grid-template-columns:1fr;display:grid}}`]})
export class PlatformServersComponent implements OnInit{
 private api=inject(EnterpriseDashboardService);private modal=inject(ModalService);private i18n=inject(TranslationService);guilds=signal<PlatformGuild[]>([]);loading=signal(false);error=signal('');query='';filter='all';revision=signal(0);
 visible=computed(()=>{this.revision();const q=this.query.trim().toLowerCase();return this.guilds().filter(g=>(!q||g.name.toLowerCase().includes(q)||g.guild_id.includes(q))&&(this.filter==='all'||this.filter==='connected'&&g.bot_status==='online'||this.filter==='offline'&&g.bot_status!=='online'||this.filter==='removed'&&['left','removed'].includes(g.status)||this.filter==='stale'&&g.sync_status==='stale'))});
 ngOnInit(){void this.load()}touch(){this.revision.update(v=>v+1)}
 async load(){this.loading.set(true);this.error.set('');try{this.guilds.set((await this.api.overview()).guilds)}catch(e:any){this.error.set(e?.error?.detail||'Unable to load servers.')}finally{this.loading.set(false)}}
 status(value:string){return value==='active'?'ACTIVE':value==='left'||value==='removed'?'REMOVED':value.toUpperCase()}
 sync(value:string){return value==='fresh'?'FRESH':value==='stale'?'STALE':'NEVER'}
 async remove(g:PlatformGuild){const confirmation=await this.modal.prompt(this.i18n.t('platform_servers.type_id_confirm','To permanently delete {name} and all saved settings, enter the server ID: {id}').replace('{name}',g.name).replace('{id}',g.guild_id),'',{title:this.i18n.t('platform_servers.delete_title','Delete server record'),confirmLabel:this.i18n.t('platform_servers.delete_record','Delete permanently'),cancelLabel:this.i18n.t('ui.cancel','Cancel'),danger:true,required:true,matchValue:g.guild_id});if(confirmation===null)return;try{await this.api.removeGuild(g.guild_id);this.guilds.update(items=>items.filter(x=>x.guild_id!==g.guild_id))}catch(e:any){this.error.set(e?.error?.detail||this.i18n.t('platform_servers.delete_error','Unable to delete the server.'))}}
}
