import{PercentPipe}from'@angular/common';import{Component,OnInit,inject,signal}from'@angular/core';import{FormsModule}from'@angular/forms';import{HttpClient}from'@angular/common/http';import{ActivatedRoute,RouterLink}from'@angular/router';import{firstValueFrom}from'rxjs';import{ShellComponent}from'../shared/shell.component';import{GuildPluginService}from'../core/guild-plugin.service';
interface Item{id:string;name:string;type?:string;managed?:boolean}
@Component({standalone:true,imports:[FormsModule,PercentPipe,ShellComponent,RouterLink],template:`
<sn-shell title="AI AutoMod"><main class="page"><header><span>GUILD PLUGIN</span><h2>AI AutoMod</h2><p>Analyze messages through the server AI Center and send violations to Moderation.</p></header>
@if(error()){<div class="notice error">{{error()}}</div>}@if(success()){<div class="notice success">{{success()}}</div>}
@if(!settings.installed){<section class="card"><p>Install Moderation first, then install AI AutoMod.</p><button (click)="install()">Install plugin</button></section>}@else{
<section class="card heading"><div><h3>Runtime</h3><p>AI Center must have an enabled <strong>moderation</strong> route.</p></div><div class="actions"><a routerLink="/guild/{{guildId}}/ai">AI Center</a><button class="secondary" (click)="toggle()">{{settings.enabled?'Disable':'Enable'}} plugin</button></div></section>
<section class="card form"><h3>Detection</h3><div class="grid"><label>Channels<select [(ngModel)]="settings.channel_mode"><option value="all">All channels</option><option value="selected">Only selected channels</option></select></label><label>Confidence threshold<input type="number" min="0.5" max="1" step="0.01" [(ngModel)]="settings.threshold"><small>{{settings.threshold|percent}}</small></label></div>
@if(settings.channel_mode==='selected'){<label>Analyze channels<select multiple [(ngModel)]="settings.channel_ids">@for(c of channels();track c.id){<option [value]="c.id">#{{c.name}}</option>}</select></label>}
<div class="grid"><label>Excluded channels<select multiple [(ngModel)]="settings.excluded_channel_ids">@for(c of channels();track c.id){<option [value]="c.id">#{{c.name}}</option>}</select></label><label>Ignored roles<select multiple [(ngModel)]="settings.ignored_role_ids">@for(r of roles();track r.id){<option [value]="r.id">{{r.name}}</option>}</select></label></div>
<label>Categories<div class="checks">@for(item of categoryOptions;track item.code){<label class="check"><input type="checkbox" [checked]="hasCategory(item.code)" (change)="toggleCategory(item.code)">{{item.name}}</label>}</div></label></section>
<section class="card form"><h3>Actions</h3><div class="checks"><label class="check"><input type="checkbox" [(ngModel)]="settings.delete_message">Delete message</label><label class="check"><input type="checkbox" [(ngModel)]="settings.warn_member">Warn member</label><label class="check"><input type="checkbox" [(ngModel)]="settings.create_case">Create Moderation case</label></div><div class="grid"><label>Timeout, minutes<input type="number" min="0" max="40320" [(ngModel)]="settings.timeout_minutes"><small>0 disables timeout.</small></label><label>Moderation log channel<select [(ngModel)]="settings.log_channel_id"><option [ngValue]="null">Do not post</option>@for(c of channels();track c.id){<option [value]="c.id">#{{c.name}}</option>}</select></label></div><label>Warning text<textarea rows="3" maxlength="1000" [(ngModel)]="settings.warning_text"></textarea><small>Variable: &#123;reason&#125;</small></label></section>
<button class="save" (click)="save()" [disabled]="busy()">Save settings</button>}
</main></sn-shell>`,styles:[`.page{max-width:1000px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}header span{color:var(--primary);font-size:.7rem;font-weight:800;letter-spacing:.12em}h2{margin:.3rem 0;font-size:1.8rem}h3,p{margin:.25rem 0}p,small{color:var(--muted)}.card,.notice{padding:1.2rem;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.heading,.actions{display:flex;align-items:center;justify-content:space-between;gap:1rem}.form{display:grid;gap:1rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}label{display:grid;gap:.4rem;color:var(--muted)}input,select,textarea{width:100%;padding:.75rem;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text);font:inherit}select[multiple]{min-height:140px}.checks{display:flex;gap:1rem;flex-wrap:wrap}.check{display:flex;align-items:center;color:var(--text)}.check input{width:auto}button,.actions a{padding:.72rem 1rem;border:0;border-radius:9px;background:var(--primary);color:#07120f;font-weight:800;text-decoration:none}.secondary{background:transparent;color:var(--text);border:1px solid var(--line)}.save{justify-self:end}.error{color:#ff9ea3}.success{color:#76e8b8}@media(max-width:700px){.grid{grid-template-columns:1fr}.heading{align-items:flex-start;flex-direction:column}}`]})
export class PluginAIAutoModComponent implements OnInit{private http=inject(HttpClient);private route=inject(ActivatedRoute);private plugins=inject(GuildPluginService);guildId=this.route.snapshot.paramMap.get('guildId')||'';busy=signal(false);error=signal('');success=signal('');channels=signal<Item[]>([]);roles=signal<Item[]>([]);settings:any={installed:false,enabled:false};categoryOptions=[{code:'harassment',name:'Harassment'},{code:'hate',name:'Hate'},{code:'threats',name:'Threats'},{code:'sexual',name:'Sexual content'},{code:'self-harm',name:'Self-harm'},{code:'spam',name:'Spam'},{code:'scam',name:'Scam'}];private get url(){return`/api/v1/discord/guilds/${this.guildId}/plugins/ai-automod`}
async ngOnInit(){try{const[s,structure]=await Promise.all([firstValueFrom(this.http.get<any>(`${this.url}/settings`)),firstValueFrom(this.http.get<any>(`/api/v1/discord/guilds/${this.guildId}/structure`))]);this.settings=s;this.channels.set((structure.channels||[]).filter((x:any)=>['text','0','guild_text'].includes(String(x.type).toLowerCase())));this.roles.set((structure.roles||[]).filter((x:any)=>!x.managed&&x.name!=='@everyone'))}catch(e:any){this.error.set(e?.error?.detail||'Could not load AI AutoMod.')}}
hasCategory(code:string){return(this.settings.categories||[]).includes(code)}toggleCategory(code:string){const values=new Set(this.settings.categories||[]);values.has(code)?values.delete(code):values.add(code);this.settings.categories=[...values]}
async install(){this.busy.set(true);try{await this.plugins.install(this.guildId,'ai_automod');await this.ngOnInit()}catch(e:any){this.error.set(e?.error?.detail||'Could not install AI AutoMod.')}finally{this.busy.set(false)}}async toggle(){this.busy.set(true);try{this.settings.enabled?await this.plugins.disable(this.guildId,'ai_automod'):await this.plugins.enable(this.guildId,'ai_automod');await this.ngOnInit()}catch(e:any){this.error.set(e?.error?.detail||'Could not change plugin state.')}finally{this.busy.set(false)}}async save(){this.busy.set(true);this.error.set('');const{installed,enabled,...payload}=this.settings;try{this.settings=await firstValueFrom(this.http.put<any>(`${this.url}/settings`,payload));this.success.set('AI AutoMod settings saved.')}catch(e:any){this.error.set(e?.error?.detail||'Could not save settings.')}finally{this.busy.set(false)}}}
