import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { ShellComponent } from '../shared/shell.component';
import { DiscordChannelPickerComponent } from '../shared/discord-channel-picker.component';
import { GuildPluginService } from '../core/guild-plugin.service';

@Component({standalone:true,imports:[FormsModule,DatePipe,ShellComponent,DiscordChannelPickerComponent],template:`
<sn-shell title="Event Manager"><main class="page">
<header><span>GUILD PLUGIN</span><h2>Event Manager</h2><p>Schedule events, collect RSVPs and notify participants.</p></header>
@if(error()){<div class="notice error">{{error()}}</div>}@if(success()){<div class="notice success">{{success()}}</div>}
@if(!settings.installed){<section class="card"><button (click)="install()">Install plugin</button></section>}@else{
<section class="card heading"><div><h3>Events</h3><p>Times are shown in each Discord member's local timezone.</p></div><button (click)="add()">Add event</button></section>
@for(event of settings.events;track event.id;let i=$index){<article class="card event">
<button class="summary" (click)="event.expanded=!event.expanded"><span><strong>{{event.title}}</strong><small>{{event.starts_at|date:'medium'}} · {{count(event,'going')}} going</small></span><b [class.open]="event.expanded">⌄</b></button>
@if(event.expanded){<div class="body">
<div class="grid"><label class="field"><span>Internal name</span><input [(ngModel)]="event.name" maxlength="80"><small>Only visible in GuildConsole.</small></label><label class="field"><span>Discord title</span><input [(ngModel)]="event.title" maxlength="100"><small>Shown in the published event.</small></label></div>
<label class="field"><span>Description</span><textarea [(ngModel)]="event.description" rows="3" maxlength="2000"></textarea><small>Event details displayed to participants.</small></label>
<div class="grid"><label class="field"><span>Channel</span><sn-discord-channel-picker [guildId]="guildId" [value]="event.channel_id" (valueChange)="event.channel_id=$event"/><small>Channel where the event will be published.</small></label><label class="field"><span>Starts at</span><input type="datetime-local" [(ngModel)]="event.local_start"><small>Uses your current local timezone.</small></label></div>
<div class="grid three"><label class="field"><span>Participant limit</span><input type="number" min="0" [(ngModel)]="event.max_participants"><small>0 means unlimited.</small></label><label class="field"><span>Reminder, minutes</span><input type="number" min="0" [(ngModel)]="event.reminder_minutes"><small>0 disables the reminder.</small></label><div class="field status-field"><span>Event status</span><label class="enabled-card"><input type="checkbox" [(ngModel)]="event.enabled"><span><strong>Event enabled</strong><small>Allow publishing and reminders.</small></span></label></div></div>
<div class="stats"><span>✅ {{count(event,'going')}} going</span><span>❔ {{count(event,'maybe')}} maybe</span><span>✖ {{count(event,'declined')}} declined</span></div>
<footer><button class="danger" (click)="settings.events.splice(i,1)">Delete</button><i></i><button class="secondary" (click)="save()">Save</button><button (click)="publish(event)" [disabled]="!settings.enabled||!event.enabled">Save and publish</button></footer>
</div>}</article>}@empty{<section class="card empty">No events yet.</section>}<button class="save" (click)="save()">Save all</button>}
</main></sn-shell>`,styles:[`
.page{max-width:1150px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}header span{color:var(--primary);font-size:.7rem;font-weight:800;letter-spacing:.12em}h2{margin:.3rem 0;font-size:1.8rem}h3,p{margin:.2rem 0}p,small{color:var(--muted)}
.card,.notice{padding:1.2rem;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.heading,footer{display:flex;justify-content:space-between;align-items:center;gap:.7rem}.event{padding:0;overflow:hidden}
.summary{width:100%;min-height:68px;display:flex;justify-content:space-between;align-items:center;text-align:left;padding:1rem 1.2rem;background:transparent;color:var(--text);border:0}.summary span{display:grid;gap:.25rem;min-width:0}.summary strong,.summary small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.summary b{font-size:1.5rem;transition:transform .18s}.summary b.open{transform:rotate(180deg)}
.body{padding:1.2rem;border-top:1px solid var(--line);display:grid;gap:1.15rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;align-items:start}.three{grid-template-columns:repeat(3,minmax(0,1fr))}
.field{display:grid;grid-template-rows:1.2rem 52px auto;align-content:start;gap:.45rem;min-width:0;color:var(--muted);font-size:.78rem;font-weight:650}.field:has(textarea){grid-template-rows:1.2rem auto auto}.field>span{line-height:1.2}.field small{min-height:1rem;font-size:.68rem;line-height:1.4}
input:not([type=checkbox]),textarea{box-sizing:border-box;width:100%;height:52px;min-height:52px;padding:.72rem .8rem;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text);font:inherit;outline:none}.field sn-discord-channel-picker{height:52px}textarea{height:auto;min-height:104px;resize:vertical;line-height:1.5}input:not([type=checkbox]):focus,textarea:focus{border-color:var(--primary);box-shadow:0 0 0 2px var(--primary-soft)}
.status-field{grid-template-rows:1.2rem 52px auto}.enabled-card{box-sizing:border-box;height:52px;min-height:52px;margin:0;padding:.65rem .8rem;display:flex;align-items:center;gap:.7rem;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text);cursor:pointer}.enabled-card input{flex:0 0 18px;width:18px;height:18px;margin:0;accent-color:var(--primary)}.enabled-card span{display:grid;gap:.08rem;min-width:0}.enabled-card strong{font-size:.78rem}.enabled-card small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.65rem;line-height:1.25}
button{min-height:44px;padding:.7rem 1rem;border:0;border-radius:9px;background:var(--primary);color:#07120f;font-weight:800;cursor:pointer}button:disabled{cursor:not-allowed;opacity:.5}.secondary,.danger{background:transparent;color:var(--text);border:1px solid var(--line)}.danger{color:#ff9ea3}footer i{flex:1}
.stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.6rem}.stats span{min-height:42px;display:flex;align-items:center;justify-content:center;padding:.45rem .65rem;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--muted);font-size:.75rem;text-align:center}.save{justify-self:end;min-width:170px}.error{color:#ff9ea3}.success{color:#76e8b8}.empty{text-align:center;color:var(--muted)}
@media(max-width:900px){.three{grid-template-columns:repeat(2,minmax(0,1fr))}.status-field{grid-column:1/-1}}
@media(max-width:760px){.grid,.three{grid-template-columns:1fr}.status-field{grid-column:auto}.heading{align-items:stretch;flex-direction:column}.heading button,.save{width:100%}footer{align-items:stretch;flex-direction:column}footer i{display:none}.stats{grid-template-columns:1fr}.field{grid-template-rows:auto 52px auto}.field:has(textarea){grid-template-rows:auto auto auto}}
`]})
export class PluginEventManagerComponent implements OnInit{
private http=inject(HttpClient);private route=inject(ActivatedRoute);private plugins=inject(GuildPluginService);guildId=this.route.snapshot.paramMap.get('guildId')||'';settings:any={installed:false,enabled:false,events:[]};error=signal('');success=signal('');private get url(){return`/api/v1/discord/guilds/${this.guildId}/plugins/event-manager`}
async ngOnInit(){try{const s=await firstValueFrom(this.http.get<any>(`${this.url}/settings`));this.settings={...s,events:(s.events||[]).map((x:any)=>({...x,expanded:false,local_start:this.local(x.starts_at)}))}}catch(e:any){this.error.set(e?.error?.detail||'Could not load events.')}}
local(v:string){if(!v)return'';const d=new Date(v),p=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
add(){this.settings.events.push({id:`event-${Date.now().toString(36)}`,name:'New event',title:'New event',description:'',channel_id:null,local_start:'',max_participants:0,reminder_minutes:30,enabled:true,participants:{},expanded:true})}count(e:any,s:string){return Object.values(e.participants||{}).filter(x=>x===s).length}payload(){return{events:this.settings.events.map(({expanded,local_start,message_id,participants,reminded_at,...e}:any)=>({...e,starts_at:new Date(local_start).toISOString()}))}}
async install(){try{await this.plugins.install(this.guildId,'event_manager');await this.ngOnInit()}catch(e:any){this.error.set(e?.error?.detail||'Install failed.')}}async toggle(){try{this.settings.enabled?await this.plugins.disable(this.guildId,'event_manager'):await this.plugins.enable(this.guildId,'event_manager');await this.ngOnInit()}catch(e:any){this.error.set(e?.error?.detail||'State change failed.')}}async save(){this.error.set('');try{const s=await firstValueFrom(this.http.put<any>(`${this.url}/settings`,this.payload()));this.settings={...s,events:s.events.map((x:any)=>({...x,expanded:true,local_start:this.local(x.starts_at)}))};this.success.set('Events saved.')}catch(e:any){this.error.set(e?.error?.detail||'Save failed.')}}async publish(e:any){await this.save();if(this.error())return;try{const r=await firstValueFrom(this.http.post<any>(`${this.url}/publish`,{event_id:e.id}));for(let i=0;i<30;i++){await new Promise(x=>setTimeout(x,1000));const j=await firstValueFrom(this.http.get<any>(`${this.url}/jobs/${r.job_id}`));if(j.status==='completed'){this.success.set('Event published.');return}if(j.status==='failed')throw new Error(j.error)}}catch(x:any){this.error.set(x?.message||'Publish failed.')}}}
