import {Component,OnInit,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {HttpClient} from '@angular/common/http';
import {ActivatedRoute} from '@angular/router';
import {firstValueFrom} from 'rxjs';
import {ShellComponent} from '../shared/shell.component';
import {DiscordChannelPickerComponent} from '../shared/discord-channel-picker.component';
import {GuildPluginService} from '../core/guild-plugin.service';

@Component({standalone:true,imports:[FormsModule,ShellComponent,DiscordChannelPickerComponent],template:`
<sn-shell title="War Planner"><main class="page">
 <header><span>GUILD PLUGIN</span><h2>War Planner</h2><p>Plan war waves, targets and participant assignments.</p></header>
 @if(error()){<div class="notice error">{{error()}}</div>} @if(success()){<div class="notice success">{{success()}}</div>}
 @if(!settings.installed){<section class="card"><button (click)="install()">Install plugin</button></section>}@else{
 <section class="card heading"><div><h3>War plans</h3><p>Publish one live coordination panel per plan.</p></div><div><button class="secondary" (click)="toggle()">{{settings.enabled?'Disable':'Enable'}} plugin</button><button (click)="addWar()">Add war</button></div></section>
 @for(war of settings.wars;track war.id;let wi=$index){<article class="card plan"><button class="summary" (click)="war.expanded=!war.expanded"><span><strong>{{war.title}}</strong><small>{{war.opponent||'No opponent'}} · {{assigned(war)}} assigned · {{war.waves.length}} waves</small></span><b [class.open]="war.expanded">⌄</b></button>
 @if(war.expanded){<div class="body"><div class="grid"><label>Internal name<input [(ngModel)]="war.name" maxlength="80"></label><label>Discord title<input [(ngModel)]="war.title" maxlength="100"></label></div><div class="grid"><label>Opponent<input [(ngModel)]="war.opponent" maxlength="100"></label><label>Channel<sn-discord-channel-picker [guildId]="guildId" [value]="war.channel_id" (valueChange)="war.channel_id=$event"/></label></div><label>Description<textarea [(ngModel)]="war.description" rows="3"></textarea></label>
 <div class="wave-head"><h3>Waves</h3><button (click)="addWave(war)">Add wave</button></div>
 @for(wave of war.waves;track wave.id;let i=$index){<section class="wave"><div class="grid three"><label>Name<input [(ngModel)]="wave.name"></label><label>Starts at<input type="datetime-local" [(ngModel)]="wave.local_start"></label><label>Capacity<input type="number" min="0" [(ngModel)]="wave.capacity"><small>0 = unlimited</small></label></div><label>Targets / instructions<textarea [(ngModel)]="wave.targets" rows="2"></textarea></label><footer><span>{{waveCount(war,wave.id)}} assigned</span><i></i><button class="danger" (click)="war.waves.splice(i,1)">Delete wave</button></footer></section>}
 <footer><button class="danger" (click)="settings.wars.splice(wi,1)">Delete plan</button><label class="check"><input type="checkbox" [(ngModel)]="war.enabled"> Enabled</label><i></i><button class="secondary" (click)="save()">Save</button><button (click)="publish(war)" [disabled]="!settings.enabled||!war.enabled||!war.waves.length">Save and publish</button></footer></div>}</article>}
 @empty{<section class="card empty">No war plans yet.</section>}<button class="save" (click)="save()">Save all</button>}
</main></sn-shell>`,styles:[`
.page{max-width:1080px;margin:auto;display:grid;gap:1rem;padding-bottom:3rem}header span{color:var(--primary);font-size:.7rem;font-weight:800;letter-spacing:.12em}h2,h3,p{margin:.25rem 0}p,small{color:var(--muted)}.card,.notice{padding:1.2rem;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.heading,.heading>div:last-child,footer,.wave-head{display:flex;justify-content:space-between;align-items:center;gap:.7rem}.plan{padding:0;overflow:hidden}.summary{width:100%;display:flex;justify-content:space-between;text-align:left;padding:1rem 1.2rem;background:transparent;color:var(--text);border:0}.summary span{display:grid}.summary b{font-size:1.5rem}.summary b.open{transform:rotate(180deg)}.body{padding:1.2rem;border-top:1px solid var(--line);display:grid;gap:1rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.three{grid-template-columns:1fr 1fr 1fr}.wave{display:grid;gap:.8rem;padding:1rem;border:1px solid var(--line);border-radius:12px;background:var(--panel-2)}label{display:grid;gap:.35rem;color:var(--muted)}.check{display:flex;align-items:center}.check input{width:auto}input,textarea{padding:.75rem;border:1px solid var(--line);border-radius:9px;background:var(--panel-2);color:var(--text)}.wave input,.wave textarea{background:var(--panel)}button{padding:.7rem 1rem;border:0;border-radius:9px;background:var(--primary);color:#07120f;font-weight:800}.secondary,.danger{background:transparent;color:var(--text);border:1px solid var(--line)}.danger{color:#ff9ea3}footer i{flex:1}.save{justify-self:end}.error{color:#ff9ea3}.success{color:#76e8b8}.empty{text-align:center;color:var(--muted)}@media(max-width:700px){.grid,.three{grid-template-columns:1fr}.heading{align-items:flex-start;flex-direction:column}footer{flex-wrap:wrap}}
`]})
export class PluginWarPlannerComponent implements OnInit{
 private http=inject(HttpClient);private route=inject(ActivatedRoute);private plugins=inject(GuildPluginService);guildId=this.route.snapshot.paramMap.get('guildId')||'';settings:any={installed:false,enabled:false,wars:[]};error=signal('');success=signal('');private get url(){return`/api/v1/discord/guilds/${this.guildId}/plugins/war-planner`}
 async ngOnInit(){try{const data=await firstValueFrom(this.http.get<any>(`${this.url}/settings`));this.settings={...data,wars:(data.wars||[]).map((war:any)=>({...war,expanded:false,waves:(war.waves||[]).map((wave:any)=>({...wave,local_start:this.local(wave.starts_at)}))}))}}catch(e:any){this.error.set(e?.error?.detail||'Could not load war plans.')}}
 local(value:string){if(!value)return'';const d=new Date(value),p=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
 addWar(){this.settings.wars.push({id:`war-${Date.now().toString(36)}`,name:'New war',title:'Alliance war',opponent:'',description:'',channel_id:null,enabled:true,waves:[],assignments:{},expanded:true})}
 addWave(war:any){war.waves.push({id:`wave-${Date.now().toString(36)}`,name:`Wave ${war.waves.length+1}`,local_start:'',capacity:0,targets:''})}
 assigned(war:any){return Object.keys(war.assignments||{}).length}waveCount(war:any,id:string){return Object.values(war.assignments||{}).filter(value=>value===id).length}
 payload(){return{wars:this.settings.wars.map(({expanded,message_id,assignments,...war}:any)=>({...war,waves:war.waves.map(({local_start,...wave}:any)=>({...wave,starts_at:new Date(local_start).toISOString()}))}))}}
 async install(){try{await this.plugins.install(this.guildId,'war_planner');await this.ngOnInit()}catch(e:any){this.error.set(e?.error?.detail||'Install failed.')}}
 async toggle(){try{this.settings.enabled?await this.plugins.disable(this.guildId,'war_planner'):await this.plugins.enable(this.guildId,'war_planner');await this.ngOnInit()}catch(e:any){this.error.set(e?.error?.detail||'State change failed.')}}
 async save(){this.error.set('');this.success.set('');try{const data=await firstValueFrom(this.http.put<any>(`${this.url}/settings`,this.payload()));this.settings={...data,wars:data.wars.map((war:any)=>({...war,expanded:true,waves:war.waves.map((wave:any)=>({...wave,local_start:this.local(wave.starts_at)}))}))};this.success.set('War plans saved.')}catch(e:any){this.error.set(e?.error?.detail||'Save failed.')}}
 async publish(war:any){await this.save();if(this.error())return;try{const result=await firstValueFrom(this.http.post<any>(`${this.url}/publish`,{war_id:war.id}));for(let i=0;i<30;i++){await new Promise(resolve=>setTimeout(resolve,1000));const job=await firstValueFrom(this.http.get<any>(`${this.url}/jobs/${result.job_id}`));if(job.status==='completed'){this.success.set('War plan published.');return}if(job.status==='failed')throw new Error(job.error)}}catch(e:any){this.error.set(e?.message||'Publish failed.')}}
}
