import {HttpClient} from '@angular/common/http';
import {Component,OnDestroy,OnInit,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {firstValueFrom} from 'rxjs';
import {GuildPluginService} from '../core/guild-plugin.service';
import {TranslationService} from '../core/translation.service';
import {TranslatePipe} from '../core/translate.pipe';
import {ShellComponent} from '../shared/shell.component';

@Component({standalone:true,imports:[FormsModule,ShellComponent,TranslatePipe],template:`
<sn-shell [title]="'wizard.title'|snT:'Server Setup Wizard'">
<header class="hero"><div><span>{{'wizard.eyebrow'|snT:'FIRST SERVER LAUNCH'}}</span><h2>{{'wizard.heading'|snT:'Create the initial server structure'}}</h2><p>{{'wizard.subtitle'|snT:'Answer four questions. GuildConsole will update the server profile and create its first system channel.'}}</p></div><b [class.ok]="state()?.completed">{{state()?.completed?('wizard.completed'|snT:'COMPLETED'):('wizard.setup'|snT:'SETUP')}}</b></header>
@if(error()){<div class="notice error">{{error()}}</div>}@if(success()){<div class="notice success">{{success()}}</div>}
@if(!state()?.installed){<section class="panel install"><h3>{{'wizard.install_title'|snT:'Install Wizard'}}</h3><p>{{'wizard.install_text'|snT:'Install the free Wizard plugin before configuring this Discord server.'}}</p><button class="primary" (click)="install()" [disabled]="busy()">{{'wizard.install'|snT:'Install Wizard'}}</button></section>}
@else{
<section class="panel permissions"><div><small>0 / 4</small><h3>{{'wizard.permissions'|snT:'Bot permissions'}}</h3><p>{{permissionText()}}</p></div><button (click)="checkPermissions()" [disabled]="busy()">{{'wizard.check_again'|snT:'Check again'}}</button></section>
<nav class="steps">@for(label of stepLabels;track label;let i=$index){<button (click)="step.set(i+1)" [class.active]="step()===i+1" [class.done]="step()>i+1">{{i+1}}<span>{{stepLabel(i)}}</span></button>}</nav>
<section class="panel form">
@if(step()===1){<div class="question"><small>1 / 4</small><h3>{{'wizard.server_identity'|snT:'Server name and logo'}}</h3><p>{{'wizard.identity_help'|snT:'The bot will update the Discord server profile.'}}</p><label>{{'wizard.server_name'|snT:'Server name'}}<input [(ngModel)]="form.name" maxlength="100"></label><label class="upload">{{'wizard.server_logo'|snT:'Server logo'}}<input type="file" accept="image/png,image/jpeg,image/webp" (change)="selectLogo($event)"><span>{{logoName()||('wizard.logo_optional'|snT:'PNG, JPEG or WebP; optional')}}</span></label></div>}
@if(step()===2){<div class="question"><small>2 / 4</small><h3>{{'wizard.description'|snT:'Server description'}}</h3><p>{{'wizard.description_help'|snT:'Explain the purpose of the community. This is also used as the first channel topic.'}}</p><label>{{'wizard.description'|snT:'Server description'}}<textarea rows="6" maxlength="300" [(ngModel)]="form.description"></textarea><em>{{form.description.length}} / 300</em></label></div>}
@if(step()===3){<div class="question"><small>3 / 4</small><h3>{{'wizard.game'|snT:'Game or community topic'}}</h3><p>{{'wizard.game_help'|snT:'Choose a common game or enter your own. Discord does not expose profile category checkboxes to bots.'}}</p><label>{{'wizard.game'|snT:'Game or topic'}}<select [(ngModel)]="form.game"><option value="">{{'wizard.select_game'|snT:'Select a game'}}</option>@for(game of games;track game){<option [value]="game">{{game}}</option>}<option value="__custom">{{'wizard.other_game'|snT:'Other'}}</option></select></label>@if(form.game==='__custom'){<label>{{'wizard.custom_game'|snT:'Game or topic name'}}<input [(ngModel)]="customGame" maxlength="100"></label>}</div>}
@if(step()===4){<div class="question"><small>4 / 4</small><h3>{{'wizard.system_channel'|snT:'First system channel'}}</h3><p>{{'wizard.channel_help'|snT:'The bot creates this text channel at the top and assigns it as the Discord system messages channel.'}}</p><label>{{'wizard.channel_name'|snT:'Channel name'}}<input [(ngModel)]="form.system_channel_name" maxlength="100" placeholder="welcome"></label><div class="summary"><b>{{form.name}}</b><span>{{effectiveGame()||'—'}}</span><span># {{form.system_channel_name}}</span></div></div>}
<footer><button (click)="previous()" [disabled]="step()===1||busy()">{{'wizard.back'|snT:'Back'}}</button>@if(step()<4){<button class="primary" (click)="next()" [disabled]="!validStep()">{{'wizard.next'|snT:'Next'}}</button>}@else{<button class="primary" (click)="apply()" [disabled]="busy()||!validStep()||!permissionsOk()">{{busy()?('wizard.applying'|snT:'Applying…'):('wizard.finish'|snT:'Create server structure')}}</button>}</footer>
</section>}
</sn-shell>`,styles:[`:host{display:block}.hero{display:flex;justify-content:space-between;gap:1rem;align-items:start;margin:1rem 0 1.3rem}.hero span{color:var(--accent);font-size:.7rem;font-weight:900;letter-spacing:.14em}.hero h2{margin:.35rem 0}.hero p,.panel p{color:var(--muted);margin:.35rem 0}.hero>b{padding:.55rem .8rem;border:1px solid var(--line);border-radius:99px;color:#f0a94b}.hero>b.ok{color:var(--success)}.panel{padding:1.25rem;border:1px solid var(--line);border-radius:16px;background:var(--panel);margin-bottom:1rem}.permissions{display:flex;justify-content:space-between;align-items:center;gap:1rem}.permissions small,.question>small{color:var(--accent);font-weight:900}.permissions h3,.question h3{margin:.3rem 0}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:.65rem;margin:1rem 0}.steps button{display:flex;align-items:center;gap:.6rem;text-align:left}.steps button.active{border-color:var(--accent);color:var(--accent)}.steps button.done{color:var(--success)}button,input,textarea,select{border:1px solid var(--line);border-radius:10px;background:var(--panel-2);color:var(--text);padding:.75rem}button{cursor:pointer;font-weight:800}.primary{background:var(--accent);border-color:var(--accent);color:#031612}.question{max-width:760px;margin:auto}.question label{display:grid;gap:.4rem;margin-top:1rem;font-weight:800}.question em{color:var(--muted);font-size:.75rem;font-style:normal;text-align:right}.upload input{padding:.5rem}.upload span{font-size:.75rem;color:var(--muted)}.summary{display:flex;gap:.65rem;flex-wrap:wrap;margin-top:1rem}.summary>*{padding:.55rem .7rem;border:1px solid var(--line);border-radius:8px}footer{display:flex;justify-content:space-between;margin-top:1.5rem;padding-top:1rem;border-top:1px solid var(--line)}.notice{padding:1rem;border-radius:12px;margin-bottom:1rem}.error{color:#ff8d96;background:rgba(255,90,110,.08)}.success{color:var(--success);background:rgba(53,226,178,.08)}@media(max-width:700px){.hero,.permissions{display:grid}.steps{grid-template-columns:1fr 1fr}.steps button{justify-content:flex-start}}` ]})
export class PluginWizardComponent implements OnInit,OnDestroy{
 private http=inject(HttpClient);private route=inject(ActivatedRoute);private plugins=inject(GuildPluginService);private i18n=inject(TranslationService);guildId=this.route.snapshot.paramMap.get('guildId')||'';state=signal<any>(null);step=signal(1);busy=signal(false);error=signal('');success=signal('');logoName=signal('');timer?:ReturnType<typeof setInterval>;customGame='';form={name:'',icon_data:null as string|null,description:'',game:'',system_channel_name:'welcome'};games=['Alliance of Valiant Arms','Call of Duty','Clash of Clans','Counter-Strike 2','Dota 2','EVE Online','Fortnite','League of Legends','Minecraft','Mobile Legends','PUBG','Roblox','World of Tanks','World of Warcraft'];
 get stepLabels(){return ['wizard.step_identity','wizard.step_description','wizard.step_game','wizard.step_channel']}
 stepLabel(index:number){return this.i18n.t(this.stepLabels[index],['Name and logo','Description','Game','System channel'][index])}
 async ngOnInit(){await this.load();if(this.state()?.installed&&!this.state()?.permission_check)await this.checkPermissions()}
 ngOnDestroy(){if(this.timer)clearInterval(this.timer)}
 async load(){try{const s=await firstValueFrom(this.http.get<any>(this.url));this.state.set(s);if(!this.form.name)this.form.name=s.guild?.name||'';if(this.running(s))this.startPolling();else if(s.completed)this.success.set(this.i18n.t('wizard.completed_message','Initial server setup is complete.'))}catch(e:any){this.fail(e)}}
 get url(){return `/api/v1/discord/guilds/${this.guildId}/plugins/wizard`}
 async install(){this.busy.set(true);try{await this.plugins.install(this.guildId,'wizard');await this.load();await this.checkPermissions()}catch(e:any){this.fail(e)}finally{this.busy.set(false)}}
 async checkPermissions(){this.busy.set(true);this.error.set('');try{await firstValueFrom(this.http.post(`${this.url}/check`,{}));this.startPolling()}catch(e:any){this.fail(e)}finally{this.busy.set(false)}}
 permissionsOk(){return !!this.state()?.permission_check?.result?.sufficient}
 permissionText(){const c=this.state()?.permission_check;if(!c||['pending','processing'].includes(c.status))return this.i18n.t('wizard.checking_permissions','Checking Manage Server and Manage Channels permissions…');if(c.status==='failed')return c.message||this.i18n.t('wizard.permissions_missing','The bot needs Manage Server and Manage Channels permissions.');return this.i18n.t('wizard.permissions_ok','Required permissions are available.')}
 selectLogo(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>1024*1024){this.error.set(this.i18n.t('wizard.logo_too_large','The logo must be smaller than 1 MB.'));return}const reader=new FileReader();reader.onload=()=>{this.form.icon_data=String(reader.result);this.logoName.set(file.name)};reader.readAsDataURL(file)}
 effectiveGame(){return this.form.game==='__custom'?this.customGame.trim():this.form.game}
 validStep(){if(this.step()===1)return this.form.name.trim().length>=2;if(this.step()===2)return this.form.description.trim().length>=3;if(this.step()===3)return this.effectiveGame().length>=2;return this.form.system_channel_name.trim().length>=1}
 next(){if(this.validStep())this.step.update(v=>Math.min(4,v+1))}
 previous(){this.step.update(v=>Math.max(1,v-1))}
 async apply(){this.busy.set(true);this.error.set('');this.success.set('');try{await firstValueFrom(this.http.post(`${this.url}/apply`,{...this.form,game:this.effectiveGame()}));this.success.set(this.i18n.t('wizard.queued','Server setup has started. Keep this page open to see the result.'));this.startPolling()}catch(e:any){this.fail(e)}finally{this.busy.set(false)}}
 running(s:any){return [s?.permission_check,s?.profile_job,s?.channel_job].some((x:any)=>x&&['pending','processing'].includes(x.status))}
 startPolling(){if(this.timer)return;this.timer=setInterval(async()=>{await this.load();if(!this.running(this.state())){clearInterval(this.timer);this.timer=undefined}},1500)}
 fail(e:any){this.error.set(e?.error?.detail||e?.message||this.i18n.t('wizard.error','Wizard operation failed.'))}
}

