import {Component,OnInit} from '@angular/core';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {TranslationService} from '../core/translation.service';
import {PublicBrandComponent} from '../shared/public-brand.component';

type LegalPage='terms'|'refund'|'payment'|'contacts';

@Component({standalone:true,imports:[RouterLink,PublicBrandComponent],template:`
<main class="legal">
  <header class="top"><sn-public-brand ariaLabel="На головну GuildConsole"/><nav><a routerLink="/docs">Документація</a><a routerLink="/pricing">Тарифи</a><a routerLink="/login">Увійти</a></nav></header>
  <section class="hero"><span>GUILDCONSOLE · ПРАВОВА ІНФОРМАЦІЯ</span><h1>{{title}}</h1><p>{{lead}}</p><small>Редакція від 21 вересня 2026 року</small></section>

  @if(page==='terms'){
    <section class="content">
      <article><b>01</b><div><h2>Загальні положення</h2><p>Ці Умови регулюють використання вебсервісу GuildConsole та є публічною пропозицією укласти договір про надання доступу до програмного забезпечення. Використовуючи сервіс або здійснюючи оплату, користувач підтверджує, що прочитав ці Умови, розуміє їх і погоджується з ними.</p><p>Постачальник послуг: ФОП Лавріненко Катерина Георгіївна, РНОКПП 3018813129. GuildConsole є незалежним програмним продуктом і не є продуктом Discord Inc.</p></div></article>
      <article><b>02</b><div><h2>Предмет послуги</h2><p>GuildConsole надає строковий дистанційний доступ до власного програмного забезпечення для адміністрування Discord-серверів. Функції охоплюють керування налаштуваннями сервера, ролями й учасниками, модерацію, аудит безпеки, автоматизацію, події, голосування, резервні копії, мовні інструменти та інші модулі, опубліковані в документації.</p><p>GuildConsole не продає облікові записи Discord, Discord Nitro, Server Boosts, внутрішню валюту, цифрові активи Discord або права на сторонні сервіси.</p></div></article>
      <article><b>03</b><div><h2>Обліковий запис і підключення сервера</h2><p>Вхід виконується через Discord. Користувач повинен мати законні повноваження власника або адміністратора відповідного сервера. Під час підключення бот отримує лише ті дозволи, які користувач підтвердив у Discord. Користувач відповідає за коректність налаштувань доступу та дії осіб, яким надав права в панелі.</p></div></article>
      <article><b>04</b><div><h2>Тарифи та строк доступу</h2><p>Актуальні ціни, тривалість доступу й перелік платних модулів наведено на сторінці «Тарифи». Ціна показується до оплати. Платна підписка діє для одного обраного Discord-сервера протягом оплаченого періоду. Безкоштовні модулі залишаються доступними відповідно до їхніх поточних умов.</p></div></article>
      <article><b>05</b><div><h2>Надання та активація</h2><p>Послуга надається виключно в електронній формі. Після підтвердження оплати доступ активується автоматично, як правило, протягом кількох хвилин. Фізична доставка відсутня. Статус і дата завершення доступу відображаються в кабінеті користувача.</p></div></article>
      <article><b>06</b><div><h2>Допустиме використання</h2><p>Заборонено використовувати сервіс для шахрайства, спаму, переслідування, незаконного збору даних, обходу обмежень Discord, поширення шкідливого коду або порушення прав третіх осіб. Користувач повинен дотримуватися законодавства, правил Discord та прав учасників сервера.</p></div></article>
      <article><b>07</b><div><h2>Сторонні сервіси</h2><p>Робота окремих функцій залежить від Discord, платіжного провайдера, постачальників штучного інтелекту та інших зовнішніх платформ. GuildConsole не контролює їхню безперервність, але вживає розумних заходів для відновлення власного сервісу та інформування користувачів про істотні збої.</p></div></article>
      <article><b>08</b><div><h2>Інтелектуальна власність</h2><p>Програмний код, дизайн, документація, назва та матеріали GuildConsole належать постачальнику або використовуються на законних підставах. Оплата надає обмежене право користуватися сервісом протягом оплаченого періоду й не передає права власності на програмне забезпечення.</p></div></article>
      <article><b>09</b><div><h2>Відповідальність і припинення доступу</h2><p>Постачальник відповідає за надання оплаченої послуги в межах законодавства України. Доступ може бути тимчасово обмежено для технічних робіт, захисту системи або припинено в разі істотного порушення Умов. Це не обмежує права споживача, передбачені законом.</p></div></article>
      <article><b>10</b><div><h2>Звернення та вирішення спорів</h2><p>Звернення приймаються електронною поштою info@lrm-it.com. Просимо зазначити Discord-акаунт, сервер, номер платежу та суть питання. Спори спочатку вирішуються шляхом переговорів, а за відсутності згоди — відповідно до законодавства України.</p></div></article>
    </section>
  }
  @if(page==='refund'){
    <section class="content">
      <article><b>01</b><div><h2>Як подати запит</h2><p>Надішліть лист на info@lrm-it.com із темою «Повернення коштів». Укажіть ПІБ або назву платника, email облікового запису, Discord ID за наявності, номер і дату платежу, суму, оплачений сервер та причину звернення. Не надсилайте номер картки, CVV або інші платіжні реквізити.</p></div></article>
      <article><b>02</b><div><h2>Коли можливе повернення</h2><p>Запит може бути задоволено, якщо послуга не активувалася після успішної оплати, стала технічно недоступною з вини GuildConsole і не була відновлена в розумний строк, відбулося помилкове повторне списання, або повернення прямо вимагається законодавством України.</p></div></article>
      <article><b>03</b><div><h2>До початку надання послуги</h2><p>Якщо доступ ще не активовано і послуга фактично не почала надаватися, користувач може звернутися щодо скасування платежу. Якщо активація вже відбулася, рішення приймається з урахуванням фактично використаного періоду, технічних обставин і вимог законодавства.</p></div></article>
      <article><b>04</b><div><h2>Випадки, що потребують перевірки</h2><p>Зміна рішення користувача після активації, невикористання доступних функцій, помилки в налаштуваннях Discord або обмеження стороннього сервісу самі по собі не гарантують повернення. Кожне звернення розглядається індивідуально, без обмеження законних прав споживача.</p></div></article>
      <article><b>05</b><div><h2>Строк розгляду</h2><p>Звернення розглядається протягом семи робочих днів після отримання достатньої інформації. Якщо потрібна додаткова перевірка, ми повідомимо про це заявника. Після погодження повернення ініціюється через платіжного провайдера.</p></div></article>
      <article><b>06</b><div><h2>Спосіб і строк зарахування</h2><p>Кошти повертаються на той платіжний засіб, з якого здійснено оплату. Строк фактичного зарахування залежить від платіжного провайдера та банку-емітента. Можливе повне або часткове повернення залежно від обставин і невикористаної частини послуги.</p></div></article>
      <article><b>07</b><div><h2>Подвійне списання та помилкова сума</h2><p>У разі двох оплат одного замовлення або списання суми, що не відповідає підтвердженому замовленню, зверніться до підтримки. Після звірки платежів зайва сума повертається тим самим способом.</p></div></article>
      <article><b>08</b><div><h2>Оскарження платежу</h2><p>Перед зверненням до банку рекомендуємо написати нам: це дозволяє швидше знайти операцію та вирішити питання. Це прохання не обмежує право користувача звертатися до банку, платіжної системи або компетентного державного органу.</p></div></article>
    </section>
  }
  @if(page==='payment'){
    <section class="content">
      <article><b>01</b><div><h2>Що саме оплачується</h2><p>Клієнт оплачує цифрову послугу — доступ до платних програмних модулів GuildConsole для одного обраного Discord-сервера на визначений строк. Перелік модулів і чинні ціни публікуються на сторінках «Тарифи» та «Документація».</p></div></article>
      <article><b>02</b><div><h2>Ціна та валюта</h2><p>До підтвердження платежу користувач бачить суму, валюту, призначення та період доступу. Остаточна сума відображається в платіжній формі. Можливі курсові різниці або комісії банку платника визначаються його банком.</p></div></article>
      <article><b>03</b><div><h2>Платіжний шлюз</h2><p>Оплата банківськими картками Visa та Mastercard проводиться через захищений платіжний шлюз. Дані картки вводяться в захищеній платіжній формі провайдера. GuildConsole не отримує і не зберігає повний номер картки, строк її дії або CVV.</p></div></article>
      <article><b>04</b><div><h2>Внутрішній облік коштів</h2><p>Особистий баланс у кабінеті є технічним обліком передоплати виключно для придбання послуг GuildConsole. Він не є банківським рахунком, електронними грошима чи інвестиційним активом, не приносить відсотків, не переказується іншим користувачам і не використовується для розрахунків поза GuildConsole.</p></div></article>
      <article><b>05</b><div><h2>Підтвердження та активація</h2><p>Після успішної авторизації платежу платіжний шлюз надсилає серверне підтвердження. Лише після перевірки цього повідомлення сума відображається в кабінеті або активується доступ. Зазвичай це займає кілька хвилин. Статус операції зберігається в історії платежів.</p></div></article>
      <article><b>06</b><div><h2>Період доступу</h2><p>Доступ можна придбати на 30, 90 або 365 днів, якщо відповідний тариф активний. Початок періоду визначається моментом активації. Дата завершення відображається до підтвердження продовження та після нього.</p></div></article>
      <article><b>07</b><div><h2>Автоматичне продовження</h2><p>Автоматичне продовження з особистого балансу застосовується лише після окремого вибору користувача. Його можна вимкнути в кабінеті до наступної дати продовження. GuildConsole не виконує прихованих списань із банківської картки.</p></div></article>
      <article><b>08</b><div><h2>Невдалий або незавершений платіж</h2><p>Якщо провайдер не підтвердив операцію, доступ не активується. Не повторюйте оплату, якщо кошти списані, але статус ще обробляється: надішліть номер платежу до підтримки для звірки.</p></div></article>
      <article><b>09</b><div><h2>Документи та підтримка</h2><p>Інформація про операцію доступна в кабінеті й у платіжного провайдера. Для звірки або повернення напишіть на info@lrm-it.com. Правила повернення опубліковано окремо і є невіддільною частиною цих умов.</p></div></article>
    </section>
  }
  @if(page==='contacts'){
    <section class="contacts">
      <article><span>ПРОДАВЕЦЬ І ПОСТАЧАЛЬНИК ПОСЛУГ</span><h2>ФОП Лавріненко Катерина Георгіївна</h2><dl><div><dt>РНОКПП</dt><dd>3018813129</dd></div><div><dt>Юридична адреса</dt><dd>Україна, м. Київ, вул. Сержа Лифаря, буд. 5</dd></div><div><dt>Фактична адреса</dt><dd>Україна, м. Київ, вул. Сержа Лифаря, буд. 5</dd></div><div><dt>Email</dt><dd><a href="mailto:info@lrm-it.com">info@lrm-it.com</a></dd></div><div><dt>Телефон</dt><dd><a href="tel:+380939848542">+380 93 984 85 42</a></dd></div><div><dt>Вебсайт</dt><dd>guildconsole.lrm-it.com</dd></div></dl></article>
      <article><span>ПІДТРИМКА</span><h2>Як звернутися</h2><p>Загальні, технічні, платіжні та юридичні звернення приймаються електронною поштою. Зареєстровані користувачі також можуть створити заявку в розділі «Пропозиції та помилки» й додати зображення.</p><p>Для швидкої перевірки зазначте тему звернення, Discord ID, назву або ID сервера, номер платежу та послідовність дій. Не надсилайте паролі, токени ботів, CVV або повний номер банківської картки.</p><a class="button" href="mailto:info@lrm-it.com">Написати підтримці</a></article>
      <article><span>НАДАННЯ ПОСЛУГ</span><h2>Дистанційний цифровий сервіс</h2><p>Послуги надаються онлайн через GuildConsole. Фізичний магазин і фізична доставка відсутні. Доступність окремих функцій може залежати від Discord та інших зовнішніх платформ.</p></article>
    </section>
  }

  <aside><strong>Пов’язані документи</strong><a routerLink="/terms">Умови користування</a><a routerLink="/payment">Оплата й активація</a><a routerLink="/refund">Повернення коштів</a><a routerLink="/privacy-policy">Конфіденційність</a><a routerLink="/contacts">Контакти</a><a routerLink="/pricing">Тарифи</a></aside>
  <footer><span>© GuildConsole · ФОП Лавріненко Катерина Георгіївна</span><nav><a routerLink="/docs">Документація</a><a routerLink="/login">Відкрити консоль</a></nav></footer>
</main>`,styles:[`
:host{display:block;min-height:100vh;background:#060a10;color:#edf8f5}.legal{min-height:100vh;padding:1.2rem clamp(1rem,4vw,4rem);background:radial-gradient(circle at 8% 3%,rgba(53,226,178,.1),transparent 27rem),linear-gradient(rgba(53,226,178,.024) 1px,transparent 1px),linear-gradient(90deg,rgba(53,226,178,.024) 1px,transparent 1px);background-size:auto,44px 44px,44px 44px}.top,.hero,.content,.contacts,aside,footer{width:min(1180px,100%);margin-inline:auto}.top,footer{display:flex;align-items:center;justify-content:space-between;gap:1rem;border-bottom:1px solid rgba(123,170,172,.18);padding:.8rem 0 1.25rem}.top nav,footer nav{display:flex;gap:1rem}.top a,footer a,aside a{color:#91aaa9;text-decoration:none}.top a:hover,footer a:hover,aside a:hover{color:#35e2b2}.hero{padding:5.5rem 0 3.5rem}.hero>span,.contacts article>span{color:#35e2b2;font-size:.67rem;font-weight:900;letter-spacing:.16em}.hero h1{max-width:900px;margin:.7rem 0;font-size:clamp(2.5rem,6vw,5.4rem);line-height:.98;letter-spacing:-.045em}.hero p{max-width:820px;color:#9bb0b6;font-size:1.08rem;line-height:1.75}.hero small{color:#647a82}.content{display:grid}.content article{display:grid;grid-template-columns:70px 1fr;gap:1.4rem;padding:2.2rem 0;border-top:1px solid rgba(123,170,172,.17)}.content article>b{color:#4e6b70;font:700 .72rem ui-monospace,monospace}.content h2,.contacts h2{margin:0 0 .8rem;font-size:1.35rem}.content p,.contacts p{max-width:900px;margin:.45rem 0;color:#91a5ad;line-height:1.78}.contacts{display:grid;grid-template-columns:1.3fr 1fr;gap:1rem}.contacts article{padding:1.4rem;border:1px solid rgba(123,170,172,.18);border-radius:15px;background:rgba(15,25,34,.78)}.contacts article:last-child{grid-column:1/-1}.contacts h2{margin:.55rem 0 1rem}.contacts dl{margin:0}.contacts dl div{display:grid;grid-template-columns:160px 1fr;gap:1rem;padding:.75rem 0;border-top:1px solid rgba(123,170,172,.13)}dt{color:#6f8990}dd{margin:0}dd a,.button{color:#35e2b2}.button{display:inline-flex;margin-top:1rem;padding:.7rem 1rem;border:1px solid rgba(53,226,178,.35);border-radius:9px;text-decoration:none;background:rgba(53,226,178,.08)}aside{display:flex;align-items:center;gap:1rem;flex-wrap:wrap;margin-top:3rem;padding:1.2rem;border:1px solid rgba(123,170,172,.18);border-radius:13px;background:rgba(15,25,34,.72)}aside strong{color:#edf8f5}aside a{font-size:.75rem}footer{margin-top:2rem;padding:1.5rem 0;border-top:1px solid rgba(123,170,172,.18);border-bottom:0;color:#647a82;font-size:.72rem}@media(max-width:720px){.top{align-items:flex-start}.top nav{display:grid;text-align:right}.hero{padding:3.5rem 0 2.5rem}.content article{grid-template-columns:1fr;gap:.5rem}.contacts{grid-template-columns:1fr}.contacts article:last-child{grid-column:auto}.contacts dl div{grid-template-columns:1fr;gap:.25rem}footer{align-items:flex-start;flex-direction:column}}
`]})
export class PublicLegalComponent implements OnInit{
  page:LegalPage='terms';title='';lead='';
  constructor(private route:ActivatedRoute,private i18n:TranslationService){}
  async ngOnInit(){await this.i18n.setLocale('uk',false);this.page=(this.route.snapshot.data['legalPage']||'terms') as LegalPage;const copy={terms:['Умови користування та публічна оферта','Правила надання доступу до GuildConsole, права й обов’язки користувача та постачальника цифрової послуги.'],refund:['Політика повернення коштів','Зрозумілий порядок скасування, розгляду звернень і повернення платежів за цифрові послуги GuildConsole.'],payment:['Оплата, активація та підписка','Що саме купує клієнт, як обробляється платіж і коли активується доступ до програмного забезпечення.'],contacts:['Контакти продавця','Офіційні реквізити постачальника послуг і способи звернення до підтримки GuildConsole.']} as Record<LegalPage,string[]>;[this.title,this.lead]=copy[this.page]}
}
