import {CommonModule} from '@angular/common';
import {Component,OnInit,computed,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {AuthService} from '../core/auth.service';
import {SupportService,SupportTicket} from '../core/support.service';
import {ShellComponent} from '../shared/shell.component';

@Component({selector:'sn-support',standalone:true,imports:[CommonModule,FormsModule,ShellComponent],template:`
<sn-shell title="Предложения и ошибки"><main class="page">
 <header><div><span>ОБРАТНАЯ СВЯЗЬ</span><h2>Предложения и ошибки</h2><p>{{staff()?'Обработка обращений пользователей панели.':'Сообщите об ошибке или предложите улучшение.'}}</p></div><button class="primary" (click)="showCreate.set(!showCreate())">+ Создать тикет</button></header>
 @if(error()){<div class="notice error">{{error()}}</div>}@if(success()){<div class="notice success">{{success()}}</div>}
 @if(showCreate()){<section class="card create"><h3>Новый тикет</h3><label>Тема<select [(ngModel)]="form.topic"><option value="bug">Ошибка</option><option value="suggestion">Пожелание</option></select></label><label>Заголовок<input [(ngModel)]="form.subject" maxlength="160"></label><label>Описание<textarea [(ngModel)]="form.body" rows="6" maxlength="10000"></textarea></label><button class="primary" [disabled]="busy()||form.subject.trim().length<3||form.body.trim().length<3" (click)="create()">Отправить</button></section>}
 <section class="workspace">
  <aside class="list card"><div class="filters">@if(staff()){<select [(ngModel)]="statusFilter" (change)="load()"><option value="">Все статусы</option><option value="open">Открытые</option><option value="in_progress">В работе</option><option value="resolved">Решённые</option><option value="closed">Закрытые</option></select>}</div>
  @for(t of tickets();track t.id){<button class="ticket" [class.active]="selected()?.id===t.id" (click)="open(t)"><span class="topic" [class.bug]="t.topic==='bug'">{{t.topic==='bug'?'ОШИБКА':'ПОЖЕЛАНИЕ'}}</span><strong>{{t.subject}}</strong>@if(staff()){<small>{{t.author_name}} · {{t.author_email}}</small>}<small>{{status(t.status)}} · {{t.updated_at|date:'short'}}</small></button>}@empty{<p class="empty">Тикетов пока нет.</p>}</aside>
  <article class="detail card">@if(selected();as t){<header class="detail-head"><div><span class="topic" [class.bug]="t.topic==='bug'">{{t.topic==='bug'?'ОШИБКА':'ПОЖЕЛАНИЕ'}}</span><h3>{{t.subject}}</h3>@if(staff()){<small>{{t.author_name}} · {{t.author_email}}</small>}</div>@if(staff()){<div class="controls"><select [ngModel]="t.priority" (ngModelChange)="change({priority:$event})"><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="urgent">Срочный</option></select><select [ngModel]="t.status" (ngModelChange)="change({status:$event})"><option value="open">Открыт</option><option value="in_progress">В работе</option><option value="resolved">Решён</option><option value="closed">Закрыт</option></select></div>}</header>
   <div class="messages">@for(m of t.messages||[];track m.id){<div class="message" [class.staff]="m.is_staff"><div><b>{{m.author_name}}</b><small>{{m.is_staff?'Команда поддержки':'Пользователь'}} · {{m.created_at|date:'short'}}</small></div><p>{{m.body}}</p></div>}</div>
   @if(t.status!=='closed'||staff()){<div class="reply"><textarea [(ngModel)]="replyBody" rows="4" placeholder="Введите ответ..."></textarea><button class="primary" [disabled]="busy()||!replyBody.trim()" (click)="reply()">Отправить ответ</button></div>}
  }@else{<div class="empty">Выберите тикет из списка.</div>}</article>
 </section>
</main></sn-shell>`,styles:[`
.page{max-width:1280px;margin:auto;display:grid;gap:1rem}.page>header,.detail-head{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem}.page>header span{color:var(--primary);font-size:.7rem;font-weight:900;letter-spacing:.15em}h2,h3,p{margin:.25rem 0}.page>header p,small,.empty{color:var(--muted)}.card,.notice{padding:1rem;border:1px solid var(--line);border-radius:15px;background:var(--panel)}.create{display:grid;gap:.8rem}.create label{display:grid;gap:.35rem}.workspace{display:grid;grid-template-columns:360px minmax(0,1fr);gap:1rem;min-height:560px}.list{padding:.5rem;align-content:start}.filters{padding:.35rem}.filters select{width:100%}.ticket{width:100%;display:grid;gap:.3rem;padding:.8rem;color:var(--text);background:transparent;border:1px solid transparent;border-radius:10px;text-align:left;cursor:pointer}.ticket:hover,.ticket.active{background:var(--panel-2);border-color:var(--line-strong)}.topic{width:max-content;padding:.2rem .45rem;border-radius:999px;background:rgba(53,226,178,.12);color:var(--primary);font-size:.58rem;font-weight:900}.topic.bug{background:rgba(255,85,105,.12);color:#ff7b88}.detail{display:grid;grid-template-rows:auto 1fr auto;gap:1rem}.controls{display:flex;gap:.5rem}.messages{display:grid;align-content:start;gap:.7rem;max-height:560px;overflow:auto}.message{padding:.8rem;border:1px solid var(--line);border-radius:11px;background:var(--panel-2)}.message.staff{border-color:rgba(53,226,178,.3)}.message>div{display:flex;justify-content:space-between;gap:1rem}.message p{white-space:pre-wrap;line-height:1.5}.reply{display:grid;gap:.6rem}.reply button{justify-self:end}input,select,textarea,button{padding:.7rem;border-radius:9px;border:1px solid var(--line);background:var(--panel-2);color:var(--text)}textarea{resize:vertical}.primary{background:var(--primary);color:#06110e;font-weight:900;cursor:pointer}.primary:disabled{opacity:.5}.notice.error{color:#ff8792}.notice.success{color:var(--success)}@media(max-width:850px){.workspace{grid-template-columns:1fr}.page>header,.detail-head{display:grid}.controls{flex-wrap:wrap}}
`]})
export class SupportComponent implements OnInit{
 tickets=signal<SupportTicket[]>([]);selected=signal<SupportTicket|null>(null);showCreate=signal(false);busy=signal(false);error=signal('');success=signal('');statusFilter='';replyBody='';form={topic:'bug',subject:'',body:''};staff=computed(()=>!!this.auth.profile()?.is_superadmin);
 constructor(private api:SupportService,private auth:AuthService){}
 ngOnInit(){void this.load()}
 async load(){try{this.tickets.set(await this.api.list(this.staff(),this.statusFilter));const id=this.selected()?.id;if(id){const found=this.tickets().find(x=>x.id===id);if(found)await this.open(found)}}catch(e:any){this.error.set(e?.error?.detail||'Не удалось загрузить тикеты.')}}
 async open(t:SupportTicket){try{this.selected.set(await this.api.get(t.id,this.staff()))}catch(e:any){this.error.set(e?.error?.detail||'Не удалось открыть тикет.')}}
 async create(){this.busy.set(true);this.error.set('');try{const t=await this.api.create(this.form);this.form={topic:'bug',subject:'',body:''};this.showCreate.set(false);this.success.set('Тикет создан.');await this.load();await this.open(t)}catch(e:any){this.error.set(e?.error?.detail||'Не удалось создать тикет.')}finally{this.busy.set(false)}}
 async reply(){const t=this.selected();if(!t)return;this.busy.set(true);try{await this.api.reply(t.id,this.replyBody,this.staff());this.replyBody='';await this.open(t);await this.load()}catch(e:any){this.error.set(e?.error?.detail||'Не удалось отправить ответ.')}finally{this.busy.set(false)}}
 async change(data:any){const t=this.selected();if(!t)return;try{await this.api.update(t.id,data);await this.load()}catch(e:any){this.error.set(e?.error?.detail||'Не удалось обновить тикет.')}}
 status(v:string){return({open:'Открыт',in_progress:'В работе',resolved:'Решён',closed:'Закрыт'} as any)[v]||v}
}
