import {CommonModule} from '@angular/common';
import {Component,OnInit,computed,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {AuthService} from '../core/auth.service';
import {SupportService,SupportTicket} from '../core/support.service';
import {ShellComponent} from '../shared/shell.component';
import {TranslatePipe} from '../core/translate.pipe';
import {TranslationService} from '../core/translation.service';

@Component({selector:'sn-support',standalone:true,imports:[CommonModule,FormsModule,ShellComponent,TranslatePipe],template:`
<sn-shell [title]="'support.title'|snT:'Feedback & issues'"><main class="page">
 <header><div><span>{{'support.eyebrow'|snT:'FEEDBACK'}}</span><h2>{{'support.title'|snT:'Feedback & issues'}}</h2><p>{{'support.subtitle'|snT:'Contact the GuildConsole support team.'}}</p></div></header>
 @if(error()){<div class="notice error">{{error()}}</div>}@if(success()){<div class="notice success">{{success()}}</div>}
 <nav class="tabs"><button [class.active]="tab()==='create'" (click)="tab.set('create')">1. {{'support.submit_tab'|snT:'Submit request'}}</button><button [class.active]="tab()==='list'" (click)="tab.set('list')">2. {{(staff()?'support.all_tickets':'support.my_tickets')|snT:(staff()?'All tickets':'My tickets')}}</button></nav>
 @if(tab()==='create'){<section class="card create"><div class="intro"><h3>{{'support.new_ticket'|snT:'New ticket'}}</h3><p><b>{{'support.bug'|snT:'Bug'}}</b> — {{'support.bug_help'|snT:'choose this topic if something does not work. Describe the problem, your actions and the result.'}}</p><p><b>{{'support.suggestion'|snT:'Suggestion'}}</b> — {{'support.suggestion_help'|snT:'choose this topic if you need a feature, have an improvement idea or want a custom plugin.'}}</p></div><label>{{'support.topic'|snT:'Topic'}}<select [(ngModel)]="form.topic"><option value="bug">{{'support.bug'|snT:'Bug'}}</option><option value="suggestion">{{'support.suggestion'|snT:'Suggestion'}}</option></select></label><label>{{'support.subject'|snT:'Subject'}}<input [(ngModel)]="form.subject" maxlength="160" [placeholder]="'support.subject_placeholder'|snT:'Briefly describe your request'"></label><label>{{'support.description'|snT:'Detailed description'}}<textarea [(ngModel)]="form.body" rows="7" maxlength="10000" [placeholder]="'support.description_placeholder'|snT:'Add the details needed to review the request'"></textarea></label><button class="primary" [disabled]="busy()||form.subject.trim().length<3||form.body.trim().length<3" (click)="create()">{{'support.send_ticket'|snT:'Send request'}}</button></section>}
 @if(tab()==='list'){
 <section class="workspace">
  <aside class="list card"><div class="filters">@if(staff()){<select [(ngModel)]="statusFilter" (change)="load()"><option value="">{{'support.all_statuses'|snT:'All statuses'}}</option><option value="open">{{'support.status_open'|snT:'Open'}}</option><option value="in_progress">{{'support.status_progress'|snT:'In progress'}}</option><option value="resolved">{{'support.status_resolved'|snT:'Resolved'}}</option><option value="closed">{{'support.status_closed'|snT:'Closed'}}</option></select>}</div>
  @for(t of tickets();track t.id){<button class="ticket" [class.active]="selected()?.id===t.id" (click)="open(t)"><span class="topic" [class.bug]="t.topic==='bug'">{{(t.topic==='bug'?'support.bug':'support.suggestion')|snT:(t.topic==='bug'?'BUG':'SUGGESTION')}}</span><strong>{{t.subject}}</strong>@if(staff()){<small>{{t.author_name}} · {{t.author_email}}</small>}<small>{{status(t.status)}} · {{t.updated_at|date:'short'}}</small></button>}@empty{<p class="empty">{{'support.no_tickets'|snT:'No tickets yet.'}}</p>}</aside>
  <article class="detail card">@if(selected();as t){<header class="detail-head"><div><span class="topic" [class.bug]="t.topic==='bug'">{{(t.topic==='bug'?'support.bug':'support.suggestion')|snT:(t.topic==='bug'?'BUG':'SUGGESTION')}}</span><h3>{{t.subject}}</h3>@if(staff()){<small>{{t.author_name}} · {{t.author_email}}</small>}</div>@if(staff()){<div class="controls"><select [ngModel]="t.priority" (ngModelChange)="change({priority:$event})"><option value="low">{{'support.priority_low'|snT:'Low'}}</option><option value="normal">{{'support.priority_normal'|snT:'Normal'}}</option><option value="high">{{'support.priority_high'|snT:'High'}}</option><option value="urgent">{{'support.priority_urgent'|snT:'Urgent'}}</option></select><select [ngModel]="t.status" (ngModelChange)="change({status:$event})"><option value="open">{{'support.status_open'|snT:'Open'}}</option><option value="in_progress">{{'support.status_progress'|snT:'In progress'}}</option><option value="resolved">{{'support.status_resolved'|snT:'Resolved'}}</option><option value="closed">{{'support.status_closed'|snT:'Closed'}}</option></select></div>}</header>
   <div class="messages">@for(m of t.messages||[];track m.id){<div class="message" [class.staff]="m.is_staff"><div><b>{{m.author_name}}</b><small>{{(m.is_staff?'support.staff':'support.user')|snT:(m.is_staff?'Support team':'User')}} · {{m.created_at|date:'short'}}</small></div><p>{{m.body}}</p></div>}</div>
   @if(t.status!=='closed'||staff()){<div class="reply"><textarea [(ngModel)]="replyBody" rows="4" [placeholder]="'support.reply_placeholder'|snT:'Enter your reply...'"></textarea><button class="primary" [disabled]="busy()||!replyBody.trim()" (click)="reply()">{{'support.send_reply'|snT:'Send reply'}}</button></div>}
  }@else{<div class="empty">{{'support.select_ticket'|snT:'Select a ticket from the list.'}}</div>}</article>
 </section>
 }
</main></sn-shell>`,styles:[`
.page{max-width:1280px;margin:auto;display:grid;gap:1rem}.page>header,.detail-head{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem}.page>header span{color:var(--primary);font-size:.7rem;font-weight:900;letter-spacing:.15em}h2,h3,p{margin:.25rem 0}.page>header p,small,.empty{color:var(--muted)}.tabs{display:flex;gap:.45rem;padding:.4rem;border:1px solid var(--line);border-radius:13px;background:var(--panel)}.tabs button{flex:1;color:var(--muted);background:transparent}.tabs button.active{color:#06110e;background:var(--primary)}.card,.notice{padding:1rem;border:1px solid var(--line);border-radius:15px;background:var(--panel)}.create{display:grid;gap:1rem}.intro{display:grid;gap:.55rem;padding-bottom:1rem;border-bottom:1px solid var(--line)}.intro p{max-width:900px;color:var(--muted);line-height:1.55}.intro b{color:var(--text)}.create label{display:grid;gap:.35rem}.create>.primary{justify-self:end}.workspace{display:grid;grid-template-columns:360px minmax(0,1fr);gap:1rem;min-height:560px}.list{padding:.5rem;align-content:start}.filters{padding:.35rem}.filters select{width:100%}.ticket{width:100%;display:grid;gap:.3rem;padding:.8rem;color:var(--text);background:transparent;border:1px solid transparent;border-radius:10px;text-align:left;cursor:pointer}.ticket:hover,.ticket.active{background:var(--panel-2);border-color:var(--line-strong)}.topic{width:max-content;padding:.2rem .45rem;border-radius:999px;background:rgba(53,226,178,.12);color:var(--primary);font-size:.58rem;font-weight:900}.topic.bug{background:rgba(255,85,105,.12);color:#ff7b88}.detail{display:grid;grid-template-rows:auto 1fr auto;gap:1rem}.controls{display:flex;gap:.5rem}.messages{display:grid;align-content:start;gap:.7rem;max-height:560px;overflow:auto}.message{padding:.8rem;border:1px solid var(--line);border-radius:11px;background:var(--panel-2)}.message.staff{border-color:rgba(53,226,178,.3)}.message>div{display:flex;justify-content:space-between;gap:1rem}.message p{white-space:pre-wrap;line-height:1.5}.reply{display:grid;gap:.6rem}.reply button{justify-self:end}input,select,textarea,button{padding:.7rem;border-radius:9px;border:1px solid var(--line);background:var(--panel-2);color:var(--text)}textarea{resize:vertical}.primary{background:var(--primary);color:#06110e;font-weight:900;cursor:pointer}.primary:disabled{opacity:.5}.notice.error{color:#ff8792}.notice.success{color:var(--success)}@media(max-width:850px){.workspace{grid-template-columns:1fr}.page>header,.detail-head{display:grid}.controls{flex-wrap:wrap}}
`]})
export class SupportComponent implements OnInit{
 tickets=signal<SupportTicket[]>([]);selected=signal<SupportTicket|null>(null);tab=signal<'create'|'list'>('create');busy=signal(false);error=signal('');success=signal('');statusFilter='';replyBody='';form={topic:'bug',subject:'',body:''};staff=computed(()=>!!this.auth.profile()?.is_superadmin);
 constructor(private api:SupportService,private auth:AuthService,private i18n:TranslationService){}
 ngOnInit(){void this.load()}
 async load(){try{this.tickets.set(await this.api.list(this.staff(),this.statusFilter));const id=this.selected()?.id;if(id){const found=this.tickets().find(x=>x.id===id);if(found)await this.open(found)}}catch(e:any){this.error.set(e?.error?.detail||this.i18n.t('support.load_error','Unable to load tickets.'))}}
 async open(t:SupportTicket){try{this.selected.set(await this.api.get(t.id,this.staff()))}catch(e:any){this.error.set(e?.error?.detail||this.i18n.t('support.open_error','Unable to open ticket.'))}}
 async create(){this.busy.set(true);this.error.set('');try{const t=await this.api.create(this.form);this.form={topic:'bug',subject:'',body:''};this.tab.set('list');this.success.set(this.i18n.t('support.created','Ticket created.'));await this.load();await this.open(t)}catch(e:any){this.error.set(e?.error?.detail||this.i18n.t('support.create_error','Unable to create ticket.'))}finally{this.busy.set(false)}}
 async reply(){const t=this.selected();if(!t)return;this.busy.set(true);try{await this.api.reply(t.id,this.replyBody,this.staff());this.replyBody='';await this.open(t);await this.load()}catch(e:any){this.error.set(e?.error?.detail||this.i18n.t('support.reply_error','Unable to send reply.'))}finally{this.busy.set(false)}}
 async change(data:any){const t=this.selected();if(!t)return;try{await this.api.update(t.id,data);await this.load()}catch(e:any){this.error.set(e?.error?.detail||this.i18n.t('support.update_error','Unable to update ticket.'))}}
 status(v:string){return this.i18n.t('support.status_'+(v==='in_progress'?'progress':v),v)}
}
